{
  "formatVersion": "1.1",
  "component": {
    "url": "../../kotlin-compose-schema/0.17.1/kotlin-compose-schema-0.17.1.module",
    "group": "ai.factoredui",
    "module": "kotlin-compose-schema",
    "version": "0.17.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14"
    }
  },
  "variants": [
    {
      "name": "linuxX64ApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "linux_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.21"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.11.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-datetime",
          "version": {
            "requires": "0.7.1"
          }
        }
      ],
      "files": [
        {
          "name": "kotlin-compose-schema-linuxX64Main-0.17.1.klib",
          "url": "kotlin-compose-schema-linuxx64-0.17.1.klib",
          "size": 112047,
          "sha512": "4df703701a8212104dc4ab852d06d9f472f8661d537612d1a75884eb53230025fd595047706185bceef11559034748d00423d1b61c628fdb1a174d4fe017b170",
          "sha256": "6f19db0d675e752483818af17abbe21042fdb2a5686d59c2cbe685a31abdd3bc",
          "sha1": "6ab0bdc6e6051d211ddcd1e9e9fea311c5908f65",
          "md5": "09b0e754883f192026b26e1a3ba851e5"
        }
      ]
    },
    {
      "name": "linuxX64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "linux_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "files": [
        {
          "name": "kotlin-compose-schema-linuxx64-0.17.1-sources.jar",
          "url": "kotlin-compose-schema-linuxx64-0.17.1-sources.jar",
          "size": 11046,
          "sha512": "cae4c08ab3f9a8344d54c7e0e4fa9269ea8da377662bc4064d80a2cd79f09fee86747b36290041c447b7ad05a090b3b7bcfbbd8da350247fd6ee8dcdd79d58e9",
          "sha256": "ed1a6fb4bff7ef3d57fa32ea9d4747fa020577883dfc09c1f4431e7d0ca4534d",
          "sha1": "aef338a946cb47d02cec2a29e4662c43516a06c2",
          "md5": "96bcd168f6e86923ea03d2264bc834ae"
        }
      ]
    }
  ]
}
