{
  "formatVersion": "1.1",
  "component": {
    "url": "../../kotlin-compose-schema/0.13.1/kotlin-compose-schema-0.13.1.module",
    "group": "ai.factoredui",
    "module": "kotlin-compose-schema",
    "version": "0.13.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14"
    }
  },
  "variants": [
    {
      "name": "iosArm64ApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.21"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.11.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-datetime",
          "version": {
            "requires": "0.7.1"
          }
        }
      ],
      "files": [
        {
          "name": "kotlin-compose-schema-iosArm64Main-0.13.1.klib",
          "url": "kotlin-compose-schema-iosarm64-0.13.1.klib",
          "size": 106211,
          "sha512": "ace2650245043e3fb40c4d0f886677cdf31c84cf668830342622db68eff53735da634aba5f67774f1f9251660b3d31d68dd5694ca817f5931ed03d6c4f667e4c",
          "sha256": "8796d389cda4ed29dfd74bb6d1ec6dfb88933f1a60b8ae6233274c7fa8180d7f",
          "sha1": "91cdb8711aa3456362c280d456c33fbce2bd25f0",
          "md5": "24b9d4ccfbe345ad133f9601cb6a1f5d"
        }
      ]
    },
    {
      "name": "iosArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "files": [
        {
          "name": "kotlin-compose-schema-iosarm64-0.13.1-sources.jar",
          "url": "kotlin-compose-schema-iosarm64-0.13.1-sources.jar",
          "size": 10453,
          "sha512": "3fbb28a198d7de5ca01ed32f9501092fac1b6af51a9b0098c21108f5a5c0608e92c3bd97c5b73aba71a264a999817927b4ebb13dae14cfabad9be095964ba1cc",
          "sha256": "a0966f1f9d3e6583b8dcf8432881a0902108e4151fa59a8d8b62084378017fe3",
          "sha1": "5013c85243b90636719264022c566aa65725c334",
          "md5": "f46850ca8f5deae24a974bcf4cc1901b"
        }
      ]
    },
    {
      "name": "iosArm64MetadataElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.21"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.11.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-datetime",
          "version": {
            "requires": "0.7.1"
          }
        }
      ],
      "files": [
        {
          "name": "kotlin-compose-schema-iosarm64-0.13.1-metadata.jar",
          "url": "kotlin-compose-schema-iosarm64-0.13.1-metadata.jar",
          "size": 261,
          "sha512": "7ffc6128bcc13075e8f31f65a75d6ecc13cbe8122fb0c58cc4ea7ecdc6129a0ae278000d965fe358e1914c6509964546c7602281a50994dd56a6cae0c060c0b8",
          "sha256": "497724ea7862a24de11db0cce3fe4dc2576104c2c93d5146f2c5ac60676a9b61",
          "sha1": "e0721c327b822cf28a343ad9b0a575b48374c879",
          "md5": "5f512e6bdb8a16a1daeca914830a2a76"
        }
      ]
    }
  ]
}
