{
  "formatVersion": "1.1",
  "component": {
    "url": "../../kotlin-compose-schema/0.19.0/kotlin-compose-schema-0.19.0.module",
    "group": "ai.factoredui",
    "module": "kotlin-compose-schema",
    "version": "0.19.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14"
    }
  },
  "variants": [
    {
      "name": "iosX64ApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.21"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.11.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-datetime",
          "version": {
            "requires": "0.7.1"
          }
        }
      ],
      "files": [
        {
          "name": "kotlin-compose-schema-iosX64Main-0.19.0.klib",
          "url": "kotlin-compose-schema-iosx64-0.19.0.klib",
          "size": 112867,
          "sha512": "f67264408b46fd600726f1508aa8b43061dddc8740ba12d6b57061bcefefebdd8e66ac98e5ee3ee2eb45ec4f936458854ecdc458c00e5a7898c8bb4caf93f0a8",
          "sha256": "db001ffb37a006e0cf36f1e90ac18c74c69f4de75da109195be346f6e420f587",
          "sha1": "a3c12227a4a274c38dd4affcebdfef9bee8e5dab",
          "md5": "c7e9975f72dcf429c7fc3192a092eda0"
        }
      ]
    },
    {
      "name": "iosX64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "files": [
        {
          "name": "kotlin-compose-schema-iosx64-0.19.0-sources.jar",
          "url": "kotlin-compose-schema-iosx64-0.19.0-sources.jar",
          "size": 11244,
          "sha512": "4f4fab68f47ca454347578d19a8686b5dc6d91880e982fd2ad2b00f30766de0e444f09cb6f94ced0f2cbd5a2748258be422665dcbc86dba910198bae1d2e7e23",
          "sha256": "98d201c5535c8ec3512dab69330bbbe3c2c19592d3a076c1131fc37ff0739ac7",
          "sha1": "f90a56dd668840053b36c36fb9bfaafba11c0ab9",
          "md5": "93f15f553e8b647097b619e1e104df7c"
        }
      ]
    },
    {
      "name": "iosX64MetadataElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.21"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.11.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-datetime",
          "version": {
            "requires": "0.7.1"
          }
        }
      ],
      "files": [
        {
          "name": "kotlin-compose-schema-iosx64-0.19.0-metadata.jar",
          "url": "kotlin-compose-schema-iosx64-0.19.0-metadata.jar",
          "size": 261,
          "sha512": "382c1cd4d39d6c01cdd2ebb61287f9891c9321fbbc1eb38b568f7499b903680916223b8b6c18874db7e7d71c9a011f4f9cd199c1af05301e347f13e71e41eb46",
          "sha256": "6d4f53c4d050f0cb9010eee38eeb6efc032057e951a896ebe530b02d89207b8a",
          "sha1": "28eda809c2c66a046acf12de48e556a5ce1fcaec",
          "md5": "51be341088d00f238ee27a391a71a2d3"
        }
      ]
    }
  ]
}
