{
  "formatVersion": "1.1",
  "component": {
    "url": "../../kotlin-engine/0.11.0/kotlin-engine-0.11.0.module",
    "group": "ai.factoredui",
    "module": "kotlin-engine",
    "version": "0.11.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14"
    }
  },
  "variants": [
    {
      "name": "iosSimulatorArm64ApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "ai.factoredui",
          "module": "kotlin-compose-schema",
          "version": {
            "requires": "0.13.2"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.21"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.11.0"
          }
        }
      ],
      "files": [
        {
          "name": "kotlin-engine-iosSimulatorArm64Main-0.11.0.klib",
          "url": "kotlin-engine-iossimulatorarm64-0.11.0.klib",
          "size": 74077,
          "sha512": "bd918982472a5e4a01ed3d6d3f59dc72352f2c30dfd7803bef586f60f225504aff0db5fb4f78696b7cd341f0614471ed99b18f03c18e778320d26f96d1ce0ca6",
          "sha256": "24bd5de32f365c20b349af98b6ddf4798699d0529b40abaf4b9fde7ee3c2d8ef",
          "sha1": "d61a6f2a6fcce6962cee0bae2335f0cac8217eb1",
          "md5": "8cfd04c1371201b3c3c39cfc4f938f8c"
        }
      ]
    },
    {
      "name": "iosSimulatorArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "files": [
        {
          "name": "kotlin-engine-iossimulatorarm64-0.11.0-sources.jar",
          "url": "kotlin-engine-iossimulatorarm64-0.11.0-sources.jar",
          "size": 12466,
          "sha512": "64fd9f6420b2aea8e49b9b1c8e9f74b7b1590d51441509053c81d6938126bbd5376f8e3906583c32e296dd31055ab1b9756ddcfed6a9f30f6e8f968bad154fa1",
          "sha256": "dc8377b57cf44787664168ef1d1e1106cfba6c2299e91d4c1eb488ea0d5db025",
          "sha1": "eb97f38572b70bdbf1fe7cb88c68eac18830fc5a",
          "md5": "326b83071cbbb8de717754774c4007c1"
        }
      ]
    },
    {
      "name": "iosSimulatorArm64MetadataElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "ai.factoredui",
          "module": "kotlin-compose-schema",
          "version": {
            "requires": "0.13.2"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.21"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.11.0"
          }
        }
      ],
      "files": [
        {
          "name": "kotlin-engine-iossimulatorarm64-0.11.0-metadata.jar",
          "url": "kotlin-engine-iossimulatorarm64-0.11.0-metadata.jar",
          "size": 261,
          "sha512": "b700d15e799dd032f712e408b6d69a2baa595fb3c7fe565f7197980f72f787859e1536231ffbcfebd20f5539ee792793635491a42a9269b84a076fcee2ed4caa",
          "sha256": "726b52056523201d4670bdeccefc3f973dd51f4beef818bc3b5b3b5ea1054b8e",
          "sha1": "733b0635d75c6842776b1b41864635302863715e",
          "md5": "aa7f531e2a847e9c23b33797421b445d"
        }
      ]
    }
  ]
}
