{
  "formatVersion": "1.1",
  "component": {
    "url": "../../kotlin-compose/0.8.0/kotlin-compose-0.8.0.module",
    "group": "ai.factoredui",
    "module": "kotlin-compose",
    "version": "0.8.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14"
    }
  },
  "variants": [
    {
      "name": "wasmJsApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "wasm",
        "org.jetbrains.kotlin.wasm.target": "js"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.21"
          }
        }
      ],
      "files": [
        {
          "name": "kotlin-compose-wasm-js-0.8.0.klib",
          "url": "kotlin-compose-wasm-js-0.8.0.klib",
          "size": 323168,
          "sha512": "c88e1b711f6d7b9037a6f818d0c8cc096079ea1c89ac2de3565af94440ff5b9a6852c71bb95775971778707e1ca93896183a273e0bdfe0e4bfa4d5e85fe02a7b",
          "sha256": "2ec3f8eabf4933c0c496e740e2cbfff9997d755c3021d1503af2b650ed1e2aac",
          "sha1": "e7092c2262a2f67aab16dd7572dd2cc4b6aec1b7",
          "md5": "1db2595979603e4ac3a17f2004dfe261"
        }
      ]
    },
    {
      "name": "wasmJsRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.platform.type": "wasm",
        "org.jetbrains.kotlin.wasm.target": "js"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.21"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-js",
          "version": {
            "requires": "3.2.0"
          }
        },
        {
          "group": "org.jetbrains.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "1.10.3"
          }
        },
        {
          "group": "org.jetbrains.compose.foundation",
          "module": "foundation",
          "version": {
            "requires": "1.10.3"
          }
        },
        {
          "group": "org.jetbrains.compose.material3",
          "module": "material3",
          "version": {
            "requires": "1.9.0-beta03"
          }
        },
        {
          "group": "org.jetbrains.compose.ui",
          "module": "ui",
          "version": {
            "requires": "1.10.3"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.11.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.10.2"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-datetime",
          "version": {
            "requires": "0.7.1"
          }
        },
        {
          "group": "io.coil-kt.coil3",
          "module": "coil-compose",
          "version": {
            "requires": "3.2.0"
          }
        },
        {
          "group": "io.coil-kt.coil3",
          "module": "coil-network-ktor3",
          "version": {
            "requires": "3.2.0"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-core",
          "version": {
            "requires": "3.2.0"
          }
        }
      ],
      "files": [
        {
          "name": "kotlin-compose-wasm-js-0.8.0.klib",
          "url": "kotlin-compose-wasm-js-0.8.0.klib",
          "size": 323168,
          "sha512": "c88e1b711f6d7b9037a6f818d0c8cc096079ea1c89ac2de3565af94440ff5b9a6852c71bb95775971778707e1ca93896183a273e0bdfe0e4bfa4d5e85fe02a7b",
          "sha256": "2ec3f8eabf4933c0c496e740e2cbfff9997d755c3021d1503af2b650ed1e2aac",
          "sha1": "e7092c2262a2f67aab16dd7572dd2cc4b6aec1b7",
          "md5": "1db2595979603e4ac3a17f2004dfe261"
        }
      ]
    },
    {
      "name": "wasmJsSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.platform.type": "wasm",
        "org.jetbrains.kotlin.wasm.target": "js"
      },
      "files": [
        {
          "name": "kotlin-compose-wasm-js-0.8.0-sources.jar",
          "url": "kotlin-compose-wasm-js-0.8.0-sources.jar",
          "size": 53029,
          "sha512": "78164caeee234f209136aab5a55bbbe56e0a694b481172e5a7e6eb9209846eca19f428e50e7988bbab9261d70b2dae15fca404b2ca4ca9f120671a68c40acf22",
          "sha256": "dee1ff1973b3e352264b4e3c0e59a10c717fd74d3ba7badfee7f7d8e15e1dc59",
          "sha1": "b5e0416c420616446b52df3990d3c30341431f73",
          "md5": "b8cd37a9e3bddbb6d5b88d00ce9bedb1"
        }
      ]
    },
    {
      "name": "wasmJsResourcesElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.libraryelements": "kotlin-multiplatformresourcesjs",
        "org.gradle.usage": "kotlin-multiplatformresourcesjs",
        "org.jetbrains.kotlin.platform.type": "wasm",
        "org.jetbrains.kotlin.wasm.target": "js"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.21"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-js",
          "version": {
            "requires": "3.2.0"
          }
        },
        {
          "group": "org.jetbrains.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "1.10.3"
          }
        },
        {
          "group": "org.jetbrains.compose.foundation",
          "module": "foundation",
          "version": {
            "requires": "1.10.3"
          }
        },
        {
          "group": "org.jetbrains.compose.material3",
          "module": "material3",
          "version": {
            "requires": "1.9.0-beta03"
          }
        },
        {
          "group": "org.jetbrains.compose.ui",
          "module": "ui",
          "version": {
            "requires": "1.10.3"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.11.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.10.2"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-datetime",
          "version": {
            "requires": "0.7.1"
          }
        },
        {
          "group": "io.coil-kt.coil3",
          "module": "coil-compose",
          "version": {
            "requires": "3.2.0"
          }
        },
        {
          "group": "io.coil-kt.coil3",
          "module": "coil-network-ktor3",
          "version": {
            "requires": "3.2.0"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-core",
          "version": {
            "requires": "3.2.0"
          }
        }
      ],
      "files": [
        {
          "name": "kotlin-compose-0.8.0.kotlin_resources.zip",
          "url": "kotlin-compose-wasm-js-0.8.0-kotlin_resources.kotlin_resources.zip",
          "size": 344,
          "sha512": "2c66de28727e02a46e5c9409122342c79fb890981504fcb9c84b9ad146a05ed0b7c2e0d5e846de003584adb2db038e45c2b7d71d0cce88b67d17a1ffe5050c89",
          "sha256": "1e0aa8b2ed644f20e8b7430190aac5162f5d3b0c5e930fe38aabe8783747c6a4",
          "sha1": "6c49d8f69f774147fca6f6d14384d6e66ff3492e",
          "md5": "1e53da7765cf43a147babf1448e7c0d1"
        }
      ]
    }
  ]
}
