{
  "formatVersion": "1.1",
  "component": {
    "url": "../../kotlin-compose-capture/0.20.3/kotlin-compose-capture-0.20.3.module",
    "group": "ai.factoredui",
    "module": "kotlin-compose-capture",
    "version": "0.20.3",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14"
    }
  },
  "variants": [
    {
      "name": "iosSimulatorArm64ApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.21"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.11.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-datetime",
          "version": {
            "requires": "0.7.1"
          }
        }
      ],
      "files": [
        {
          "name": "kotlin-compose-capture-iosSimulatorArm64Main-0.20.3.klib",
          "url": "kotlin-compose-capture-iossimulatorarm64-0.20.3.klib",
          "size": 22709,
          "sha512": "5a5436bd67ef1fd250881eeb297365fa79e22d9b2b90b9bbca141e6f2e3ff05093ccbf6dbbb963d20e2666c69c3da3b0c9507e8217264df9a5c7bc9e981e262d",
          "sha256": "7b7db9eaab63c914a428d67db601645f43c21c29c0842844290d92faf5d821df",
          "sha1": "69b54f5e07f2b312f3e3d939d97583b1b1429342",
          "md5": "e2f7fdddfc40a6e52fab52e4c6a1a5f4"
        }
      ]
    },
    {
      "name": "iosSimulatorArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "files": [
        {
          "name": "kotlin-compose-capture-iossimulatorarm64-0.20.3-sources.jar",
          "url": "kotlin-compose-capture-iossimulatorarm64-0.20.3-sources.jar",
          "size": 2675,
          "sha512": "2f30e91c5b3bb7af31334533cd53498c1f205f723d4956b8bd8d8d2c9480058b2ae47a8fdca96e615561199fa50a6a22b561bc5220848629ef7fe47dd537c6ef",
          "sha256": "c82f37fc21d50fc8ecc030b86b4137334808ac44ee33a7e7732c739eb29d0700",
          "sha1": "84a2b3c08bc728e17e68a868cfa57eada683f007",
          "md5": "1ce993c162e5d1582ebec69fad7b8a80"
        }
      ]
    },
    {
      "name": "iosSimulatorArm64MetadataElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.21"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.11.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-datetime",
          "version": {
            "requires": "0.7.1"
          }
        }
      ],
      "files": [
        {
          "name": "kotlin-compose-capture-iossimulatorarm64-0.20.3-metadata.jar",
          "url": "kotlin-compose-capture-iossimulatorarm64-0.20.3-metadata.jar",
          "size": 261,
          "sha512": "552b33ece4c635c75301760f4ee6a274b2dec51a1308de5d5bd91018669f39cca8e7c710a6a545674df4fa108f942f79c5c4646d8fad2ebee7c2b2f3a98df0b2",
          "sha256": "d6f2d8e6f25081c1f895c31142b2fd07d487e39fbe43763519c9626f6f31ea23",
          "sha1": "755facae58fbd5524db5e356070392a5ba4e01af",
          "md5": "5451aede563e35618c4b4afd2fd8d623"
        }
      ]
    }
  ]
}
