{
  "formatVersion": "1.1",
  "component": {
    "url": "../../kotlin-compose/0.4.1/kotlin-compose-0.4.1.module",
    "group": "ai.factoredui",
    "module": "kotlin-compose",
    "version": "0.4.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.10.2"
    }
  },
  "variants": [
    {
      "name": "wasmJsApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "wasm",
        "org.jetbrains.kotlin.wasm.target": "js"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.21"
          }
        }
      ],
      "files": [
        {
          "name": "kotlin-compose-wasm-js-0.4.1.klib",
          "url": "kotlin-compose-wasm-js-0.4.1.klib",
          "size": 299733,
          "sha512": "922bf9575a2776cf50e4a99ef95a2d04881977fbc1594b1d6398d2e98ee2c29e87dcb88b87383e43130e8fb10c8f058833969c3b3a2cb1313872029f5a3c8113",
          "sha256": "c15b98caf95f1341566b61e762911de8e9268a3b7976ec3c14407060f52ce6de",
          "sha1": "a9f46ca61240610b0466eaf4415b9fa8b102a89e",
          "md5": "942de7421d4bd97eca9c35b75f8b7192"
        }
      ]
    },
    {
      "name": "wasmJsRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.platform.type": "wasm",
        "org.jetbrains.kotlin.wasm.target": "js"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.21"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-js",
          "version": {
            "requires": "3.0.3"
          }
        },
        {
          "group": "org.jetbrains.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "1.7.3"
          }
        },
        {
          "group": "org.jetbrains.compose.foundation",
          "module": "foundation",
          "version": {
            "requires": "1.7.3"
          }
        },
        {
          "group": "org.jetbrains.compose.material3",
          "module": "material3",
          "version": {
            "requires": "1.7.3"
          }
        },
        {
          "group": "org.jetbrains.compose.ui",
          "module": "ui",
          "version": {
            "requires": "1.7.3"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.7.3"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-datetime",
          "version": {
            "requires": "0.6.1"
          }
        },
        {
          "group": "io.coil-kt.coil3",
          "module": "coil-compose",
          "version": {
            "requires": "3.0.4"
          }
        },
        {
          "group": "io.coil-kt.coil3",
          "module": "coil-network-ktor3",
          "version": {
            "requires": "3.0.4"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-core",
          "version": {
            "requires": "3.0.3"
          }
        }
      ],
      "files": [
        {
          "name": "kotlin-compose-wasm-js-0.4.1.klib",
          "url": "kotlin-compose-wasm-js-0.4.1.klib",
          "size": 299733,
          "sha512": "922bf9575a2776cf50e4a99ef95a2d04881977fbc1594b1d6398d2e98ee2c29e87dcb88b87383e43130e8fb10c8f058833969c3b3a2cb1313872029f5a3c8113",
          "sha256": "c15b98caf95f1341566b61e762911de8e9268a3b7976ec3c14407060f52ce6de",
          "sha1": "a9f46ca61240610b0466eaf4415b9fa8b102a89e",
          "md5": "942de7421d4bd97eca9c35b75f8b7192"
        }
      ]
    },
    {
      "name": "wasmJsSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.platform.type": "wasm",
        "org.jetbrains.kotlin.wasm.target": "js"
      },
      "files": [
        {
          "name": "kotlin-compose-wasm-js-0.4.1-sources.jar",
          "url": "kotlin-compose-wasm-js-0.4.1-sources.jar",
          "size": 41375,
          "sha512": "15dbde7994543c680cfc6d50a683e8b1c7e87ce21e9b547c4a731eea2d06bc5ac35d6d20829b60138be76d55188df9ecb75da22fef0e46f006cebdd5ddfd643e",
          "sha256": "578274b3eaa058fc2d38f08ae2a157fc4a277f430a4c6439d110f8431ce56830",
          "sha1": "439887af88a4aef41aaa06b00eb6950348ea46d5",
          "md5": "f32eccaca592026582447f7546cd0a76"
        }
      ]
    },
    {
      "name": "wasmJsResourcesElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.libraryelements": "kotlin-multiplatformresourcesjs",
        "org.gradle.usage": "kotlin-multiplatformresourcesjs",
        "org.jetbrains.kotlin.platform.type": "wasm",
        "org.jetbrains.kotlin.wasm.target": "js"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.21"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-js",
          "version": {
            "requires": "3.0.3"
          }
        },
        {
          "group": "org.jetbrains.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "1.7.3"
          }
        },
        {
          "group": "org.jetbrains.compose.foundation",
          "module": "foundation",
          "version": {
            "requires": "1.7.3"
          }
        },
        {
          "group": "org.jetbrains.compose.material3",
          "module": "material3",
          "version": {
            "requires": "1.7.3"
          }
        },
        {
          "group": "org.jetbrains.compose.ui",
          "module": "ui",
          "version": {
            "requires": "1.7.3"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.7.3"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-datetime",
          "version": {
            "requires": "0.6.1"
          }
        },
        {
          "group": "io.coil-kt.coil3",
          "module": "coil-compose",
          "version": {
            "requires": "3.0.4"
          }
        },
        {
          "group": "io.coil-kt.coil3",
          "module": "coil-network-ktor3",
          "version": {
            "requires": "3.0.4"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-core",
          "version": {
            "requires": "3.0.3"
          }
        }
      ],
      "files": [
        {
          "name": "kotlin-compose-0.4.1.kotlin_resources.zip",
          "url": "kotlin-compose-wasm-js-0.4.1-kotlin_resources.kotlin_resources.zip",
          "size": 344,
          "sha512": "4f0477bc6ddd2f8c5be9490d6b8a2918efa8a00bc0daca7fa390c8b760fc620548eb033cdd4acd33cf2853f51eb5eaa6510e254153aee753fa1a55bce09cac70",
          "sha256": "34ae3bcf0d5d369646cef06c38354d328e9b8255d8a371a56666787be0bccfa1",
          "sha1": "272b25b436ee0bf7fe04e0b6cc822511195ca622",
          "md5": "4a7752e4b97680f886e0ee6444ee0957"
        }
      ]
    }
  ]
}
