{
  "formatVersion": "1.1",
  "component": {
    "url": "../../kotlin-compose/0.13.1/kotlin-compose-0.13.1.module",
    "group": "ai.factoredui",
    "module": "kotlin-compose",
    "version": "0.13.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14"
    }
  },
  "variants": [
    {
      "name": "desktopApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "ai.factoredui",
          "module": "kotlin-compose-schema",
          "version": {
            "requires": "0.13.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.21"
          }
        }
      ],
      "files": [
        {
          "name": "kotlin-compose-desktop-0.13.1.jar",
          "url": "kotlin-compose-desktop-0.13.1.jar",
          "size": 805062,
          "sha512": "2e49226339f7dcf47a3a6ba348ec95382da3f569fd688ef50eda0d2d15933b4cdbd743912450be9d7d3df1718ff67d6f701a244786b20ce63393fe7251655ea3",
          "sha256": "618e0151f45c02bd48f76112dc1aa6f9020157d401f1fd355bd7818daca09e37",
          "sha1": "d85386b0d7b59157a2bdfaff4651234db7edc8df",
          "md5": "439acfd51f5a054f58779a2932294d52"
        }
      ]
    },
    {
      "name": "desktopRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "ai.factoredui",
          "module": "kotlin-compose-schema",
          "version": {
            "requires": "0.13.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.21"
          }
        },
        {
          "group": "org.jetbrains.compose.desktop",
          "module": "desktop-jvm-linux-x64",
          "version": {
            "requires": "1.10.3"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-okhttp",
          "version": {
            "requires": "3.2.0"
          }
        },
        {
          "group": "org.jetbrains.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "1.10.3"
          }
        },
        {
          "group": "org.jetbrains.compose.foundation",
          "module": "foundation",
          "version": {
            "requires": "1.10.3"
          }
        },
        {
          "group": "org.jetbrains.compose.material3",
          "module": "material3",
          "version": {
            "requires": "1.9.0-beta03"
          }
        },
        {
          "group": "org.jetbrains.compose.ui",
          "module": "ui",
          "version": {
            "requires": "1.10.3"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.11.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.10.2"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-datetime",
          "version": {
            "requires": "0.7.1"
          }
        },
        {
          "group": "io.coil-kt.coil3",
          "module": "coil-compose",
          "version": {
            "requires": "3.2.0"
          }
        },
        {
          "group": "io.coil-kt.coil3",
          "module": "coil-network-ktor3",
          "version": {
            "requires": "3.2.0"
          }
        },
        {
          "group": "io.coil-kt.coil3",
          "module": "coil-svg",
          "version": {
            "requires": "3.2.0"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-core",
          "version": {
            "requires": "3.2.0"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-content-negotiation",
          "version": {
            "requires": "3.2.0"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-serialization-kotlinx-json",
          "version": {
            "requires": "3.2.0"
          }
        }
      ],
      "files": [
        {
          "name": "kotlin-compose-desktop-0.13.1.jar",
          "url": "kotlin-compose-desktop-0.13.1.jar",
          "size": 805062,
          "sha512": "2e49226339f7dcf47a3a6ba348ec95382da3f569fd688ef50eda0d2d15933b4cdbd743912450be9d7d3df1718ff67d6f701a244786b20ce63393fe7251655ea3",
          "sha256": "618e0151f45c02bd48f76112dc1aa6f9020157d401f1fd355bd7818daca09e37",
          "sha1": "d85386b0d7b59157a2bdfaff4651234db7edc8df",
          "md5": "439acfd51f5a054f58779a2932294d52"
        }
      ]
    },
    {
      "name": "desktopSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "kotlin-compose-desktop-0.13.1-sources.jar",
          "url": "kotlin-compose-desktop-0.13.1-sources.jar",
          "size": 94303,
          "sha512": "1b6607d85d2c9b96a8406e43895e609d39db5ca456507ac4c32c1660d9f36f76ed2318eb7e052c768a6ddf62c3847f398333c11a7af9f1fe00b42e91e4c02d28",
          "sha256": "22c4162650fd172308e27f30d138175e46e51f45f40930f3bc1c26554c9cd6d3",
          "sha1": "b6296602a00a652c47bac507f561906ff9a700ac",
          "md5": "6d21c467e476e098bb882eba49fe0535"
        }
      ]
    }
  ]
}
