{
  "formatVersion": "1.1",
  "component": {
    "url": "../../kotlin-compose/0.20.2/kotlin-compose-0.20.2.module",
    "group": "ai.factoredui",
    "module": "kotlin-compose",
    "version": "0.20.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14"
    }
  },
  "variants": [
    {
      "name": "desktopApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "ai.factoredui",
          "module": "kotlin-compose-schema",
          "version": {
            "requires": "0.20.2"
          }
        },
        {
          "group": "ai.factoredui",
          "module": "kotlin-compose-capture",
          "version": {
            "requires": "0.20.2"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.21"
          }
        }
      ],
      "files": [
        {
          "name": "kotlin-compose-desktop-0.20.2.jar",
          "url": "kotlin-compose-desktop-0.20.2.jar",
          "size": 894615,
          "sha512": "5ce1b0a672cbabd038b00b526bda14ae9cfe08c2d28a7be6e03ba3f5a345d5d560ae47a4d47b8d1e68f60c14bac5c976056237d04bf9cb8665ba3db74770de89",
          "sha256": "bd733732b18a98ee7e0264a0eb380767bffa8822d478279c28857b2d394d2d79",
          "sha1": "4051772696927c858642808435615fec46242bc6",
          "md5": "deb522e202fb6f4a03f23f850e3404e6"
        }
      ]
    },
    {
      "name": "desktopRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "ai.factoredui",
          "module": "kotlin-compose-schema",
          "version": {
            "requires": "0.20.2"
          }
        },
        {
          "group": "ai.factoredui",
          "module": "kotlin-compose-capture",
          "version": {
            "requires": "0.20.2"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.21"
          }
        },
        {
          "group": "org.jetbrains.compose.desktop",
          "module": "desktop",
          "version": {
            "requires": "1.10.3"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-okhttp",
          "version": {
            "requires": "3.2.4"
          }
        },
        {
          "group": "org.jetbrains.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "1.10.3"
          }
        },
        {
          "group": "org.jetbrains.compose.foundation",
          "module": "foundation",
          "version": {
            "requires": "1.10.3"
          }
        },
        {
          "group": "org.jetbrains.compose.material3",
          "module": "material3",
          "version": {
            "requires": "1.9.0-beta03"
          }
        },
        {
          "group": "org.jetbrains.compose.ui",
          "module": "ui",
          "version": {
            "requires": "1.10.3"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.11.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.10.2"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-datetime",
          "version": {
            "requires": "0.7.1"
          }
        },
        {
          "group": "io.coil-kt.coil3",
          "module": "coil-compose",
          "version": {
            "requires": "3.2.0"
          }
        },
        {
          "group": "io.coil-kt.coil3",
          "module": "coil-network-ktor3",
          "version": {
            "requires": "3.2.0"
          }
        },
        {
          "group": "io.coil-kt.coil3",
          "module": "coil-svg",
          "version": {
            "requires": "3.2.0"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-core",
          "version": {
            "requires": "3.2.4"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-content-negotiation",
          "version": {
            "requires": "3.2.4"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-serialization-kotlinx-json",
          "version": {
            "requires": "3.2.4"
          }
        }
      ],
      "files": [
        {
          "name": "kotlin-compose-desktop-0.20.2.jar",
          "url": "kotlin-compose-desktop-0.20.2.jar",
          "size": 894615,
          "sha512": "5ce1b0a672cbabd038b00b526bda14ae9cfe08c2d28a7be6e03ba3f5a345d5d560ae47a4d47b8d1e68f60c14bac5c976056237d04bf9cb8665ba3db74770de89",
          "sha256": "bd733732b18a98ee7e0264a0eb380767bffa8822d478279c28857b2d394d2d79",
          "sha1": "4051772696927c858642808435615fec46242bc6",
          "md5": "deb522e202fb6f4a03f23f850e3404e6"
        }
      ]
    },
    {
      "name": "desktopSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "kotlin-compose-desktop-0.20.2-sources.jar",
          "url": "kotlin-compose-desktop-0.20.2-sources.jar",
          "size": 109324,
          "sha512": "831d27482a101bc5ef1abfbe4a1dbb8a7b5a0beea8148a81bbaf497d5f0f23ff5c83a8fdc128bbc86e8e387cce37d19f4a36ab6d1fc8cd92bc94e5dd4198d028",
          "sha256": "ebde35e8a3dd1af3d37f1182cdca783f5198b296b4992bd815157d22f80c0691",
          "sha1": "b1ee0995740f6a666d6251d8f393a77ee24ce69d",
          "md5": "acead3309e88547939c00c1feec98d88"
        }
      ]
    }
  ]
}
