{
  "formatVersion": "1.1",
  "component": {
    "url": "../../kotlin-compose-schema/0.20.7/kotlin-compose-schema-0.20.7.module",
    "group": "ai.factoredui",
    "module": "kotlin-compose-schema",
    "version": "0.20.7",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14"
    }
  },
  "variants": [
    {
      "name": "iosSimulatorArm64ApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.21"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.11.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-datetime",
          "version": {
            "requires": "0.7.1"
          }
        }
      ],
      "files": [
        {
          "name": "kotlin-compose-schema-iosSimulatorArm64Main-0.20.7.klib",
          "url": "kotlin-compose-schema-iossimulatorarm64-0.20.7.klib",
          "size": 140341,
          "sha512": "40b4dcd0f95ffceb5ec323aaee489af64d1462ed4e54fde5f7594dfb0d27ebcc046233872cccb23711dab823286b20cf48da19b2fecdeea225680555c2c87f2c",
          "sha256": "3eca19787a213a2c16a84a2b2bcf1f7638e836bba2a4034bd6bc4f888f6728f2",
          "sha1": "42263b5bc3914ef39821cb59667bca6af242fda5",
          "md5": "743f377c97a48915032951a09ee588b3"
        }
      ]
    },
    {
      "name": "iosSimulatorArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "files": [
        {
          "name": "kotlin-compose-schema-iossimulatorarm64-0.20.7-sources.jar",
          "url": "kotlin-compose-schema-iossimulatorarm64-0.20.7-sources.jar",
          "size": 12896,
          "sha512": "1f8eec231bb59f13ab0a1e2aac85f9f8e201081805972512f2f28ea743d54f2d8fc6bfdc9dd88970f7c8d64546cc78401c5c6f316204cbf20b1ea6368a8ef793",
          "sha256": "ca7b1c8612282eeb2c1391b6f3da13cfbcc0c44c72c0e6ca6193c844db9a5fdd",
          "sha1": "3dde30d0160d2f7d0843c764314d54909d01f06d",
          "md5": "d552ea9172056e2e5e0d8bf0aa4f36be"
        }
      ]
    },
    {
      "name": "iosSimulatorArm64MetadataElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.21"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.11.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-datetime",
          "version": {
            "requires": "0.7.1"
          }
        }
      ],
      "files": [
        {
          "name": "kotlin-compose-schema-iossimulatorarm64-0.20.7-metadata.jar",
          "url": "kotlin-compose-schema-iossimulatorarm64-0.20.7-metadata.jar",
          "size": 261,
          "sha512": "f97199bda5aebeed2e9737b67e6c751a459af823f45cec99e830ab4cc41df92e013d96391af67c9c77aa33855062d548f8eaa4cc6dffcf26a79de7dba5fb3610",
          "sha256": "f2ef82cb4d053fc19688194f8229ed0cab55db73fd129b8b63cb5caab9f79f00",
          "sha1": "99bc08a7419384cdc01f340cf5f6b469bf64d28c",
          "md5": "f46be8be7e73d72d9f6d3ca8a986fa8c"
        }
      ]
    }
  ]
}
