{
  "formatVersion": "1.1",
  "component": {
    "url": "../../kotlin-compose-schema/0.19.0/kotlin-compose-schema-0.19.0.module",
    "group": "ai.factoredui",
    "module": "kotlin-compose-schema",
    "version": "0.19.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14"
    }
  },
  "variants": [
    {
      "name": "wasmJsApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "wasm",
        "org.jetbrains.kotlin.wasm.target": "js"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.21"
          }
        }
      ],
      "files": [
        {
          "name": "kotlin-compose-schema-wasm-js-0.19.0.klib",
          "url": "kotlin-compose-schema-wasm-js-0.19.0.klib",
          "size": 109384,
          "sha512": "6ed601cd9221436229c8306a5d1f3a52b2d37df3a30dcbea6744b3fca6cfb5c2bc6a977d44a3107342d48fc3dc9e87e9a87187d71f7d39204a2cf3b4d4c2bf1a",
          "sha256": "b43921b79c4c81261f941482f277a19b85bf3e60685d689069155e62d912eb55",
          "sha1": "d87d551d8e79012d93e541d58bfe1a58435f8ae4",
          "md5": "401c062b539bdf11ae55655b0a50b7d1"
        }
      ]
    },
    {
      "name": "wasmJsRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.platform.type": "wasm",
        "org.jetbrains.kotlin.wasm.target": "js"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.21"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.11.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-datetime",
          "version": {
            "requires": "0.7.1"
          }
        }
      ],
      "files": [
        {
          "name": "kotlin-compose-schema-wasm-js-0.19.0.klib",
          "url": "kotlin-compose-schema-wasm-js-0.19.0.klib",
          "size": 109384,
          "sha512": "6ed601cd9221436229c8306a5d1f3a52b2d37df3a30dcbea6744b3fca6cfb5c2bc6a977d44a3107342d48fc3dc9e87e9a87187d71f7d39204a2cf3b4d4c2bf1a",
          "sha256": "b43921b79c4c81261f941482f277a19b85bf3e60685d689069155e62d912eb55",
          "sha1": "d87d551d8e79012d93e541d58bfe1a58435f8ae4",
          "md5": "401c062b539bdf11ae55655b0a50b7d1"
        }
      ]
    },
    {
      "name": "wasmJsSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.platform.type": "wasm",
        "org.jetbrains.kotlin.wasm.target": "js"
      },
      "files": [
        {
          "name": "kotlin-compose-schema-wasm-js-0.19.0-sources.jar",
          "url": "kotlin-compose-schema-wasm-js-0.19.0-sources.jar",
          "size": 11244,
          "sha512": "4f4fab68f47ca454347578d19a8686b5dc6d91880e982fd2ad2b00f30766de0e444f09cb6f94ced0f2cbd5a2748258be422665dcbc86dba910198bae1d2e7e23",
          "sha256": "98d201c5535c8ec3512dab69330bbbe3c2c19592d3a076c1131fc37ff0739ac7",
          "sha1": "f90a56dd668840053b36c36fb9bfaafba11c0ab9",
          "md5": "93f15f553e8b647097b619e1e104df7c"
        }
      ]
    }
  ]
}
