{
  "formatVersion": "1.1",
  "component": {
    "url": "../../kotlin-compose-schema/0.11.0/kotlin-compose-schema-0.11.0.module",
    "group": "ai.factoredui",
    "module": "kotlin-compose-schema",
    "version": "0.11.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14"
    }
  },
  "variants": [
    {
      "name": "linuxX64ApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "linux_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.21"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.11.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-datetime",
          "version": {
            "requires": "0.7.1"
          }
        }
      ],
      "files": [
        {
          "name": "kotlin-compose-schema-linuxX64Main-0.11.0.klib",
          "url": "kotlin-compose-schema-linuxx64-0.11.0.klib",
          "size": 104158,
          "sha512": "355ac0d8c68a60044c859152fd774e9786544e71222d73f56603c5e0ef419e1cf52e7c528944076fff3dcd4f44b3e7dce767883e7f6927f35947a3e189ba6387",
          "sha256": "cb15c6a547e3f68f37e58855fa5ae877975728f0ab816a3af2de8bba6a45c03f",
          "sha1": "3438f8026cf7776548a9764f84c827ec4f49d038",
          "md5": "afe1049d7ed34b455fb42ccfe85d88bf"
        }
      ]
    },
    {
      "name": "linuxX64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "linux_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "files": [
        {
          "name": "kotlin-compose-schema-linuxx64-0.11.0-sources.jar",
          "url": "kotlin-compose-schema-linuxx64-0.11.0-sources.jar",
          "size": 10330,
          "sha512": "a382fccd52fdda3052f9860ae1672b6ddec46e4a42b1e470b34abe77f572b3c7c6147c02fc717466e1728d23e9cfe6ba79773e05c07e1dd4eab4c783616c743c",
          "sha256": "56a70713b4824ac51521f5bf2b1de228e11b1f7f41ba3da94a83ac3f6562aba9",
          "sha1": "143eaa67fbf50a4e8d67677a653de0d876e21a0e",
          "md5": "2d6fb7c3de3193d0eebbfafcccb1d343"
        }
      ]
    }
  ]
}
