{
  "formatVersion": "1.1",
  "component": {
    "url": "../../kotlin-compose/0.11.0/kotlin-compose-0.11.0.module",
    "group": "ai.factoredui",
    "module": "kotlin-compose",
    "version": "0.11.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14"
    }
  },
  "variants": [
    {
      "name": "desktopApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "ai.factoredui",
          "module": "kotlin-compose-schema",
          "version": {
            "requires": "0.11.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.21"
          }
        }
      ],
      "files": [
        {
          "name": "kotlin-compose-desktop-0.11.0.jar",
          "url": "kotlin-compose-desktop-0.11.0.jar",
          "size": 721866,
          "sha512": "cdb99232396603ed166ee1b22be70d266a773e58295ba44aaad440cd4b838a7d67a2f68f0fee33e3bc33413dbe6ae9455df26042eecb65e4e354f2c9f5c41ef2",
          "sha256": "10a5e5f1aa2119f56f7234b8abe2698ae24ec1c4a83aa7cbc4932be7ac3178ef",
          "sha1": "f7c1ee9b0537ca20f3203e8ad57bca0c2204950e",
          "md5": "46a4d3bb6186316c02c641d3f0f8bc21"
        }
      ]
    },
    {
      "name": "desktopRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "ai.factoredui",
          "module": "kotlin-compose-schema",
          "version": {
            "requires": "0.11.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.21"
          }
        },
        {
          "group": "org.jetbrains.compose.desktop",
          "module": "desktop-jvm-linux-x64",
          "version": {
            "requires": "1.10.3"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-okhttp",
          "version": {
            "requires": "3.2.0"
          }
        },
        {
          "group": "org.jetbrains.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "1.10.3"
          }
        },
        {
          "group": "org.jetbrains.compose.foundation",
          "module": "foundation",
          "version": {
            "requires": "1.10.3"
          }
        },
        {
          "group": "org.jetbrains.compose.material3",
          "module": "material3",
          "version": {
            "requires": "1.9.0-beta03"
          }
        },
        {
          "group": "org.jetbrains.compose.ui",
          "module": "ui",
          "version": {
            "requires": "1.10.3"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.11.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.10.2"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-datetime",
          "version": {
            "requires": "0.7.1"
          }
        },
        {
          "group": "io.coil-kt.coil3",
          "module": "coil-compose",
          "version": {
            "requires": "3.2.0"
          }
        },
        {
          "group": "io.coil-kt.coil3",
          "module": "coil-network-ktor3",
          "version": {
            "requires": "3.2.0"
          }
        },
        {
          "group": "io.coil-kt.coil3",
          "module": "coil-svg",
          "version": {
            "requires": "3.2.0"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-core",
          "version": {
            "requires": "3.2.0"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-content-negotiation",
          "version": {
            "requires": "3.2.0"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-serialization-kotlinx-json",
          "version": {
            "requires": "3.2.0"
          }
        }
      ],
      "files": [
        {
          "name": "kotlin-compose-desktop-0.11.0.jar",
          "url": "kotlin-compose-desktop-0.11.0.jar",
          "size": 721866,
          "sha512": "cdb99232396603ed166ee1b22be70d266a773e58295ba44aaad440cd4b838a7d67a2f68f0fee33e3bc33413dbe6ae9455df26042eecb65e4e354f2c9f5c41ef2",
          "sha256": "10a5e5f1aa2119f56f7234b8abe2698ae24ec1c4a83aa7cbc4932be7ac3178ef",
          "sha1": "f7c1ee9b0537ca20f3203e8ad57bca0c2204950e",
          "md5": "46a4d3bb6186316c02c641d3f0f8bc21"
        }
      ]
    },
    {
      "name": "desktopSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "kotlin-compose-desktop-0.11.0-sources.jar",
          "url": "kotlin-compose-desktop-0.11.0-sources.jar",
          "size": 87722,
          "sha512": "d39f291de2e0f6cc4017fbce900b725602f7bc515dfccfa63bc498d272effcaf359f0265569bc64b085316004ba396bce8e43274f730257c0ead50acd4a2f009",
          "sha256": "5300cdb34ac545fe16830a5bb9b0b22805a73d18dcbf82cc3898a3f502145166",
          "sha1": "b0ec23592245cf7a066e13432c0f71a76d24a4c4",
          "md5": "13ae4b7dac14fb3cbc2c38eaf47a6833"
        }
      ]
    }
  ]
}
