{
  "formatVersion": "1.1",
  "component": {
    "url": "../../kotlin-compose-schema/0.10.0/kotlin-compose-schema-0.10.0.module",
    "group": "ai.factoredui",
    "module": "kotlin-compose-schema",
    "version": "0.10.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14"
    }
  },
  "variants": [
    {
      "name": "iosX64ApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.21"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.11.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-datetime",
          "version": {
            "requires": "0.7.1"
          }
        }
      ],
      "files": [
        {
          "name": "kotlin-compose-schema-iosX64Main-0.10.0.klib",
          "url": "kotlin-compose-schema-iosx64-0.10.0.klib",
          "size": 99071,
          "sha512": "ea1df5678bf03e97caec44bb4936a0333b190d45b29a8756fe23704b09efb7fb0e0b54102980125ff7e1378fbf463da5e415fe437e51721657085d4471f72ee3",
          "sha256": "0147eb9abcb1d536dc6e84e6068fdda891250724ddd09ddcf5c95713ae95f72f",
          "sha1": "9bc392f46c0b1647f2e06a53bd950ab87c9c2eb6",
          "md5": "1aee8ca54cba128d1dbb82f34965b0c6"
        }
      ]
    },
    {
      "name": "iosX64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "files": [
        {
          "name": "kotlin-compose-schema-iosx64-0.10.0-sources.jar",
          "url": "kotlin-compose-schema-iosx64-0.10.0-sources.jar",
          "size": 10001,
          "sha512": "71cec9d5887d8c8550ef4f906682c9132c7f5c113b54a19b2cab1f702ab714693db442e4ec6308070795d47a25976d72d12638f368a0fb9b42b198d33e43d898",
          "sha256": "f7c01cbaa1bdaea32adcfe422e834bd8a159d7552b9f210042929c82ad087f32",
          "sha1": "f4b105061fc01c35414b5766a1200f469695849b",
          "md5": "129b40ea92cc22a10556906f7c1ac502"
        }
      ]
    },
    {
      "name": "iosX64MetadataElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.21"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.11.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-datetime",
          "version": {
            "requires": "0.7.1"
          }
        }
      ],
      "files": [
        {
          "name": "kotlin-compose-schema-iosx64-0.10.0-metadata.jar",
          "url": "kotlin-compose-schema-iosx64-0.10.0-metadata.jar",
          "size": 261,
          "sha512": "2f5e7e8f59c007771f96e33beb51e96a251c5f4c88440c69fa4ae159ab84b15d5ea178a22676aacceebbe0494e5a1744d0904e1100a315d33c02648c153f88c9",
          "sha256": "50ac1bd0d5da709283e99f52841cc58b6207311581cfb39168e4b42bf791480b",
          "sha1": "da946aef10fa6afc7fe4bab640959e5791db4779",
          "md5": "534930d641a41418631c738b65f06af9"
        }
      ]
    }
  ]
}
