{
  "formatVersion": "1.1",
  "component": {
    "url": "../../kotlin-compose-schema/0.20.1/kotlin-compose-schema-0.20.1.module",
    "group": "ai.factoredui",
    "module": "kotlin-compose-schema",
    "version": "0.20.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14"
    }
  },
  "variants": [
    {
      "name": "linuxX64ApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "linux_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.21"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.11.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-datetime",
          "version": {
            "requires": "0.7.1"
          }
        }
      ],
      "files": [
        {
          "name": "kotlin-compose-schema-linuxX64Main-0.20.1.klib",
          "url": "kotlin-compose-schema-linuxx64-0.20.1.klib",
          "size": 125933,
          "sha512": "92461ae7a0c337c057935e04422df0f6b6fcc606153d381ebaf1940148d1a4a7beda8b689e9b37019281232134a331e95574b4ad25a47eae194d0bb403e19226",
          "sha256": "15b633f9196ee20b0841fc8cdbe099c58e8283bb76b2f12083ad4d07a73e6bd4",
          "sha1": "56ee9c2199b775d248e38aa2458ff64dcb767c3f",
          "md5": "cacc252a3c597054b0769e0b48914686"
        }
      ]
    },
    {
      "name": "linuxX64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "linux_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "files": [
        {
          "name": "kotlin-compose-schema-linuxx64-0.20.1-sources.jar",
          "url": "kotlin-compose-schema-linuxx64-0.20.1-sources.jar",
          "size": 11925,
          "sha512": "d1645926de0ed497e29af6c88a436b8b476605cbcf4c24d77f201dde5dc5c9cc1ebab9abcc50f0ac083e71007b9d0274013de0c58ad30852cae2bab4e9d00cb1",
          "sha256": "73d01c96b3c64ca8363f6f66713809c860ec92db0979d282b8a093525ea084e0",
          "sha1": "91339d0e477881713eba748395a8388c2c5e97d9",
          "md5": "dd76c50fd5f31467021fb2455b52bc31"
        }
      ]
    }
  ]
}
