package ai.factoredui.engine.factors

import kotlin.math.abs
import kotlin.test.Test
import kotlin.test.assertEquals
import kotlin.test.assertTrue

/**
 * Parity tests for the k-means port. Reference labels/centroids/iterations were
 * generated by running the verbatim TS `kMeans` (clustering.ts). If the
 * Mulberry32 port drifts by a single bit, the init centroid changes and these
 * fail. Running in commonTest means parity is checked on every KMP target.
 */
class KMeansTest {

    private val sample = listOf(
        listOf(1.0, 1.0),
        listOf(1.5, 2.0),
        listOf(3.0, 4.0),
        listOf(5.0, 7.0),
        listOf(3.5, 5.0),
        listOf(4.5, 5.0),
        listOf(3.5, 4.5),
    )

    @Test
    fun matchesTsReferenceForK2Seed42() {
        val result = kMeans(sample, k = 2, seed = 42)
        assertEquals(listOf(1, 1, 0, 0, 0, 0, 0), result.labels)
        assertEquals(2, result.iterations)
        assertCentroidsEqual(listOf(listOf(3.9, 5.1), listOf(1.25, 1.5)), result.centroids)
    }

    @Test
    fun matchesTsReferenceForK1Seed1() {
        val result = kMeans(listOf(listOf(1.0, 1.0), listOf(2.0, 2.0), listOf(3.0, 3.0)), k = 1, seed = 1)
        assertEquals(listOf(0, 0, 0), result.labels)
        assertEquals(1, result.iterations)
        assertCentroidsEqual(listOf(listOf(2.0, 2.0)), result.centroids)
    }

    @Test
    fun sameSeedProducesIdenticalResult() {
        val first = kMeans(sample, k = 2, seed = 42)
        val second = kMeans(sample, k = 2, seed = 42)
        assertEquals(first, second)
    }

    private fun assertCentroidsEqual(expected: List<List<Double>>, actual: List<List<Double>>) {
        assertEquals(expected.size, actual.size, "centroid count")
        for (c in expected.indices) {
            assertEquals(expected[c].size, actual[c].size, "centroid $c dimensions")
            for (d in expected[c].indices) {
                assertTrue(
                    abs(expected[c][d] - actual[c][d]) < 1e-9,
                    "centroid[$c][$d]: expected ${expected[c][d]}, got ${actual[c][d]}",
                )
            }
        }
    }
}
