{
  "formatVersion": "1.1",
  "component": {
    "group": "ai.factoredui",
    "module": "kotlin-compose-schema",
    "version": "0.9.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14"
    }
  },
  "variants": [
    {
      "name": "metadataApiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.21"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.11.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-datetime",
          "version": {
            "requires": "0.7.1"
          }
        }
      ],
      "files": [
        {
          "name": "kotlin-compose-schema-metadata-0.9.0.jar",
          "url": "kotlin-compose-schema-0.9.0.jar",
          "size": 10760,
          "sha512": "795121c507cabefdea46efe3258dd771da0aa0c2bd3530b7db8b92e2c3a0f6a79ac9dc4c4df4719e186e96fbc42bb716ea33f04d80c79b57ac59d7532af462ad",
          "sha256": "da36623e358c9c3a7607e0e29a415a1d41f0db226c02bbe1e3783220d6eabba4",
          "sha1": "b7dd8321951dcb49f42f8a238db5ee5982df3b60",
          "md5": "a78a4da21431f5fa3fc6b91e50ad45f1"
        }
      ]
    },
    {
      "name": "metadataSourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "files": [
        {
          "name": "kotlin-compose-schema-kotlin-0.9.0-sources.jar",
          "url": "kotlin-compose-schema-0.9.0-sources.jar",
          "size": 9238,
          "sha512": "4affb9330a226168437bcad22a19f8f492f87332b9c51c96580c010ee95755cf8883c32b4ce9371c7e3c9c54c909a2e2a17dece57bd3fe38fb1c6e7adcfe5637",
          "sha256": "e78bf3fee0afef260d2b7b9d2508411a3f75322d03950f74b61a4c43921cf425",
          "sha1": "cf4b1509d3d93b4bfbb46c0419551f4cbc1df5ad",
          "md5": "185746942c49e1f311e19e8f75d18e3e"
        }
      ]
    },
    {
      "name": "releaseApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "available-at": {
        "url": "../../kotlin-compose-schema-android/0.9.0/kotlin-compose-schema-android-0.9.0.module",
        "group": "ai.factoredui",
        "module": "kotlin-compose-schema-android",
        "version": "0.9.0"
      }
    },
    {
      "name": "releaseRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "available-at": {
        "url": "../../kotlin-compose-schema-android/0.9.0/kotlin-compose-schema-android-0.9.0.module",
        "group": "ai.factoredui",
        "module": "kotlin-compose-schema-android",
        "version": "0.9.0"
      }
    },
    {
      "name": "releaseSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "android",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "available-at": {
        "url": "../../kotlin-compose-schema-android/0.9.0/kotlin-compose-schema-android-0.9.0.module",
        "group": "ai.factoredui",
        "module": "kotlin-compose-schema-android",
        "version": "0.9.0"
      }
    },
    {
      "name": "iosArm64ApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kotlin-compose-schema-iosarm64/0.9.0/kotlin-compose-schema-iosarm64-0.9.0.module",
        "group": "ai.factoredui",
        "module": "kotlin-compose-schema-iosarm64",
        "version": "0.9.0"
      }
    },
    {
      "name": "iosArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kotlin-compose-schema-iosarm64/0.9.0/kotlin-compose-schema-iosarm64-0.9.0.module",
        "group": "ai.factoredui",
        "module": "kotlin-compose-schema-iosarm64",
        "version": "0.9.0"
      }
    },
    {
      "name": "iosArm64MetadataElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kotlin-compose-schema-iosarm64/0.9.0/kotlin-compose-schema-iosarm64-0.9.0.module",
        "group": "ai.factoredui",
        "module": "kotlin-compose-schema-iosarm64",
        "version": "0.9.0"
      }
    },
    {
      "name": "iosSimulatorArm64ApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kotlin-compose-schema-iossimulatorarm64/0.9.0/kotlin-compose-schema-iossimulatorarm64-0.9.0.module",
        "group": "ai.factoredui",
        "module": "kotlin-compose-schema-iossimulatorarm64",
        "version": "0.9.0"
      }
    },
    {
      "name": "iosSimulatorArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kotlin-compose-schema-iossimulatorarm64/0.9.0/kotlin-compose-schema-iossimulatorarm64-0.9.0.module",
        "group": "ai.factoredui",
        "module": "kotlin-compose-schema-iossimulatorarm64",
        "version": "0.9.0"
      }
    },
    {
      "name": "iosSimulatorArm64MetadataElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kotlin-compose-schema-iossimulatorarm64/0.9.0/kotlin-compose-schema-iossimulatorarm64-0.9.0.module",
        "group": "ai.factoredui",
        "module": "kotlin-compose-schema-iossimulatorarm64",
        "version": "0.9.0"
      }
    },
    {
      "name": "iosX64ApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kotlin-compose-schema-iosx64/0.9.0/kotlin-compose-schema-iosx64-0.9.0.module",
        "group": "ai.factoredui",
        "module": "kotlin-compose-schema-iosx64",
        "version": "0.9.0"
      }
    },
    {
      "name": "iosX64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kotlin-compose-schema-iosx64/0.9.0/kotlin-compose-schema-iosx64-0.9.0.module",
        "group": "ai.factoredui",
        "module": "kotlin-compose-schema-iosx64",
        "version": "0.9.0"
      }
    },
    {
      "name": "iosX64MetadataElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kotlin-compose-schema-iosx64/0.9.0/kotlin-compose-schema-iosx64-0.9.0.module",
        "group": "ai.factoredui",
        "module": "kotlin-compose-schema-iosx64",
        "version": "0.9.0"
      }
    },
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../kotlin-compose-schema-jvm/0.9.0/kotlin-compose-schema-jvm-0.9.0.module",
        "group": "ai.factoredui",
        "module": "kotlin-compose-schema-jvm",
        "version": "0.9.0"
      }
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../kotlin-compose-schema-jvm/0.9.0/kotlin-compose-schema-jvm-0.9.0.module",
        "group": "ai.factoredui",
        "module": "kotlin-compose-schema-jvm",
        "version": "0.9.0"
      }
    },
    {
      "name": "jvmSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../kotlin-compose-schema-jvm/0.9.0/kotlin-compose-schema-jvm-0.9.0.module",
        "group": "ai.factoredui",
        "module": "kotlin-compose-schema-jvm",
        "version": "0.9.0"
      }
    },
    {
      "name": "linuxX64ApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "linux_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kotlin-compose-schema-linuxx64/0.9.0/kotlin-compose-schema-linuxx64-0.9.0.module",
        "group": "ai.factoredui",
        "module": "kotlin-compose-schema-linuxx64",
        "version": "0.9.0"
      }
    },
    {
      "name": "linuxX64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "linux_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kotlin-compose-schema-linuxx64/0.9.0/kotlin-compose-schema-linuxx64-0.9.0.module",
        "group": "ai.factoredui",
        "module": "kotlin-compose-schema-linuxx64",
        "version": "0.9.0"
      }
    },
    {
      "name": "wasmJsApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "wasm",
        "org.jetbrains.kotlin.wasm.target": "js"
      },
      "available-at": {
        "url": "../../kotlin-compose-schema-wasm-js/0.9.0/kotlin-compose-schema-wasm-js-0.9.0.module",
        "group": "ai.factoredui",
        "module": "kotlin-compose-schema-wasm-js",
        "version": "0.9.0"
      }
    },
    {
      "name": "wasmJsRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.platform.type": "wasm",
        "org.jetbrains.kotlin.wasm.target": "js"
      },
      "available-at": {
        "url": "../../kotlin-compose-schema-wasm-js/0.9.0/kotlin-compose-schema-wasm-js-0.9.0.module",
        "group": "ai.factoredui",
        "module": "kotlin-compose-schema-wasm-js",
        "version": "0.9.0"
      }
    },
    {
      "name": "wasmJsSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.platform.type": "wasm",
        "org.jetbrains.kotlin.wasm.target": "js"
      },
      "available-at": {
        "url": "../../kotlin-compose-schema-wasm-js/0.9.0/kotlin-compose-schema-wasm-js-0.9.0.module",
        "group": "ai.factoredui",
        "module": "kotlin-compose-schema-wasm-js",
        "version": "0.9.0"
      }
    }
  ]
}
