{
  "formatVersion": "1.1",
  "component": {
    "url": "../../kotlin-compose/0.5.0/kotlin-compose-0.5.0.module",
    "group": "ai.factoredui",
    "module": "kotlin-compose",
    "version": "0.5.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.10.2"
    }
  },
  "variants": [
    {
      "name": "wasmJsApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "wasm",
        "org.jetbrains.kotlin.wasm.target": "js"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.21"
          }
        }
      ],
      "files": [
        {
          "name": "kotlin-compose-wasm-js-0.5.0.klib",
          "url": "kotlin-compose-wasm-js-0.5.0.klib",
          "size": 328011,
          "sha512": "2e69531feef8aab3486dc0d7fe99d9a3ab1171178b30776d8eb8deb33410bc2b72588226bc61c8128017ba2a1cd8ce97774868c1f2ae90dc11c4f0744ecf4633",
          "sha256": "07d7edcc118d7916eecc22caf6ea4460ce6b08df088787dadb9147c0edd3daba",
          "sha1": "5892383d39f403c0206297fddd223e2d32469125",
          "md5": "93c22f715664fbf7a4ec3ea3a5e81d7c"
        }
      ]
    },
    {
      "name": "wasmJsRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.platform.type": "wasm",
        "org.jetbrains.kotlin.wasm.target": "js"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.21"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-js",
          "version": {
            "requires": "3.0.3"
          }
        },
        {
          "group": "org.jetbrains.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "1.7.3"
          }
        },
        {
          "group": "org.jetbrains.compose.foundation",
          "module": "foundation",
          "version": {
            "requires": "1.7.3"
          }
        },
        {
          "group": "org.jetbrains.compose.material3",
          "module": "material3",
          "version": {
            "requires": "1.7.3"
          }
        },
        {
          "group": "org.jetbrains.compose.ui",
          "module": "ui",
          "version": {
            "requires": "1.7.3"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.7.3"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-datetime",
          "version": {
            "requires": "0.6.1"
          }
        },
        {
          "group": "io.coil-kt.coil3",
          "module": "coil-compose",
          "version": {
            "requires": "3.0.4"
          }
        },
        {
          "group": "io.coil-kt.coil3",
          "module": "coil-network-ktor3",
          "version": {
            "requires": "3.0.4"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-core",
          "version": {
            "requires": "3.0.3"
          }
        }
      ],
      "files": [
        {
          "name": "kotlin-compose-wasm-js-0.5.0.klib",
          "url": "kotlin-compose-wasm-js-0.5.0.klib",
          "size": 328011,
          "sha512": "2e69531feef8aab3486dc0d7fe99d9a3ab1171178b30776d8eb8deb33410bc2b72588226bc61c8128017ba2a1cd8ce97774868c1f2ae90dc11c4f0744ecf4633",
          "sha256": "07d7edcc118d7916eecc22caf6ea4460ce6b08df088787dadb9147c0edd3daba",
          "sha1": "5892383d39f403c0206297fddd223e2d32469125",
          "md5": "93c22f715664fbf7a4ec3ea3a5e81d7c"
        }
      ]
    },
    {
      "name": "wasmJsSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.platform.type": "wasm",
        "org.jetbrains.kotlin.wasm.target": "js"
      },
      "files": [
        {
          "name": "kotlin-compose-wasm-js-0.5.0-sources.jar",
          "url": "kotlin-compose-wasm-js-0.5.0-sources.jar",
          "size": 48145,
          "sha512": "dad8b4cbf59b5648c52c3a02a96178b345ad6501f4606130864de32622ab0e908574a1f4d1991de96260a9913a9cffa0c69429b6fd30e79ffd30755bedfdf57d",
          "sha256": "0d1d4aa1e0b7363ddece1a9ead06282afe8afbfe02989f250cd06d3d55d2825a",
          "sha1": "1b3023cae1f756506c0c5691b9e1f9646eeefe84",
          "md5": "df9f414ef61a7892440458c6502cd607"
        }
      ]
    },
    {
      "name": "wasmJsResourcesElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.libraryelements": "kotlin-multiplatformresourcesjs",
        "org.gradle.usage": "kotlin-multiplatformresourcesjs",
        "org.jetbrains.kotlin.platform.type": "wasm",
        "org.jetbrains.kotlin.wasm.target": "js"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.21"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-js",
          "version": {
            "requires": "3.0.3"
          }
        },
        {
          "group": "org.jetbrains.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "1.7.3"
          }
        },
        {
          "group": "org.jetbrains.compose.foundation",
          "module": "foundation",
          "version": {
            "requires": "1.7.3"
          }
        },
        {
          "group": "org.jetbrains.compose.material3",
          "module": "material3",
          "version": {
            "requires": "1.7.3"
          }
        },
        {
          "group": "org.jetbrains.compose.ui",
          "module": "ui",
          "version": {
            "requires": "1.7.3"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.7.3"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-datetime",
          "version": {
            "requires": "0.6.1"
          }
        },
        {
          "group": "io.coil-kt.coil3",
          "module": "coil-compose",
          "version": {
            "requires": "3.0.4"
          }
        },
        {
          "group": "io.coil-kt.coil3",
          "module": "coil-network-ktor3",
          "version": {
            "requires": "3.0.4"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-core",
          "version": {
            "requires": "3.0.3"
          }
        }
      ],
      "files": [
        {
          "name": "kotlin-compose-0.5.0.kotlin_resources.zip",
          "url": "kotlin-compose-wasm-js-0.5.0-kotlin_resources.kotlin_resources.zip",
          "size": 344,
          "sha512": "582a49a0cda0b0cd1bf914ebec401bd3922f1e0a60443c74c13c5e5aac672a178a2d272aaf2596345693947543ae1e16239e09ba9d8b1451d848a34ce69a70fe",
          "sha256": "0a0dfa6ddb70d23637c0998e704d669245273a2dc3aad2ab8e934f5783f109eb",
          "sha1": "d2ecd43e58875eb2ea1ee9877b43238d7ad83fb7",
          "md5": "1649a0e28218c43aca1d458364a19a96"
        }
      ]
    }
  ]
}
