{
  "formatVersion": "1.1",
  "component": {
    "url": "../../kotlin-compose/0.4.0/kotlin-compose-0.4.0.module",
    "group": "ai.factoredui",
    "module": "kotlin-compose",
    "version": "0.4.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.10.2"
    }
  },
  "variants": [
    {
      "name": "desktopApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.21"
          }
        }
      ],
      "files": [
        {
          "name": "kotlin-compose-desktop-0.4.0.jar",
          "url": "kotlin-compose-desktop-0.4.0.jar",
          "size": 368275,
          "sha512": "0add6b0dc0e22c5fe1c91fad18058fd11a28ea8e77be94e475979688b5d106da5531afe3a8d6b8865660800f1b831a0fc66b5a39f01920f76a68e8325ca3bb15",
          "sha256": "46a0da5528f848622303e91f7f8f81782cd34d248aa480a3973b4950eb47fb3b",
          "sha1": "e030bc16a4347fdfa4e3e667dc5383ca2f2404fa",
          "md5": "1f96ade8550f47a81d2697135a36af6a"
        }
      ]
    },
    {
      "name": "desktopRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.21"
          }
        },
        {
          "group": "org.jetbrains.compose.desktop",
          "module": "desktop-jvm-linux-x64",
          "version": {
            "requires": "1.7.3"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-okhttp",
          "version": {
            "requires": "3.0.3"
          }
        },
        {
          "group": "org.jetbrains.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "1.7.3"
          }
        },
        {
          "group": "org.jetbrains.compose.foundation",
          "module": "foundation",
          "version": {
            "requires": "1.7.3"
          }
        },
        {
          "group": "org.jetbrains.compose.material3",
          "module": "material3",
          "version": {
            "requires": "1.7.3"
          }
        },
        {
          "group": "org.jetbrains.compose.ui",
          "module": "ui",
          "version": {
            "requires": "1.7.3"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.7.3"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-datetime",
          "version": {
            "requires": "0.6.1"
          }
        },
        {
          "group": "io.coil-kt.coil3",
          "module": "coil-compose",
          "version": {
            "requires": "3.0.4"
          }
        },
        {
          "group": "io.coil-kt.coil3",
          "module": "coil-network-ktor3",
          "version": {
            "requires": "3.0.4"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-core",
          "version": {
            "requires": "3.0.3"
          }
        }
      ],
      "files": [
        {
          "name": "kotlin-compose-desktop-0.4.0.jar",
          "url": "kotlin-compose-desktop-0.4.0.jar",
          "size": 368275,
          "sha512": "0add6b0dc0e22c5fe1c91fad18058fd11a28ea8e77be94e475979688b5d106da5531afe3a8d6b8865660800f1b831a0fc66b5a39f01920f76a68e8325ca3bb15",
          "sha256": "46a0da5528f848622303e91f7f8f81782cd34d248aa480a3973b4950eb47fb3b",
          "sha1": "e030bc16a4347fdfa4e3e667dc5383ca2f2404fa",
          "md5": "1f96ade8550f47a81d2697135a36af6a"
        }
      ]
    },
    {
      "name": "desktopSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "kotlin-compose-desktop-0.4.0-sources.jar",
          "url": "kotlin-compose-desktop-0.4.0-sources.jar",
          "size": 38680,
          "sha512": "7c4d84c711a730ef0ba6944e44e823b52e1400c8e60aeb7943ed5a076167e5224ab5f7cb0fa07b83859d440becbdcdd7bb5bfffa7462e9b2d60a88e8d610f19d",
          "sha256": "a38b37ca879f61262549844e58d960495091480a23c2b12caaa175f59dc3e143",
          "sha1": "d08de8aeac6cd0e2bd71d31430cd160491f2ef7b",
          "md5": "2cd0942cf3083e501d1286e029a7ef72"
        }
      ]
    }
  ]
}
