{
  "formatVersion": "1.1",
  "component": {
    "url": "../../kotlin-compose/0.20.6/kotlin-compose-0.20.6.module",
    "group": "ai.factoredui",
    "module": "kotlin-compose",
    "version": "0.20.6",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14"
    }
  },
  "variants": [
    {
      "name": "releaseApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "ai.factoredui",
          "module": "kotlin-compose-schema",
          "version": {
            "requires": "0.20.6"
          }
        },
        {
          "group": "ai.factoredui",
          "module": "kotlin-compose-capture",
          "version": {
            "requires": "0.20.6"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.21"
          }
        }
      ],
      "files": [
        {
          "name": "kotlin-compose-release.aar",
          "url": "kotlin-compose-android-0.20.6.aar",
          "size": 715189,
          "sha512": "ad4927831d69e01d6a9bf950cea918633fc0bdbfaf226973eed9b1da47b098a103488990187159ea3fd703febb48095896b49ca53fab82a4f9bc120ab2c62919",
          "sha256": "616d394dc8ce8593ba4553a8a67f9976e7f9f89895c72b03606b0f7ed95c3fe9",
          "sha1": "989b87b6d47e3ca7fef2a4dc63b20921ef051e9b",
          "md5": "52d79f00e3c1dc300ea1dcfddd7eb114"
        }
      ]
    },
    {
      "name": "releaseRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "androidx.activity",
          "module": "activity-compose",
          "version": {
            "requires": "1.9.3"
          },
          "excludes": [
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-annotations-common"
            }
          ]
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-okhttp",
          "version": {
            "requires": "3.2.4"
          },
          "excludes": [
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-annotations-common"
            }
          ]
        },
        {
          "group": "ai.factoredui",
          "module": "kotlin-compose-schema",
          "version": {
            "requires": "0.20.6"
          },
          "excludes": [
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-annotations-common"
            }
          ]
        },
        {
          "group": "ai.factoredui",
          "module": "kotlin-compose-capture",
          "version": {
            "requires": "0.20.6"
          },
          "excludes": [
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-annotations-common"
            }
          ]
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.21"
          },
          "excludes": [
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-annotations-common"
            }
          ]
        },
        {
          "group": "org.jetbrains.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "1.10.3"
          },
          "excludes": [
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-annotations-common"
            }
          ]
        },
        {
          "group": "org.jetbrains.compose.foundation",
          "module": "foundation",
          "version": {
            "requires": "1.10.3"
          },
          "excludes": [
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-annotations-common"
            }
          ]
        },
        {
          "group": "org.jetbrains.compose.material3",
          "module": "material3",
          "version": {
            "requires": "1.9.0-beta03"
          },
          "excludes": [
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-annotations-common"
            }
          ]
        },
        {
          "group": "org.jetbrains.compose.ui",
          "module": "ui",
          "version": {
            "requires": "1.10.3"
          },
          "excludes": [
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-annotations-common"
            }
          ]
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.11.0"
          },
          "excludes": [
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-annotations-common"
            }
          ]
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.10.2"
          },
          "excludes": [
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-annotations-common"
            }
          ]
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-datetime",
          "version": {
            "requires": "0.7.1"
          },
          "excludes": [
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-annotations-common"
            }
          ]
        },
        {
          "group": "io.coil-kt.coil3",
          "module": "coil-compose",
          "version": {
            "requires": "3.2.0"
          },
          "excludes": [
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-annotations-common"
            }
          ]
        },
        {
          "group": "io.coil-kt.coil3",
          "module": "coil-network-ktor3",
          "version": {
            "requires": "3.2.0"
          },
          "excludes": [
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-annotations-common"
            }
          ]
        },
        {
          "group": "io.coil-kt.coil3",
          "module": "coil-svg",
          "version": {
            "requires": "3.2.0"
          },
          "excludes": [
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-annotations-common"
            }
          ]
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-core",
          "version": {
            "requires": "3.2.4"
          },
          "excludes": [
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-annotations-common"
            }
          ]
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-content-negotiation",
          "version": {
            "requires": "3.2.4"
          },
          "excludes": [
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-annotations-common"
            }
          ]
        },
        {
          "group": "io.ktor",
          "module": "ktor-serialization-kotlinx-json",
          "version": {
            "requires": "3.2.4"
          },
          "excludes": [
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-annotations-common"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "kotlin-compose-release.aar",
          "url": "kotlin-compose-android-0.20.6.aar",
          "size": 715189,
          "sha512": "ad4927831d69e01d6a9bf950cea918633fc0bdbfaf226973eed9b1da47b098a103488990187159ea3fd703febb48095896b49ca53fab82a4f9bc120ab2c62919",
          "sha256": "616d394dc8ce8593ba4553a8a67f9976e7f9f89895c72b03606b0f7ed95c3fe9",
          "sha1": "989b87b6d47e3ca7fef2a4dc63b20921ef051e9b",
          "md5": "52d79f00e3c1dc300ea1dcfddd7eb114"
        }
      ]
    },
    {
      "name": "releaseSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "android",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "files": [
        {
          "name": "kotlin-compose-android-0.20.6-sources.jar",
          "url": "kotlin-compose-android-0.20.6-sources.jar",
          "size": 92353,
          "sha512": "e2dedf7bbf189d7f35aeb10a8a05fb40be08880c1dfe950a8aa94e6f7c6a2317b7e8f61e4582402ed59f5d71db9a3e590f14f548298ec3c192fd96cf249cd641",
          "sha256": "77784d63b73cb1edf665c4f5ea38d135ec209951b5d4322c6461e1d8ebaf31b5",
          "sha1": "f9483c4bf7e190b8cc4c6b05effe74145132ae51",
          "md5": "09f6c1216010e331b43bbccf6701b9f5"
        }
      ]
    }
  ]
}
