{
  "formatVersion": "1.1",
  "component": {
    "url": "../../kotlin-compose/0.4.0/kotlin-compose-0.4.0.module",
    "group": "ai.factoredui",
    "module": "kotlin-compose",
    "version": "0.4.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.10.2"
    }
  },
  "variants": [
    {
      "name": "wasmJsApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "wasm",
        "org.jetbrains.kotlin.wasm.target": "js"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.21"
          }
        }
      ],
      "files": [
        {
          "name": "kotlin-compose-wasm-js-0.4.0.klib",
          "url": "kotlin-compose-wasm-js-0.4.0.klib",
          "size": 296048,
          "sha512": "f6118c463a900dcfec213e4230e9233e5271c72c5112a397be17c6664de0e1da0f32a0aab742ec61054e93b3e36a084d7383b59c4b26275d08fdf7556782c310",
          "sha256": "eb6308514828b5bf9792af05dae988a1240fa32538367077425cf430a92042e4",
          "sha1": "39533fcc73e2ca9b946a8a937fef5a650a78d35d",
          "md5": "23f23386d7170f548ec83582259d2606"
        }
      ]
    },
    {
      "name": "wasmJsRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.platform.type": "wasm",
        "org.jetbrains.kotlin.wasm.target": "js"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.21"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-js",
          "version": {
            "requires": "3.0.3"
          }
        },
        {
          "group": "org.jetbrains.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "1.7.3"
          }
        },
        {
          "group": "org.jetbrains.compose.foundation",
          "module": "foundation",
          "version": {
            "requires": "1.7.3"
          }
        },
        {
          "group": "org.jetbrains.compose.material3",
          "module": "material3",
          "version": {
            "requires": "1.7.3"
          }
        },
        {
          "group": "org.jetbrains.compose.ui",
          "module": "ui",
          "version": {
            "requires": "1.7.3"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.7.3"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-datetime",
          "version": {
            "requires": "0.6.1"
          }
        },
        {
          "group": "io.coil-kt.coil3",
          "module": "coil-compose",
          "version": {
            "requires": "3.0.4"
          }
        },
        {
          "group": "io.coil-kt.coil3",
          "module": "coil-network-ktor3",
          "version": {
            "requires": "3.0.4"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-core",
          "version": {
            "requires": "3.0.3"
          }
        }
      ],
      "files": [
        {
          "name": "kotlin-compose-wasm-js-0.4.0.klib",
          "url": "kotlin-compose-wasm-js-0.4.0.klib",
          "size": 296048,
          "sha512": "f6118c463a900dcfec213e4230e9233e5271c72c5112a397be17c6664de0e1da0f32a0aab742ec61054e93b3e36a084d7383b59c4b26275d08fdf7556782c310",
          "sha256": "eb6308514828b5bf9792af05dae988a1240fa32538367077425cf430a92042e4",
          "sha1": "39533fcc73e2ca9b946a8a937fef5a650a78d35d",
          "md5": "23f23386d7170f548ec83582259d2606"
        }
      ]
    },
    {
      "name": "wasmJsSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.platform.type": "wasm",
        "org.jetbrains.kotlin.wasm.target": "js"
      },
      "files": [
        {
          "name": "kotlin-compose-wasm-js-0.4.0-sources.jar",
          "url": "kotlin-compose-wasm-js-0.4.0-sources.jar",
          "size": 38680,
          "sha512": "7c4d84c711a730ef0ba6944e44e823b52e1400c8e60aeb7943ed5a076167e5224ab5f7cb0fa07b83859d440becbdcdd7bb5bfffa7462e9b2d60a88e8d610f19d",
          "sha256": "a38b37ca879f61262549844e58d960495091480a23c2b12caaa175f59dc3e143",
          "sha1": "d08de8aeac6cd0e2bd71d31430cd160491f2ef7b",
          "md5": "2cd0942cf3083e501d1286e029a7ef72"
        }
      ]
    },
    {
      "name": "wasmJsResourcesElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.libraryelements": "kotlin-multiplatformresourcesjs",
        "org.gradle.usage": "kotlin-multiplatformresourcesjs",
        "org.jetbrains.kotlin.platform.type": "wasm",
        "org.jetbrains.kotlin.wasm.target": "js"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.21"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-js",
          "version": {
            "requires": "3.0.3"
          }
        },
        {
          "group": "org.jetbrains.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "1.7.3"
          }
        },
        {
          "group": "org.jetbrains.compose.foundation",
          "module": "foundation",
          "version": {
            "requires": "1.7.3"
          }
        },
        {
          "group": "org.jetbrains.compose.material3",
          "module": "material3",
          "version": {
            "requires": "1.7.3"
          }
        },
        {
          "group": "org.jetbrains.compose.ui",
          "module": "ui",
          "version": {
            "requires": "1.7.3"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.7.3"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-datetime",
          "version": {
            "requires": "0.6.1"
          }
        },
        {
          "group": "io.coil-kt.coil3",
          "module": "coil-compose",
          "version": {
            "requires": "3.0.4"
          }
        },
        {
          "group": "io.coil-kt.coil3",
          "module": "coil-network-ktor3",
          "version": {
            "requires": "3.0.4"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-core",
          "version": {
            "requires": "3.0.3"
          }
        }
      ],
      "files": [
        {
          "name": "kotlin-compose-0.4.0.kotlin_resources.zip",
          "url": "kotlin-compose-wasm-js-0.4.0-kotlin_resources.kotlin_resources.zip",
          "size": 344,
          "sha512": "739746c5b8af7fcdd18a73772c5d0a4373ac4f18032b38779cd91b6e1013119b8df5d69bf8352dfd6dbc4cb92089bf834a6f83ee0173f3b3104dd0454923ccb2",
          "sha256": "43847815c2c08dd8bf0ad4a6efe926f47d29ea939055f94c3ba004d5cb878852",
          "sha1": "4674de23ed05bc3092b09da5f2d5c5fc0864f72d",
          "md5": "b8baae29b0d765da7b7dafdef2752120"
        }
      ]
    }
  ]
}
