{
  "formatVersion": "1.1",
  "component": {
    "url": "../../kotlin-compose-capture/0.17.1/kotlin-compose-capture-0.17.1.module",
    "group": "ai.factoredui",
    "module": "kotlin-compose-capture",
    "version": "0.17.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14"
    }
  },
  "variants": [
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.21"
          }
        }
      ],
      "files": [
        {
          "name": "kotlin-compose-capture-jvm-0.17.1.jar",
          "url": "kotlin-compose-capture-jvm-0.17.1.jar",
          "size": 22498,
          "sha512": "d5614ab3618436ee788d1dbe55f67367ae48aa65ddb29a4ea1910b57e711ae90ca74d53eca15193cf173699087b9cd079c21764caf96c45cbc4bbf989a8eea2b",
          "sha256": "925d82f51303137a45539ab87e43921c8bee3f7cb9a8e7eac800893d2c6fe054",
          "sha1": "657a9df151c33453d5c9019fc412ef2df066bf03",
          "md5": "f61a8cc9219e3b488775bba453bfb26d"
        }
      ]
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.21"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.11.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-datetime",
          "version": {
            "requires": "0.7.1"
          }
        }
      ],
      "files": [
        {
          "name": "kotlin-compose-capture-jvm-0.17.1.jar",
          "url": "kotlin-compose-capture-jvm-0.17.1.jar",
          "size": 22498,
          "sha512": "d5614ab3618436ee788d1dbe55f67367ae48aa65ddb29a4ea1910b57e711ae90ca74d53eca15193cf173699087b9cd079c21764caf96c45cbc4bbf989a8eea2b",
          "sha256": "925d82f51303137a45539ab87e43921c8bee3f7cb9a8e7eac800893d2c6fe054",
          "sha1": "657a9df151c33453d5c9019fc412ef2df066bf03",
          "md5": "f61a8cc9219e3b488775bba453bfb26d"
        }
      ]
    },
    {
      "name": "jvmSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "kotlin-compose-capture-jvm-0.17.1-sources.jar",
          "url": "kotlin-compose-capture-jvm-0.17.1-sources.jar",
          "size": 2675,
          "sha512": "2f30e91c5b3bb7af31334533cd53498c1f205f723d4956b8bd8d8d2c9480058b2ae47a8fdca96e615561199fa50a6a22b561bc5220848629ef7fe47dd537c6ef",
          "sha256": "c82f37fc21d50fc8ecc030b86b4137334808ac44ee33a7e7732c739eb29d0700",
          "sha1": "84a2b3c08bc728e17e68a868cfa57eada683f007",
          "md5": "1ce993c162e5d1582ebec69fad7b8a80"
        }
      ]
    }
  ]
}
