{
  "formatVersion": "1.1",
  "component": {
    "url": "../../kotlin-compose-schema/0.20.2/kotlin-compose-schema-0.20.2.module",
    "group": "ai.factoredui",
    "module": "kotlin-compose-schema",
    "version": "0.20.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14"
    }
  },
  "variants": [
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.21"
          }
        }
      ],
      "files": [
        {
          "name": "kotlin-compose-schema-jvm-0.20.2.jar",
          "url": "kotlin-compose-schema-jvm-0.20.2.jar",
          "size": 171734,
          "sha512": "2903ffa561cb8bc6af1d96802a30bf4a6f074adee84d012d9231466548c53ae31b03d2220688f6c9d5cc8ff8c638828885a4b1516f0c1f7fc73d918e3de44c16",
          "sha256": "eb8203f66928b92eb2cf712e7c4798a6f40fa1d771d4f4e6826083462650bf41",
          "sha1": "e80037b330dd1fdf63e435867ed33f0ad40b972c",
          "md5": "fd4802eafd8e467107598e5b6fbd5ca1"
        }
      ]
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.21"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.11.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-datetime",
          "version": {
            "requires": "0.7.1"
          }
        }
      ],
      "files": [
        {
          "name": "kotlin-compose-schema-jvm-0.20.2.jar",
          "url": "kotlin-compose-schema-jvm-0.20.2.jar",
          "size": 171734,
          "sha512": "2903ffa561cb8bc6af1d96802a30bf4a6f074adee84d012d9231466548c53ae31b03d2220688f6c9d5cc8ff8c638828885a4b1516f0c1f7fc73d918e3de44c16",
          "sha256": "eb8203f66928b92eb2cf712e7c4798a6f40fa1d771d4f4e6826083462650bf41",
          "sha1": "e80037b330dd1fdf63e435867ed33f0ad40b972c",
          "md5": "fd4802eafd8e467107598e5b6fbd5ca1"
        }
      ]
    },
    {
      "name": "jvmSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "kotlin-compose-schema-jvm-0.20.2-sources.jar",
          "url": "kotlin-compose-schema-jvm-0.20.2-sources.jar",
          "size": 12227,
          "sha512": "5db475c4b75a6cc059c089fcf69d18564941622e5a810c8f3fdde229351edc07975303b83f2edfd9da46d15a48aea3d9f271f9afbe21b858914f06fe34feffe7",
          "sha256": "d4edad5c0c1cbc5e0fb2f061b7c94c482e244a006cab0f66be88b71caa346434",
          "sha1": "7df2897c68f265f63bc65f877a394cb724681794",
          "md5": "2f93944aaafde82ab59bffdf39087647"
        }
      ]
    }
  ]
}
