{
  "formatVersion": "1.1",
  "component": {
    "url": "../../kotlin-compose-capture/0.18.0/kotlin-compose-capture-0.18.0.module",
    "group": "ai.factoredui",
    "module": "kotlin-compose-capture",
    "version": "0.18.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14"
    }
  },
  "variants": [
    {
      "name": "iosSimulatorArm64ApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.21"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.11.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-datetime",
          "version": {
            "requires": "0.7.1"
          }
        }
      ],
      "files": [
        {
          "name": "kotlin-compose-capture-iosSimulatorArm64Main-0.18.0.klib",
          "url": "kotlin-compose-capture-iossimulatorarm64-0.18.0.klib",
          "size": 22709,
          "sha512": "5a5436bd67ef1fd250881eeb297365fa79e22d9b2b90b9bbca141e6f2e3ff05093ccbf6dbbb963d20e2666c69c3da3b0c9507e8217264df9a5c7bc9e981e262d",
          "sha256": "7b7db9eaab63c914a428d67db601645f43c21c29c0842844290d92faf5d821df",
          "sha1": "69b54f5e07f2b312f3e3d939d97583b1b1429342",
          "md5": "e2f7fdddfc40a6e52fab52e4c6a1a5f4"
        }
      ]
    },
    {
      "name": "iosSimulatorArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "files": [
        {
          "name": "kotlin-compose-capture-iossimulatorarm64-0.18.0-sources.jar",
          "url": "kotlin-compose-capture-iossimulatorarm64-0.18.0-sources.jar",
          "size": 2675,
          "sha512": "2f30e91c5b3bb7af31334533cd53498c1f205f723d4956b8bd8d8d2c9480058b2ae47a8fdca96e615561199fa50a6a22b561bc5220848629ef7fe47dd537c6ef",
          "sha256": "c82f37fc21d50fc8ecc030b86b4137334808ac44ee33a7e7732c739eb29d0700",
          "sha1": "84a2b3c08bc728e17e68a868cfa57eada683f007",
          "md5": "1ce993c162e5d1582ebec69fad7b8a80"
        }
      ]
    },
    {
      "name": "iosSimulatorArm64MetadataElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.21"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.11.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-datetime",
          "version": {
            "requires": "0.7.1"
          }
        }
      ],
      "files": [
        {
          "name": "kotlin-compose-capture-iossimulatorarm64-0.18.0-metadata.jar",
          "url": "kotlin-compose-capture-iossimulatorarm64-0.18.0-metadata.jar",
          "size": 261,
          "sha512": "5e657cb477ff0634f7bdeb542a6329411dfddb69748a4c68747f4ffc5c528a3358d593e4afa3725e91d25514dcffc85756eb43798531c1c1d5c6fe32ec4aba64",
          "sha256": "7b928470a74ffb0d8c1bc61c717d5224600cfb75139bb63a73628eea62ab58e2",
          "sha1": "1ec065c1418610799163399b3061d3aa861fbd4e",
          "md5": "93f6f6a59a68dc70f536cbc54adb1f10"
        }
      ]
    }
  ]
}
