{
  "formatVersion": "1.1",
  "component": {
    "url": "../../kotlin-compose/0.20.6/kotlin-compose-0.20.6.module",
    "group": "ai.factoredui",
    "module": "kotlin-compose",
    "version": "0.20.6",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14"
    }
  },
  "variants": [
    {
      "name": "desktopApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "ai.factoredui",
          "module": "kotlin-compose-schema",
          "version": {
            "requires": "0.20.6"
          }
        },
        {
          "group": "ai.factoredui",
          "module": "kotlin-compose-capture",
          "version": {
            "requires": "0.20.6"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.21"
          }
        }
      ],
      "files": [
        {
          "name": "kotlin-compose-desktop-0.20.6.jar",
          "url": "kotlin-compose-desktop-0.20.6.jar",
          "size": 926380,
          "sha512": "92ec60f488173862cf7c8e1730f439be4ba54fc400cdc171b268aa188a337db3cf22687eabdb62ee562c360ca4b0a03dab8847b0b23000dc807cc5326d3a632f",
          "sha256": "39d67bae3ed8197f94fc1e960dc5ce9bdd8f537bf673758b068c298f799cc4c3",
          "sha1": "00014bc4fa4daf43716fffe941d17362d64bd2fe",
          "md5": "0254b9293e0567d066c1339a8045313d"
        }
      ]
    },
    {
      "name": "desktopRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "ai.factoredui",
          "module": "kotlin-compose-schema",
          "version": {
            "requires": "0.20.6"
          }
        },
        {
          "group": "ai.factoredui",
          "module": "kotlin-compose-capture",
          "version": {
            "requires": "0.20.6"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.21"
          }
        },
        {
          "group": "org.jetbrains.compose.desktop",
          "module": "desktop",
          "version": {
            "requires": "1.10.3"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-okhttp",
          "version": {
            "requires": "3.2.4"
          }
        },
        {
          "group": "org.jetbrains.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "1.10.3"
          }
        },
        {
          "group": "org.jetbrains.compose.foundation",
          "module": "foundation",
          "version": {
            "requires": "1.10.3"
          }
        },
        {
          "group": "org.jetbrains.compose.material3",
          "module": "material3",
          "version": {
            "requires": "1.9.0-beta03"
          }
        },
        {
          "group": "org.jetbrains.compose.ui",
          "module": "ui",
          "version": {
            "requires": "1.10.3"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.11.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.10.2"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-datetime",
          "version": {
            "requires": "0.7.1"
          }
        },
        {
          "group": "io.coil-kt.coil3",
          "module": "coil-compose",
          "version": {
            "requires": "3.2.0"
          }
        },
        {
          "group": "io.coil-kt.coil3",
          "module": "coil-network-ktor3",
          "version": {
            "requires": "3.2.0"
          }
        },
        {
          "group": "io.coil-kt.coil3",
          "module": "coil-svg",
          "version": {
            "requires": "3.2.0"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-core",
          "version": {
            "requires": "3.2.4"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-content-negotiation",
          "version": {
            "requires": "3.2.4"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-serialization-kotlinx-json",
          "version": {
            "requires": "3.2.4"
          }
        }
      ],
      "files": [
        {
          "name": "kotlin-compose-desktop-0.20.6.jar",
          "url": "kotlin-compose-desktop-0.20.6.jar",
          "size": 926380,
          "sha512": "92ec60f488173862cf7c8e1730f439be4ba54fc400cdc171b268aa188a337db3cf22687eabdb62ee562c360ca4b0a03dab8847b0b23000dc807cc5326d3a632f",
          "sha256": "39d67bae3ed8197f94fc1e960dc5ce9bdd8f537bf673758b068c298f799cc4c3",
          "sha1": "00014bc4fa4daf43716fffe941d17362d64bd2fe",
          "md5": "0254b9293e0567d066c1339a8045313d"
        }
      ]
    },
    {
      "name": "desktopSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "kotlin-compose-desktop-0.20.6-sources.jar",
          "url": "kotlin-compose-desktop-0.20.6-sources.jar",
          "size": 114116,
          "sha512": "d9e91b65879260a655eaaef0a3b92d5c548cc9fd4b9e620e409c7007349ed537fb8de71f6ab5748e1edda4a02ca6e2216e7f6d652832de075ab7d26149dcdde3",
          "sha256": "18193b8dbab61d80a3101c77aa76c2557a1fe532cb69f77e4b13a6b7b76b3b49",
          "sha1": "3c7b3d35945dfeb7b498d593be34d91c6234a624",
          "md5": "2e1383893e9393cb28f3d8226fd9b601"
        }
      ]
    }
  ]
}
