{
  "formatVersion": "1.1",
  "component": {
    "url": "../../kotlin-engine/0.20.0/kotlin-engine-0.20.0.module",
    "group": "ai.factoredui",
    "module": "kotlin-engine",
    "version": "0.20.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14"
    }
  },
  "variants": [
    {
      "name": "iosSimulatorArm64ApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "ai.factoredui",
          "module": "kotlin-compose-schema",
          "version": {
            "requires": "0.20.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.21"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.11.0"
          }
        }
      ],
      "files": [
        {
          "name": "kotlin-engine-iosSimulatorArm64Main-0.20.0.klib",
          "url": "kotlin-engine-iossimulatorarm64-0.20.0.klib",
          "size": 74077,
          "sha512": "bd918982472a5e4a01ed3d6d3f59dc72352f2c30dfd7803bef586f60f225504aff0db5fb4f78696b7cd341f0614471ed99b18f03c18e778320d26f96d1ce0ca6",
          "sha256": "24bd5de32f365c20b349af98b6ddf4798699d0529b40abaf4b9fde7ee3c2d8ef",
          "sha1": "d61a6f2a6fcce6962cee0bae2335f0cac8217eb1",
          "md5": "8cfd04c1371201b3c3c39cfc4f938f8c"
        }
      ]
    },
    {
      "name": "iosSimulatorArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "files": [
        {
          "name": "kotlin-engine-iossimulatorarm64-0.20.0-sources.jar",
          "url": "kotlin-engine-iossimulatorarm64-0.20.0-sources.jar",
          "size": 12466,
          "sha512": "64fd9f6420b2aea8e49b9b1c8e9f74b7b1590d51441509053c81d6938126bbd5376f8e3906583c32e296dd31055ab1b9756ddcfed6a9f30f6e8f968bad154fa1",
          "sha256": "dc8377b57cf44787664168ef1d1e1106cfba6c2299e91d4c1eb488ea0d5db025",
          "sha1": "eb97f38572b70bdbf1fe7cb88c68eac18830fc5a",
          "md5": "326b83071cbbb8de717754774c4007c1"
        }
      ]
    },
    {
      "name": "iosSimulatorArm64MetadataElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "ai.factoredui",
          "module": "kotlin-compose-schema",
          "version": {
            "requires": "0.20.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.21"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.11.0"
          }
        }
      ],
      "files": [
        {
          "name": "kotlin-engine-iossimulatorarm64-0.20.0-metadata.jar",
          "url": "kotlin-engine-iossimulatorarm64-0.20.0-metadata.jar",
          "size": 261,
          "sha512": "2e400ff11272d02158335e536de251d36bc81214b0e0faa7f75f89ce8631490949f8d3addd0486ee3944af4290f3a623ced2614f2d119d106882e69fd504fbb7",
          "sha256": "fb92567e16d5da1ecc2782dd01f94108e78dc1beecfbf38d178dfa9e9bd1a699",
          "sha1": "5d52bf84c62839899ddcbc24e80c2eea8719a12c",
          "md5": "1b5ff3e29c1924e457010a5b77a32e4e"
        }
      ]
    }
  ]
}
