{
  "formatVersion": "1.1",
  "component": {
    "url": "../../kotlin-compose-schema/0.20.6/kotlin-compose-schema-0.20.6.module",
    "group": "ai.factoredui",
    "module": "kotlin-compose-schema",
    "version": "0.20.6",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14"
    }
  },
  "variants": [
    {
      "name": "iosX64ApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.21"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.11.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-datetime",
          "version": {
            "requires": "0.7.1"
          }
        }
      ],
      "files": [
        {
          "name": "kotlin-compose-schema-iosX64Main-0.20.6.klib",
          "url": "kotlin-compose-schema-iosx64-0.20.6.klib",
          "size": 140264,
          "sha512": "52135d88f3a1fb14cca523784db9dda15b350c7756dc9b607026a26f96cae2979e307b9b5481343de8d29b26fdd581d1095940f05aa1b93fa23c6a53ad20511d",
          "sha256": "fb24e72f3913f00390efb43df1cdbda24312a6cb81ffce397c6c32f4fe3121d1",
          "sha1": "e739cef0f2505a46b0c4f7b74e4637b388e3a33d",
          "md5": "94b2a2d7b5943c35041804610202a461"
        }
      ]
    },
    {
      "name": "iosX64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "files": [
        {
          "name": "kotlin-compose-schema-iosx64-0.20.6-sources.jar",
          "url": "kotlin-compose-schema-iosx64-0.20.6-sources.jar",
          "size": 12896,
          "sha512": "1f8eec231bb59f13ab0a1e2aac85f9f8e201081805972512f2f28ea743d54f2d8fc6bfdc9dd88970f7c8d64546cc78401c5c6f316204cbf20b1ea6368a8ef793",
          "sha256": "ca7b1c8612282eeb2c1391b6f3da13cfbcc0c44c72c0e6ca6193c844db9a5fdd",
          "sha1": "3dde30d0160d2f7d0843c764314d54909d01f06d",
          "md5": "d552ea9172056e2e5e0d8bf0aa4f36be"
        }
      ]
    },
    {
      "name": "iosX64MetadataElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.21"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.11.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-datetime",
          "version": {
            "requires": "0.7.1"
          }
        }
      ],
      "files": [
        {
          "name": "kotlin-compose-schema-iosx64-0.20.6-metadata.jar",
          "url": "kotlin-compose-schema-iosx64-0.20.6-metadata.jar",
          "size": 261,
          "sha512": "105e228f9a01f99fc21de96d9aaaf00862484c21ce34ade4cbf1cc4006ad989a6f3777a9e2984a7c141b976973ad3b685ec0f1469ce55b5400a3fadbf2754bf1",
          "sha256": "c0f3f7f94906042a19ec556dd6a723388c39db24c522961aca30e5891100945c",
          "sha1": "f62c672ef811fbaa15dd9090182656ae2f1fe6bf",
          "md5": "781cf80f94c151639a76664a907c5238"
        }
      ]
    }
  ]
}
