{
  "formatVersion": "1.1",
  "component": {
    "url": "../../kotlin-compose/0.2.0/kotlin-compose-0.2.0.module",
    "group": "ai.factoredui",
    "module": "kotlin-compose",
    "version": "0.2.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.10.2"
    }
  },
  "variants": [
    {
      "name": "wasmJsApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "wasm",
        "org.jetbrains.kotlin.wasm.target": "js"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.21"
          }
        }
      ],
      "files": [
        {
          "name": "kotlin-compose-wasm-js-0.2.0.klib",
          "url": "kotlin-compose-wasm-js-0.2.0.klib",
          "size": 143193,
          "sha512": "8fb5012f22bd237e9771407025e99cedabab9bb4bded03c3e13cbd1acc7a21a40979e3ea36066289aac5b04942f6b74107223961b3cde60e9cda5d495c878d44",
          "sha256": "9848d78b9f1a55dfabb51213182e65eda580e960ba68f910f8d6dec26c477362",
          "sha1": "329d40915149a2fa52664d32282a7926005ec799",
          "md5": "7cc99b47421f05e2cc2b85600d4eefd6"
        }
      ]
    },
    {
      "name": "wasmJsRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.platform.type": "wasm",
        "org.jetbrains.kotlin.wasm.target": "js"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.21"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-js",
          "version": {
            "requires": "3.0.3"
          }
        },
        {
          "group": "org.jetbrains.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "1.7.3"
          }
        },
        {
          "group": "org.jetbrains.compose.foundation",
          "module": "foundation",
          "version": {
            "requires": "1.7.3"
          }
        },
        {
          "group": "org.jetbrains.compose.material3",
          "module": "material3",
          "version": {
            "requires": "1.7.3"
          }
        },
        {
          "group": "org.jetbrains.compose.ui",
          "module": "ui",
          "version": {
            "requires": "1.7.3"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.7.3"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "io.coil-kt.coil3",
          "module": "coil-compose",
          "version": {
            "requires": "3.0.4"
          }
        },
        {
          "group": "io.coil-kt.coil3",
          "module": "coil-network-ktor3",
          "version": {
            "requires": "3.0.4"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-core",
          "version": {
            "requires": "3.0.3"
          }
        }
      ],
      "files": [
        {
          "name": "kotlin-compose-wasm-js-0.2.0.klib",
          "url": "kotlin-compose-wasm-js-0.2.0.klib",
          "size": 143193,
          "sha512": "8fb5012f22bd237e9771407025e99cedabab9bb4bded03c3e13cbd1acc7a21a40979e3ea36066289aac5b04942f6b74107223961b3cde60e9cda5d495c878d44",
          "sha256": "9848d78b9f1a55dfabb51213182e65eda580e960ba68f910f8d6dec26c477362",
          "sha1": "329d40915149a2fa52664d32282a7926005ec799",
          "md5": "7cc99b47421f05e2cc2b85600d4eefd6"
        }
      ]
    },
    {
      "name": "wasmJsSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.platform.type": "wasm",
        "org.jetbrains.kotlin.wasm.target": "js"
      },
      "files": [
        {
          "name": "kotlin-compose-wasm-js-0.2.0-sources.jar",
          "url": "kotlin-compose-wasm-js-0.2.0-sources.jar",
          "size": 15932,
          "sha512": "1ed32ccefe14008fdfda7fc7b81953921c7d582bcaa4a96f83331877a5a113b2a0b60bec6d8e5e6ef3e2c46ad1c5a95ebfd445d720f2644eee711aa46654461e",
          "sha256": "4f8582b7f53359a9295eec6e08ff0e0a48ec2c51eb589c3480f81c4a91c6ea65",
          "sha1": "0d7596b86fda0afdfa2ea7a8ccb100bdf4f54b06",
          "md5": "df9433551b309f38499e3a248788a3d9"
        }
      ]
    },
    {
      "name": "wasmJsResourcesElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.libraryelements": "kotlin-multiplatformresourcesjs",
        "org.gradle.usage": "kotlin-multiplatformresourcesjs",
        "org.jetbrains.kotlin.platform.type": "wasm",
        "org.jetbrains.kotlin.wasm.target": "js"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.21"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-js",
          "version": {
            "requires": "3.0.3"
          }
        },
        {
          "group": "org.jetbrains.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "1.7.3"
          }
        },
        {
          "group": "org.jetbrains.compose.foundation",
          "module": "foundation",
          "version": {
            "requires": "1.7.3"
          }
        },
        {
          "group": "org.jetbrains.compose.material3",
          "module": "material3",
          "version": {
            "requires": "1.7.3"
          }
        },
        {
          "group": "org.jetbrains.compose.ui",
          "module": "ui",
          "version": {
            "requires": "1.7.3"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.7.3"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "io.coil-kt.coil3",
          "module": "coil-compose",
          "version": {
            "requires": "3.0.4"
          }
        },
        {
          "group": "io.coil-kt.coil3",
          "module": "coil-network-ktor3",
          "version": {
            "requires": "3.0.4"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-core",
          "version": {
            "requires": "3.0.3"
          }
        }
      ],
      "files": [
        {
          "name": "kotlin-compose-0.2.0.kotlin_resources.zip",
          "url": "kotlin-compose-wasm-js-0.2.0-kotlin_resources.kotlin_resources.zip",
          "size": 344,
          "sha512": "8025076117b891761afa96b0a80b07db42d9aa7313451520f50b670bfff8d4a2854628973a341779eae61ca0b0e4e3cd0b4d5b7fc2219a3db228330aa5e13109",
          "sha256": "49f79350f9fd328344efb0cb6ca18bea46e46d684159e98499c17c95abf7079f",
          "sha1": "0cd21e86545b6041c77d6417d935b47cbd67fd88",
          "md5": "dece592e84a078003da9f73943f85fd3"
        }
      ]
    }
  ]
}
