{
  "formatVersion": "1.1",
  "component": {
    "url": "../../kotlin-compose-schema/0.10.0/kotlin-compose-schema-0.10.0.module",
    "group": "ai.factoredui",
    "module": "kotlin-compose-schema",
    "version": "0.10.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14"
    }
  },
  "variants": [
    {
      "name": "wasmJsApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "wasm",
        "org.jetbrains.kotlin.wasm.target": "js"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.21"
          }
        }
      ],
      "files": [
        {
          "name": "kotlin-compose-schema-wasm-js-0.10.0.klib",
          "url": "kotlin-compose-schema-wasm-js-0.10.0.klib",
          "size": 95063,
          "sha512": "d1cc24d63b49684685120aa537792ae284a091f281aee7b357203c872682e96654c9d8781c2ee838f3a6146498ef7ad4e5c2068f36902b9d5fc3960f5b12afa0",
          "sha256": "f1369f5b22e9b4ea1c8cb86624f953618fd219d4ac72f4566176b6bc4b5ecfea",
          "sha1": "d3d353a701752ffdc3440c769a40a67cc4ee77d3",
          "md5": "5800561b2d338100c9dfce433dd2453a"
        }
      ]
    },
    {
      "name": "wasmJsRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.platform.type": "wasm",
        "org.jetbrains.kotlin.wasm.target": "js"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.21"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.11.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-datetime",
          "version": {
            "requires": "0.7.1"
          }
        }
      ],
      "files": [
        {
          "name": "kotlin-compose-schema-wasm-js-0.10.0.klib",
          "url": "kotlin-compose-schema-wasm-js-0.10.0.klib",
          "size": 95063,
          "sha512": "d1cc24d63b49684685120aa537792ae284a091f281aee7b357203c872682e96654c9d8781c2ee838f3a6146498ef7ad4e5c2068f36902b9d5fc3960f5b12afa0",
          "sha256": "f1369f5b22e9b4ea1c8cb86624f953618fd219d4ac72f4566176b6bc4b5ecfea",
          "sha1": "d3d353a701752ffdc3440c769a40a67cc4ee77d3",
          "md5": "5800561b2d338100c9dfce433dd2453a"
        }
      ]
    },
    {
      "name": "wasmJsSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.platform.type": "wasm",
        "org.jetbrains.kotlin.wasm.target": "js"
      },
      "files": [
        {
          "name": "kotlin-compose-schema-wasm-js-0.10.0-sources.jar",
          "url": "kotlin-compose-schema-wasm-js-0.10.0-sources.jar",
          "size": 10001,
          "sha512": "71cec9d5887d8c8550ef4f906682c9132c7f5c113b54a19b2cab1f702ab714693db442e4ec6308070795d47a25976d72d12638f368a0fb9b42b198d33e43d898",
          "sha256": "f7c01cbaa1bdaea32adcfe422e834bd8a159d7552b9f210042929c82ad087f32",
          "sha1": "f4b105061fc01c35414b5766a1200f469695849b",
          "md5": "129b40ea92cc22a10556906f7c1ac502"
        }
      ]
    }
  ]
}
