{
  "formatVersion": "1.1",
  "component": {
    "url": "../../kotlin-compose-schema/0.9.0/kotlin-compose-schema-0.9.0.module",
    "group": "ai.factoredui",
    "module": "kotlin-compose-schema",
    "version": "0.9.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14"
    }
  },
  "variants": [
    {
      "name": "releaseApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.21"
          }
        }
      ],
      "files": [
        {
          "name": "kotlin-compose-schema-release.aar",
          "url": "kotlin-compose-schema-android-0.9.0.aar",
          "size": 129745,
          "sha512": "8ed8a829e23c73bfc823d1b9c8d2ab2cf1d7d374d1e84c48a594fcb97098a116b3cd6b6923d07d44c1ba4bc5852ff571b1d75a25dce5464dda60ed929b910303",
          "sha256": "def34c4102dd822c120ca4d8340d60fd0a94139ade31fc1154c25d19ea49f01b",
          "sha1": "d56c2fa49d00a1240981b23d2a1eb9ab78f3060a",
          "md5": "dbe9aeffc95dc8560d65153aa5a9be6e"
        }
      ]
    },
    {
      "name": "releaseRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.21"
          },
          "excludes": [
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-annotations-common"
            }
          ]
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.11.0"
          },
          "excludes": [
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-annotations-common"
            }
          ]
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-datetime",
          "version": {
            "requires": "0.7.1"
          },
          "excludes": [
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-annotations-common"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "kotlin-compose-schema-release.aar",
          "url": "kotlin-compose-schema-android-0.9.0.aar",
          "size": 129745,
          "sha512": "8ed8a829e23c73bfc823d1b9c8d2ab2cf1d7d374d1e84c48a594fcb97098a116b3cd6b6923d07d44c1ba4bc5852ff571b1d75a25dce5464dda60ed929b910303",
          "sha256": "def34c4102dd822c120ca4d8340d60fd0a94139ade31fc1154c25d19ea49f01b",
          "sha1": "d56c2fa49d00a1240981b23d2a1eb9ab78f3060a",
          "md5": "dbe9aeffc95dc8560d65153aa5a9be6e"
        }
      ]
    },
    {
      "name": "releaseSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "android",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "files": [
        {
          "name": "kotlin-compose-schema-android-0.9.0-sources.jar",
          "url": "kotlin-compose-schema-android-0.9.0-sources.jar",
          "size": 9238,
          "sha512": "4affb9330a226168437bcad22a19f8f492f87332b9c51c96580c010ee95755cf8883c32b4ce9371c7e3c9c54c909a2e2a17dece57bd3fe38fb1c6e7adcfe5637",
          "sha256": "e78bf3fee0afef260d2b7b9d2508411a3f75322d03950f74b61a4c43921cf425",
          "sha1": "cf4b1509d3d93b4bfbb46c0419551f4cbc1df5ad",
          "md5": "185746942c49e1f311e19e8f75d18e3e"
        }
      ]
    }
  ]
}
