{
  "formatVersion": "1.1",
  "component": {
    "url": "../../kotlin-compose-schema/0.11.0/kotlin-compose-schema-0.11.0.module",
    "group": "ai.factoredui",
    "module": "kotlin-compose-schema",
    "version": "0.11.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14"
    }
  },
  "variants": [
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.21"
          }
        }
      ],
      "files": [
        {
          "name": "kotlin-compose-schema-jvm-0.11.0.jar",
          "url": "kotlin-compose-schema-jvm-0.11.0.jar",
          "size": 146897,
          "sha512": "ad8fb41336f0068a53cca200623d09d14f3efea3152e0194c2aa03ec2be1be6c9bdc7533bbd28481facc7f7efdf6cf756edf7703a7ef7042965592ce6020851c",
          "sha256": "f018dd7cd6e52aace34007bc19a58a550d7aaa30a1ebdb8d320738c500b703d2",
          "sha1": "e2f06265e21052c1cbc0b99155ba2b39ca4ca64e",
          "md5": "712f7048598cd186438aae4f4a131717"
        }
      ]
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.21"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.11.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-datetime",
          "version": {
            "requires": "0.7.1"
          }
        }
      ],
      "files": [
        {
          "name": "kotlin-compose-schema-jvm-0.11.0.jar",
          "url": "kotlin-compose-schema-jvm-0.11.0.jar",
          "size": 146897,
          "sha512": "ad8fb41336f0068a53cca200623d09d14f3efea3152e0194c2aa03ec2be1be6c9bdc7533bbd28481facc7f7efdf6cf756edf7703a7ef7042965592ce6020851c",
          "sha256": "f018dd7cd6e52aace34007bc19a58a550d7aaa30a1ebdb8d320738c500b703d2",
          "sha1": "e2f06265e21052c1cbc0b99155ba2b39ca4ca64e",
          "md5": "712f7048598cd186438aae4f4a131717"
        }
      ]
    },
    {
      "name": "jvmSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "kotlin-compose-schema-jvm-0.11.0-sources.jar",
          "url": "kotlin-compose-schema-jvm-0.11.0-sources.jar",
          "size": 10330,
          "sha512": "a382fccd52fdda3052f9860ae1672b6ddec46e4a42b1e470b34abe77f572b3c7c6147c02fc717466e1728d23e9cfe6ba79773e05c07e1dd4eab4c783616c743c",
          "sha256": "56a70713b4824ac51521f5bf2b1de228e11b1f7f41ba3da94a83ac3f6562aba9",
          "sha1": "143eaa67fbf50a4e8d67677a653de0d876e21a0e",
          "md5": "2d6fb7c3de3193d0eebbfafcccb1d343"
        }
      ]
    }
  ]
}
