{
  "formatVersion": "1.1",
  "component": {
    "url": "../../kotlin-compose-schema/0.16.0/kotlin-compose-schema-0.16.0.module",
    "group": "ai.factoredui",
    "module": "kotlin-compose-schema",
    "version": "0.16.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14"
    }
  },
  "variants": [
    {
      "name": "iosArm64ApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.21"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.11.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-datetime",
          "version": {
            "requires": "0.7.1"
          }
        }
      ],
      "files": [
        {
          "name": "kotlin-compose-schema-iosArm64Main-0.16.0.klib",
          "url": "kotlin-compose-schema-iosarm64-0.16.0.klib",
          "size": 121868,
          "sha512": "85745a03d4147a8bfd62bb53368964d189d2af3c022763b748efdeb7509ccb967531f46c0c8ec55e04fb30caad5205c07083ed2d898e97e3473c4c7c74711d6c",
          "sha256": "921b6f779aab56221929c83b7b23f782e02853f5822301efe4b6054c3c48fd69",
          "sha1": "7cf6533de177e08561c99209760ea453c1ce3a0a",
          "md5": "93efd85b1907e4ce1e99ccc80ff01596"
        }
      ]
    },
    {
      "name": "iosArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "files": [
        {
          "name": "kotlin-compose-schema-iosarm64-0.16.0-sources.jar",
          "url": "kotlin-compose-schema-iosarm64-0.16.0-sources.jar",
          "size": 12074,
          "sha512": "0f83535733491c1df2c8839f9e8cdd741d094d2fcf5c5867c4cf9aa6783766e31904264a5c2a531bc40e1042f24ec16f7cd966ade28eabb144589ed74e702521",
          "sha256": "8a0a6c9b47f3d952b1cbeb02da39bb2b5beac4745711c6131ad3ffefeb30fd2c",
          "sha1": "78b5446e4ba180e5bf8bb8332cadb6e52ddc94b6",
          "md5": "6b36540fbd346ac3266ff6fe483d0eca"
        }
      ]
    },
    {
      "name": "iosArm64MetadataElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.21"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.11.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-datetime",
          "version": {
            "requires": "0.7.1"
          }
        }
      ],
      "files": [
        {
          "name": "kotlin-compose-schema-iosarm64-0.16.0-metadata.jar",
          "url": "kotlin-compose-schema-iosarm64-0.16.0-metadata.jar",
          "size": 261,
          "sha512": "7f13ae05d4bf542d1a480fd28a3e6ad1ea699572ead2448a58deaba08a2b9b29918f9ce06ea356a7c267a07ab8b04f471d3a12d0761008be6c9f3272e6b630c2",
          "sha256": "e80525f49a2e472407343916ba2598833f05b8dd0b8a1b8f26b51e8d0749803f",
          "sha1": "5cdd4637960a2af6760ae3076b134fb8eb6a934e",
          "md5": "3e2b4599786085bd674681f897d0a78c"
        }
      ]
    }
  ]
}
