{
  "formatVersion": "1.1",
  "component": {
    "url": "../../kotlin-compose/0.20.7/kotlin-compose-0.20.7.module",
    "group": "ai.factoredui",
    "module": "kotlin-compose",
    "version": "0.20.7",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14"
    }
  },
  "variants": [
    {
      "name": "desktopApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "ai.factoredui",
          "module": "kotlin-compose-schema",
          "version": {
            "requires": "0.20.7"
          }
        },
        {
          "group": "ai.factoredui",
          "module": "kotlin-compose-capture",
          "version": {
            "requires": "0.20.7"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.21"
          }
        }
      ],
      "files": [
        {
          "name": "kotlin-compose-desktop-0.20.7.jar",
          "url": "kotlin-compose-desktop-0.20.7.jar",
          "size": 927226,
          "sha512": "68bdf25d5073808a703843ce3f6c729bddf002549a6b604470ee9619cc47638858b4b941720150f0cce0e74b9b218dd0c9e4c5564ace125c64414e243e927cd9",
          "sha256": "d9c78bd0bc27485e91cb0dcfa6800d989f0ae066cfdf123594ecf917ae149de8",
          "sha1": "bb501f7feca6bf05689a6c48896c9908409934bf",
          "md5": "694d9213fbb503961d4582e8d5c9f67f"
        }
      ]
    },
    {
      "name": "desktopRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "ai.factoredui",
          "module": "kotlin-compose-schema",
          "version": {
            "requires": "0.20.7"
          }
        },
        {
          "group": "ai.factoredui",
          "module": "kotlin-compose-capture",
          "version": {
            "requires": "0.20.7"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.21"
          }
        },
        {
          "group": "org.jetbrains.compose.desktop",
          "module": "desktop",
          "version": {
            "requires": "1.10.3"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-okhttp",
          "version": {
            "requires": "3.2.4"
          }
        },
        {
          "group": "org.jetbrains.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "1.10.3"
          }
        },
        {
          "group": "org.jetbrains.compose.foundation",
          "module": "foundation",
          "version": {
            "requires": "1.10.3"
          }
        },
        {
          "group": "org.jetbrains.compose.material3",
          "module": "material3",
          "version": {
            "requires": "1.9.0-beta03"
          }
        },
        {
          "group": "org.jetbrains.compose.ui",
          "module": "ui",
          "version": {
            "requires": "1.10.3"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.11.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.10.2"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-datetime",
          "version": {
            "requires": "0.7.1"
          }
        },
        {
          "group": "io.coil-kt.coil3",
          "module": "coil-compose",
          "version": {
            "requires": "3.2.0"
          }
        },
        {
          "group": "io.coil-kt.coil3",
          "module": "coil-network-ktor3",
          "version": {
            "requires": "3.2.0"
          }
        },
        {
          "group": "io.coil-kt.coil3",
          "module": "coil-svg",
          "version": {
            "requires": "3.2.0"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-core",
          "version": {
            "requires": "3.2.4"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-content-negotiation",
          "version": {
            "requires": "3.2.4"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-serialization-kotlinx-json",
          "version": {
            "requires": "3.2.4"
          }
        }
      ],
      "files": [
        {
          "name": "kotlin-compose-desktop-0.20.7.jar",
          "url": "kotlin-compose-desktop-0.20.7.jar",
          "size": 927226,
          "sha512": "68bdf25d5073808a703843ce3f6c729bddf002549a6b604470ee9619cc47638858b4b941720150f0cce0e74b9b218dd0c9e4c5564ace125c64414e243e927cd9",
          "sha256": "d9c78bd0bc27485e91cb0dcfa6800d989f0ae066cfdf123594ecf917ae149de8",
          "sha1": "bb501f7feca6bf05689a6c48896c9908409934bf",
          "md5": "694d9213fbb503961d4582e8d5c9f67f"
        }
      ]
    },
    {
      "name": "desktopSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "kotlin-compose-desktop-0.20.7-sources.jar",
          "url": "kotlin-compose-desktop-0.20.7-sources.jar",
          "size": 114854,
          "sha512": "91a116cd281b07c8c2b896a8118634d8ef913ee9225064dc770d256b32eb89d3efdf8b95d4f712c6d20039752e7038e2840e4436176cfbada7927ed2cc501570",
          "sha256": "c0512e76e6809ab3121bf9c87b0810a33bc357fd906d7ded20f091e6966355ef",
          "sha1": "22c98eff177318cd37b1b799ad4421c5858ebc41",
          "md5": "f6e41637a662071d34e7bf799b9b5abb"
        }
      ]
    }
  ]
}
