{
  "formatVersion": "1.1",
  "component": {
    "url": "../../kotlin-compose/0.15.1/kotlin-compose-0.15.1.module",
    "group": "ai.factoredui",
    "module": "kotlin-compose",
    "version": "0.15.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14"
    }
  },
  "variants": [
    {
      "name": "desktopApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "ai.factoredui",
          "module": "kotlin-compose-schema",
          "version": {
            "requires": "0.15.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.21"
          }
        }
      ],
      "files": [
        {
          "name": "kotlin-compose-desktop-0.15.1.jar",
          "url": "kotlin-compose-desktop-0.15.1.jar",
          "size": 807276,
          "sha512": "866b8ac97b63ad0362bfc14e5ac8bbb15126a36a6b4114c44c56c509ee58dca26f6569389c51b8654d5512534bc69884454f124781eb4476e5e735f2a404499c",
          "sha256": "b781a1c0d295ac2a52629bf7a56d5f6c586506ca2f9fe709f4f544e43b06dd41",
          "sha1": "b7e0a7b31c9664655808b19fa9facc29f278b0ba",
          "md5": "2570f64e835a6e587be38823ff8be7d0"
        }
      ]
    },
    {
      "name": "desktopRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "ai.factoredui",
          "module": "kotlin-compose-schema",
          "version": {
            "requires": "0.15.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.21"
          }
        },
        {
          "group": "org.jetbrains.compose.desktop",
          "module": "desktop-jvm-linux-x64",
          "version": {
            "requires": "1.10.3"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-okhttp",
          "version": {
            "requires": "3.2.0"
          }
        },
        {
          "group": "org.jetbrains.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "1.10.3"
          }
        },
        {
          "group": "org.jetbrains.compose.foundation",
          "module": "foundation",
          "version": {
            "requires": "1.10.3"
          }
        },
        {
          "group": "org.jetbrains.compose.material3",
          "module": "material3",
          "version": {
            "requires": "1.9.0-beta03"
          }
        },
        {
          "group": "org.jetbrains.compose.ui",
          "module": "ui",
          "version": {
            "requires": "1.10.3"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.11.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.10.2"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-datetime",
          "version": {
            "requires": "0.7.1"
          }
        },
        {
          "group": "io.coil-kt.coil3",
          "module": "coil-compose",
          "version": {
            "requires": "3.2.0"
          }
        },
        {
          "group": "io.coil-kt.coil3",
          "module": "coil-network-ktor3",
          "version": {
            "requires": "3.2.0"
          }
        },
        {
          "group": "io.coil-kt.coil3",
          "module": "coil-svg",
          "version": {
            "requires": "3.2.0"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-core",
          "version": {
            "requires": "3.2.0"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-content-negotiation",
          "version": {
            "requires": "3.2.0"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-serialization-kotlinx-json",
          "version": {
            "requires": "3.2.0"
          }
        }
      ],
      "files": [
        {
          "name": "kotlin-compose-desktop-0.15.1.jar",
          "url": "kotlin-compose-desktop-0.15.1.jar",
          "size": 807276,
          "sha512": "866b8ac97b63ad0362bfc14e5ac8bbb15126a36a6b4114c44c56c509ee58dca26f6569389c51b8654d5512534bc69884454f124781eb4476e5e735f2a404499c",
          "sha256": "b781a1c0d295ac2a52629bf7a56d5f6c586506ca2f9fe709f4f544e43b06dd41",
          "sha1": "b7e0a7b31c9664655808b19fa9facc29f278b0ba",
          "md5": "2570f64e835a6e587be38823ff8be7d0"
        }
      ]
    },
    {
      "name": "desktopSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "kotlin-compose-desktop-0.15.1-sources.jar",
          "url": "kotlin-compose-desktop-0.15.1-sources.jar",
          "size": 95799,
          "sha512": "45af509646c403c562dfc04cf1e5a20713fbaa90a0d6dfb5e4ca1b8189161148d7a8bfd5ec971260bc8dcb136e7531d06b3332e54d7f89fceb75b0c1e1f6ab90",
          "sha256": "7643ec8519bdd6ba963f43a6914db8e955ccde53dd3bc9e858c68e405380de01",
          "sha1": "abbb228ff9f4a32755bc6a0241e66a8b608c7587",
          "md5": "f8bd4d1dfb0004ddd721b1d84242a068"
        }
      ]
    }
  ]
}
