{
  "formatVersion": "1.1",
  "component": {
    "url": "../../kotlin-compose-schema/0.21.0/kotlin-compose-schema-0.21.0.module",
    "group": "ai.factoredui",
    "module": "kotlin-compose-schema",
    "version": "0.21.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14"
    }
  },
  "variants": [
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.21"
          }
        }
      ],
      "files": [
        {
          "name": "kotlin-compose-schema-jvm-0.21.0.jar",
          "url": "kotlin-compose-schema-jvm-0.21.0.jar",
          "size": 257401,
          "sha512": "c49c6ca2c2377de46e84182688e307dc5200a1af24879e194b9abaab0fe27808271a844922ccd2b16e3b86169236c54a60c709ea2839aa903ada730931c250b9",
          "sha256": "a803dac40d54accf64b97eac777118ee7a285eccd9bb93754439429155feaa5d",
          "sha1": "c227f4fbca0eb0e90fa2c49aaf5920ae9f5d9730",
          "md5": "9f5c7898caf9fb3b38990688e5a0fc09"
        }
      ]
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.21"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.11.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-datetime",
          "version": {
            "requires": "0.7.1"
          }
        }
      ],
      "files": [
        {
          "name": "kotlin-compose-schema-jvm-0.21.0.jar",
          "url": "kotlin-compose-schema-jvm-0.21.0.jar",
          "size": 257401,
          "sha512": "c49c6ca2c2377de46e84182688e307dc5200a1af24879e194b9abaab0fe27808271a844922ccd2b16e3b86169236c54a60c709ea2839aa903ada730931c250b9",
          "sha256": "a803dac40d54accf64b97eac777118ee7a285eccd9bb93754439429155feaa5d",
          "sha1": "c227f4fbca0eb0e90fa2c49aaf5920ae9f5d9730",
          "md5": "9f5c7898caf9fb3b38990688e5a0fc09"
        }
      ]
    },
    {
      "name": "jvmSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "kotlin-compose-schema-jvm-0.21.0-sources.jar",
          "url": "kotlin-compose-schema-jvm-0.21.0-sources.jar",
          "size": 21268,
          "sha512": "1774b1fd3212bfdc80ecbbc9e7187c8fce3678923d55f577323e20ad693b9f8f7b23ceb3170ecdfbd6ed128823d024ecbc929e5fe6c6ee7fdd36ff20ba590505",
          "sha256": "f2d8394a1f338471010a1cd4be4c6c61a61b6c7c2f061591ea4ebdd0f0f6026d",
          "sha1": "61b9d1524295ec25c6415dc41bba6da086bb46d5",
          "md5": "2366df9d040e75148abafb0c9948d6b1"
        }
      ]
    }
  ]
}
