{
  "formatVersion": "1.1",
  "component": {
    "url": "../../kotlin-compose-schema/0.20.2/kotlin-compose-schema-0.20.2.module",
    "group": "ai.factoredui",
    "module": "kotlin-compose-schema",
    "version": "0.20.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14"
    }
  },
  "variants": [
    {
      "name": "linuxX64ApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "linux_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.21"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.11.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-datetime",
          "version": {
            "requires": "0.7.1"
          }
        }
      ],
      "files": [
        {
          "name": "kotlin-compose-schema-linuxX64Main-0.20.2.klib",
          "url": "kotlin-compose-schema-linuxx64-0.20.2.klib",
          "size": 131321,
          "sha512": "0177a6b4930b274f7cb5c31502a2bd5aa5855944678c8f467a15681055c6c351cb17370d73f3eb01676695e3af5c6dcbe66a5a83cfd7e5da72c0e59d93b6d2d5",
          "sha256": "43257188b5887b170ab730e429d1c64a7ee38e78283439084c94ee87c69b84bc",
          "sha1": "5b045f4e16d492978205da605f9ed5bfba1e24e2",
          "md5": "1e9a0a88c81fae0c945f648be486247d"
        }
      ]
    },
    {
      "name": "linuxX64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "linux_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "files": [
        {
          "name": "kotlin-compose-schema-linuxx64-0.20.2-sources.jar",
          "url": "kotlin-compose-schema-linuxx64-0.20.2-sources.jar",
          "size": 12227,
          "sha512": "5db475c4b75a6cc059c089fcf69d18564941622e5a810c8f3fdde229351edc07975303b83f2edfd9da46d15a48aea3d9f271f9afbe21b858914f06fe34feffe7",
          "sha256": "d4edad5c0c1cbc5e0fb2f061b7c94c482e244a006cab0f66be88b71caa346434",
          "sha1": "7df2897c68f265f63bc65f877a394cb724681794",
          "md5": "2f93944aaafde82ab59bffdf39087647"
        }
      ]
    }
  ]
}
