{
  "formatVersion": "1.1",
  "component": {
    "url": "../../kotlin-compose-schema/0.20.3/kotlin-compose-schema-0.20.3.module",
    "group": "ai.factoredui",
    "module": "kotlin-compose-schema",
    "version": "0.20.3",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14"
    }
  },
  "variants": [
    {
      "name": "iosArm64ApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.21"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.11.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-datetime",
          "version": {
            "requires": "0.7.1"
          }
        }
      ],
      "files": [
        {
          "name": "kotlin-compose-schema-iosArm64Main-0.20.3.klib",
          "url": "kotlin-compose-schema-iosarm64-0.20.3.klib",
          "size": 137461,
          "sha512": "dd7a2110681db28677f985a7e7126882b1d461fea960f170d7f93507f6b36512e4973ccdbb817848645eeb5b0dbb7530857ff4755644030b4d32031bc31417de",
          "sha256": "893bb2b2d21ae297b1b4f1a7cd4848ee5a594c3259efd9787c5724331e20a25f",
          "sha1": "40b11cc015e86e1b4db858e6432f9a593f7a4913",
          "md5": "e2e6c2c64e15a9fc264975ed7ca3c127"
        }
      ]
    },
    {
      "name": "iosArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "files": [
        {
          "name": "kotlin-compose-schema-iosarm64-0.20.3-sources.jar",
          "url": "kotlin-compose-schema-iosarm64-0.20.3-sources.jar",
          "size": 12655,
          "sha512": "56fad55d8e0c43351bd16088455a1bcfe12f22e93d50a58a236ed4270d4ec6cd9dc6294debd66a00473cdbecf915c1c94c703765246c9188668de7ea1df4a028",
          "sha256": "65da5477d0683a86e9ca2d230a6999774e17b1fd8a4c299c586afb10a628fd3a",
          "sha1": "0f80938d4b52e433a40a5785fa813e91cc17238d",
          "md5": "34413440d782b0b921f92eced8f06fa3"
        }
      ]
    },
    {
      "name": "iosArm64MetadataElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.21"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.11.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-datetime",
          "version": {
            "requires": "0.7.1"
          }
        }
      ],
      "files": [
        {
          "name": "kotlin-compose-schema-iosarm64-0.20.3-metadata.jar",
          "url": "kotlin-compose-schema-iosarm64-0.20.3-metadata.jar",
          "size": 261,
          "sha512": "7cdd1ba2ec1c38eaffffba952799a2589934893025c08f2dd923de05c2ff375b783c68cda8c5836148bc33bed8813d669f8a5b86b3c70ebee0ac8204713b0cc9",
          "sha256": "f453c3e37b40e81af00a11437b6fb7e7faff713e4b882bafe0bf651f78cf1599",
          "sha1": "7b6b7319c35f54d6078b3de38eeb90b8ec6dc8d2",
          "md5": "8c060371c9b656933f8fb198e084350e"
        }
      ]
    }
  ]
}
