{
  "formatVersion": "1.1",
  "component": {
    "url": "../../kotlin-compose-capture/0.20.3/kotlin-compose-capture-0.20.3.module",
    "group": "ai.factoredui",
    "module": "kotlin-compose-capture",
    "version": "0.20.3",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14"
    }
  },
  "variants": [
    {
      "name": "iosX64ApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.21"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.11.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-datetime",
          "version": {
            "requires": "0.7.1"
          }
        }
      ],
      "files": [
        {
          "name": "kotlin-compose-capture-iosX64Main-0.20.3.klib",
          "url": "kotlin-compose-capture-iosx64-0.20.3.klib",
          "size": 22631,
          "sha512": "ac2e6b41bec6d172e80e221ca3ac459faadba82f398ae2944559e8b55bc81337c83bfbdfb194e8741de6ce8df3e726403cfc49386f7f185eaf057e70e06375e5",
          "sha256": "857ab61bdac25450d0efc61e5ac8b63655b28b70106efca7ddbb80e25cca0c95",
          "sha1": "6baccecd0ed96b8160a4b33e3f7d163b5049154f",
          "md5": "b5a67d0bd779cfb58138508ba3fc0d53"
        }
      ]
    },
    {
      "name": "iosX64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "files": [
        {
          "name": "kotlin-compose-capture-iosx64-0.20.3-sources.jar",
          "url": "kotlin-compose-capture-iosx64-0.20.3-sources.jar",
          "size": 2675,
          "sha512": "2f30e91c5b3bb7af31334533cd53498c1f205f723d4956b8bd8d8d2c9480058b2ae47a8fdca96e615561199fa50a6a22b561bc5220848629ef7fe47dd537c6ef",
          "sha256": "c82f37fc21d50fc8ecc030b86b4137334808ac44ee33a7e7732c739eb29d0700",
          "sha1": "84a2b3c08bc728e17e68a868cfa57eada683f007",
          "md5": "1ce993c162e5d1582ebec69fad7b8a80"
        }
      ]
    },
    {
      "name": "iosX64MetadataElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.21"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.11.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-datetime",
          "version": {
            "requires": "0.7.1"
          }
        }
      ],
      "files": [
        {
          "name": "kotlin-compose-capture-iosx64-0.20.3-metadata.jar",
          "url": "kotlin-compose-capture-iosx64-0.20.3-metadata.jar",
          "size": 261,
          "sha512": "552b33ece4c635c75301760f4ee6a274b2dec51a1308de5d5bd91018669f39cca8e7c710a6a545674df4fa108f942f79c5c4646d8fad2ebee7c2b2f3a98df0b2",
          "sha256": "d6f2d8e6f25081c1f895c31142b2fd07d487e39fbe43763519c9626f6f31ea23",
          "sha1": "755facae58fbd5524db5e356070392a5ba4e01af",
          "md5": "5451aede563e35618c4b4afd2fd8d623"
        }
      ]
    }
  ]
}
