{
  "formatVersion": "1.1",
  "component": {
    "url": "../../kotlin-compose-schema/0.19.0/kotlin-compose-schema-0.19.0.module",
    "group": "ai.factoredui",
    "module": "kotlin-compose-schema",
    "version": "0.19.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14"
    }
  },
  "variants": [
    {
      "name": "iosArm64ApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.21"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.11.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-datetime",
          "version": {
            "requires": "0.7.1"
          }
        }
      ],
      "files": [
        {
          "name": "kotlin-compose-schema-iosArm64Main-0.19.0.klib",
          "url": "kotlin-compose-schema-iosarm64-0.19.0.klib",
          "size": 112879,
          "sha512": "2e17252b7697664759efa8189322febbe5a6cbf49986fb5cfb03a384a3c84579a4e2dc71a58301ed237d94b76794df2b5d527805beb3fb7e56f1c78779a8d710",
          "sha256": "10464db41f1490fd405f0e7b84ec7668958cb14385726812ce473bbe5f5653e5",
          "sha1": "11b459f5f44a42b2a86ca872d661c548bf9aafd8",
          "md5": "c4458c90b4092ca363a5fc4214c65127"
        }
      ]
    },
    {
      "name": "iosArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "files": [
        {
          "name": "kotlin-compose-schema-iosarm64-0.19.0-sources.jar",
          "url": "kotlin-compose-schema-iosarm64-0.19.0-sources.jar",
          "size": 11244,
          "sha512": "4f4fab68f47ca454347578d19a8686b5dc6d91880e982fd2ad2b00f30766de0e444f09cb6f94ced0f2cbd5a2748258be422665dcbc86dba910198bae1d2e7e23",
          "sha256": "98d201c5535c8ec3512dab69330bbbe3c2c19592d3a076c1131fc37ff0739ac7",
          "sha1": "f90a56dd668840053b36c36fb9bfaafba11c0ab9",
          "md5": "93f15f553e8b647097b619e1e104df7c"
        }
      ]
    },
    {
      "name": "iosArm64MetadataElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.21"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.11.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-datetime",
          "version": {
            "requires": "0.7.1"
          }
        }
      ],
      "files": [
        {
          "name": "kotlin-compose-schema-iosarm64-0.19.0-metadata.jar",
          "url": "kotlin-compose-schema-iosarm64-0.19.0-metadata.jar",
          "size": 261,
          "sha512": "382c1cd4d39d6c01cdd2ebb61287f9891c9321fbbc1eb38b568f7499b903680916223b8b6c18874db7e7d71c9a011f4f9cd199c1af05301e347f13e71e41eb46",
          "sha256": "6d4f53c4d050f0cb9010eee38eeb6efc032057e951a896ebe530b02d89207b8a",
          "sha1": "28eda809c2c66a046acf12de48e556a5ce1fcaec",
          "md5": "51be341088d00f238ee27a391a71a2d3"
        }
      ]
    }
  ]
}
