{
  "formatVersion": "1.1",
  "component": {
    "url": "../../kotlin-compose-schema/0.20.0/kotlin-compose-schema-0.20.0.module",
    "group": "ai.factoredui",
    "module": "kotlin-compose-schema",
    "version": "0.20.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14"
    }
  },
  "variants": [
    {
      "name": "iosX64ApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.21"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.11.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-datetime",
          "version": {
            "requires": "0.7.1"
          }
        }
      ],
      "files": [
        {
          "name": "kotlin-compose-schema-iosX64Main-0.20.0.klib",
          "url": "kotlin-compose-schema-iosx64-0.20.0.klib",
          "size": 125919,
          "sha512": "6a938062f2d6bf680bb401cf3eeee2314197cc41c2e512c85ff5cb477aaba769e7456e6b97a28411afa50f84a88afbcab860cef6ee8c35b937eb1e15bb4fd73c",
          "sha256": "179b6ba69a19efc505c2305bde9169f8f9fbd2c93f01953231699baab0c41821",
          "sha1": "d801bea9f149fc626d2463d7b77378d22bae2388",
          "md5": "fe2da06758573100c418818c271ff9e3"
        }
      ]
    },
    {
      "name": "iosX64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "files": [
        {
          "name": "kotlin-compose-schema-iosx64-0.20.0-sources.jar",
          "url": "kotlin-compose-schema-iosx64-0.20.0-sources.jar",
          "size": 11925,
          "sha512": "d1645926de0ed497e29af6c88a436b8b476605cbcf4c24d77f201dde5dc5c9cc1ebab9abcc50f0ac083e71007b9d0274013de0c58ad30852cae2bab4e9d00cb1",
          "sha256": "73d01c96b3c64ca8363f6f66713809c860ec92db0979d282b8a093525ea084e0",
          "sha1": "91339d0e477881713eba748395a8388c2c5e97d9",
          "md5": "dd76c50fd5f31467021fb2455b52bc31"
        }
      ]
    },
    {
      "name": "iosX64MetadataElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.21"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.11.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-datetime",
          "version": {
            "requires": "0.7.1"
          }
        }
      ],
      "files": [
        {
          "name": "kotlin-compose-schema-iosx64-0.20.0-metadata.jar",
          "url": "kotlin-compose-schema-iosx64-0.20.0-metadata.jar",
          "size": 261,
          "sha512": "546536f80f27a3bfc4a48a8d4aba0d1f3d37520090765f6193e0e82107d4a915d128aec21db4c39dbe906745645229088dd7dec4e6fa9fc6a420aa0723dc2296",
          "sha256": "a8a03c68f1c9ccd37421374f56020f1c60e648e30aee0db3f75233774ce7b9fd",
          "sha1": "306844dd0885a907a7e80f169bf2193aacef0c50",
          "md5": "9fc16d68af33dbd5fa5edae3901d41a0"
        }
      ]
    }
  ]
}
