{
  "formatVersion": "1.1",
  "component": {
    "url": "../../kotlin-compose/0.16.0/kotlin-compose-0.16.0.module",
    "group": "ai.factoredui",
    "module": "kotlin-compose",
    "version": "0.16.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14"
    }
  },
  "variants": [
    {
      "name": "desktopApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "ai.factoredui",
          "module": "kotlin-compose-schema",
          "version": {
            "requires": "0.16.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.21"
          }
        }
      ],
      "files": [
        {
          "name": "kotlin-compose-desktop-0.16.0.jar",
          "url": "kotlin-compose-desktop-0.16.0.jar",
          "size": 616802,
          "sha512": "b85a7ea853903f0831a0a811655cce1b8bb9d85d1e8b6ff0e4702b0cde92cc397eedd7e0ae3141a6f4d6c7cea3b163782ef967dd49b4fc5a9411292ab065267e",
          "sha256": "c7723200094a65d90283dda1207268e2659424ab20f4a2e95479a7aecedca645",
          "sha1": "15dca71675113513e7667e5d7ddf27311cc907de",
          "md5": "f4082e0c9bccbfcacb081ad1dfa45deb"
        }
      ]
    },
    {
      "name": "desktopRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "ai.factoredui",
          "module": "kotlin-compose-schema",
          "version": {
            "requires": "0.16.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.21"
          }
        },
        {
          "group": "org.jetbrains.compose.desktop",
          "module": "desktop-jvm-linux-x64",
          "version": {
            "requires": "1.10.3"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-okhttp",
          "version": {
            "requires": "3.2.0"
          }
        },
        {
          "group": "org.jetbrains.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "1.10.3"
          }
        },
        {
          "group": "org.jetbrains.compose.foundation",
          "module": "foundation",
          "version": {
            "requires": "1.10.3"
          }
        },
        {
          "group": "org.jetbrains.compose.material3",
          "module": "material3",
          "version": {
            "requires": "1.9.0-beta03"
          }
        },
        {
          "group": "org.jetbrains.compose.ui",
          "module": "ui",
          "version": {
            "requires": "1.10.3"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.11.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.10.2"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-datetime",
          "version": {
            "requires": "0.7.1"
          }
        },
        {
          "group": "io.coil-kt.coil3",
          "module": "coil-compose",
          "version": {
            "requires": "3.2.0"
          }
        },
        {
          "group": "io.coil-kt.coil3",
          "module": "coil-network-ktor3",
          "version": {
            "requires": "3.2.0"
          }
        },
        {
          "group": "io.coil-kt.coil3",
          "module": "coil-svg",
          "version": {
            "requires": "3.2.0"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-core",
          "version": {
            "requires": "3.2.0"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-content-negotiation",
          "version": {
            "requires": "3.2.0"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-serialization-kotlinx-json",
          "version": {
            "requires": "3.2.0"
          }
        }
      ],
      "files": [
        {
          "name": "kotlin-compose-desktop-0.16.0.jar",
          "url": "kotlin-compose-desktop-0.16.0.jar",
          "size": 616802,
          "sha512": "b85a7ea853903f0831a0a811655cce1b8bb9d85d1e8b6ff0e4702b0cde92cc397eedd7e0ae3141a6f4d6c7cea3b163782ef967dd49b4fc5a9411292ab065267e",
          "sha256": "c7723200094a65d90283dda1207268e2659424ab20f4a2e95479a7aecedca645",
          "sha1": "15dca71675113513e7667e5d7ddf27311cc907de",
          "md5": "f4082e0c9bccbfcacb081ad1dfa45deb"
        }
      ]
    },
    {
      "name": "desktopSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "kotlin-compose-desktop-0.16.0-sources.jar",
          "url": "kotlin-compose-desktop-0.16.0-sources.jar",
          "size": 73108,
          "sha512": "719d419ba6fabc7e60ffb02de07f231b0030a2e23741da20941fef4617651c1a20fb3624f183977486a3df036f0a9b50aa9e7129b05f2183f1c8b491be2f29f3",
          "sha256": "319677f4a69efcf366050bc0daa9c8156b0d24323eee2b9f8e0c7d874877a4d1",
          "sha1": "4c82d5658377bf743362ca20dcaae9c302946a8f",
          "md5": "7bdfa8d7372dac22eb5160bafb560fa1"
        }
      ]
    }
  ]
}
