{
  "formatVersion": "1.1",
  "component": {
    "url": "../../kotlin-compose-schema/0.20.3/kotlin-compose-schema-0.20.3.module",
    "group": "ai.factoredui",
    "module": "kotlin-compose-schema",
    "version": "0.20.3",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14"
    }
  },
  "variants": [
    {
      "name": "wasmJsApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "wasm",
        "org.jetbrains.kotlin.wasm.target": "js"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.21"
          }
        }
      ],
      "files": [
        {
          "name": "kotlin-compose-schema-wasm-js-0.20.3.klib",
          "url": "kotlin-compose-schema-wasm-js-0.20.3.klib",
          "size": 133987,
          "sha512": "52e3f84b836f6983d9ba25b6fecd157eed97c38306d085dfaf8a8e807af066e7f0cdb66e20895abd54faaa1946e2f2f3bda2259d9a42ff00df5e5bbe2a741f9d",
          "sha256": "63bf5a285778fa8067b9ef386b155c1f1d57c7be9858a1cbbe0fcf3620a825e5",
          "sha1": "2a07bd9a6f9c6abccd373054c86206f7631c8691",
          "md5": "789c04ed58bf15ba80686482ffb596a1"
        }
      ]
    },
    {
      "name": "wasmJsRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.platform.type": "wasm",
        "org.jetbrains.kotlin.wasm.target": "js"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.21"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.11.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-datetime",
          "version": {
            "requires": "0.7.1"
          }
        }
      ],
      "files": [
        {
          "name": "kotlin-compose-schema-wasm-js-0.20.3.klib",
          "url": "kotlin-compose-schema-wasm-js-0.20.3.klib",
          "size": 133987,
          "sha512": "52e3f84b836f6983d9ba25b6fecd157eed97c38306d085dfaf8a8e807af066e7f0cdb66e20895abd54faaa1946e2f2f3bda2259d9a42ff00df5e5bbe2a741f9d",
          "sha256": "63bf5a285778fa8067b9ef386b155c1f1d57c7be9858a1cbbe0fcf3620a825e5",
          "sha1": "2a07bd9a6f9c6abccd373054c86206f7631c8691",
          "md5": "789c04ed58bf15ba80686482ffb596a1"
        }
      ]
    },
    {
      "name": "wasmJsSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.platform.type": "wasm",
        "org.jetbrains.kotlin.wasm.target": "js"
      },
      "files": [
        {
          "name": "kotlin-compose-schema-wasm-js-0.20.3-sources.jar",
          "url": "kotlin-compose-schema-wasm-js-0.20.3-sources.jar",
          "size": 12655,
          "sha512": "56fad55d8e0c43351bd16088455a1bcfe12f22e93d50a58a236ed4270d4ec6cd9dc6294debd66a00473cdbecf915c1c94c703765246c9188668de7ea1df4a028",
          "sha256": "65da5477d0683a86e9ca2d230a6999774e17b1fd8a4c299c586afb10a628fd3a",
          "sha1": "0f80938d4b52e433a40a5785fa813e91cc17238d",
          "md5": "34413440d782b0b921f92eced8f06fa3"
        }
      ]
    }
  ]
}
