{
  "formatVersion": "1.1",
  "component": {
    "url": "../../kotlin-compose-schema/0.20.2/kotlin-compose-schema-0.20.2.module",
    "group": "ai.factoredui",
    "module": "kotlin-compose-schema",
    "version": "0.20.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14"
    }
  },
  "variants": [
    {
      "name": "iosArm64ApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.21"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.11.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-datetime",
          "version": {
            "requires": "0.7.1"
          }
        }
      ],
      "files": [
        {
          "name": "kotlin-compose-schema-iosArm64Main-0.20.2.klib",
          "url": "kotlin-compose-schema-iosarm64-0.20.2.klib",
          "size": 131319,
          "sha512": "980a30d921f56ceb055510ba5a1cbd2dd86bb300037af71d13972ab91f633cf9a9e6d4399854e02c2ee5b6d769b70973b956e1f0c472a8b9b7de46f3dc5b8b97",
          "sha256": "0fc487b855d1d51a270208d0e2457d1e098e17dc5cb0db405672868587e1bcf8",
          "sha1": "eddb250fb57b79e54f271d170bd2f15d1305e975",
          "md5": "4d661d1d2dcd92e0142c0d2cfafa7f21"
        }
      ]
    },
    {
      "name": "iosArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "files": [
        {
          "name": "kotlin-compose-schema-iosarm64-0.20.2-sources.jar",
          "url": "kotlin-compose-schema-iosarm64-0.20.2-sources.jar",
          "size": 12227,
          "sha512": "5db475c4b75a6cc059c089fcf69d18564941622e5a810c8f3fdde229351edc07975303b83f2edfd9da46d15a48aea3d9f271f9afbe21b858914f06fe34feffe7",
          "sha256": "d4edad5c0c1cbc5e0fb2f061b7c94c482e244a006cab0f66be88b71caa346434",
          "sha1": "7df2897c68f265f63bc65f877a394cb724681794",
          "md5": "2f93944aaafde82ab59bffdf39087647"
        }
      ]
    },
    {
      "name": "iosArm64MetadataElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.21"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.11.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-datetime",
          "version": {
            "requires": "0.7.1"
          }
        }
      ],
      "files": [
        {
          "name": "kotlin-compose-schema-iosarm64-0.20.2-metadata.jar",
          "url": "kotlin-compose-schema-iosarm64-0.20.2-metadata.jar",
          "size": 261,
          "sha512": "992a008c3bbb4052af2aa57010beba84626d511b3ee850b2a9dda596ac8d97311de75bec61aa66ab9a60241d5bd620919f007f7fb8ea2453b35d08aca02aef74",
          "sha256": "4f655c23fc9d54a7bb49782505a1bc45258decd0e7596363e1a47acb673b1eba",
          "sha1": "024cc21eb6e00107f6e7d5495a3ce9b55e04e450",
          "md5": "e578f963a96e4da3edeb8db94adb7821"
        }
      ]
    }
  ]
}
