{
  "formatVersion": "1.1",
  "component": {
    "url": "../../kotlin-compose-schema/0.12.0/kotlin-compose-schema-0.12.0.module",
    "group": "ai.factoredui",
    "module": "kotlin-compose-schema",
    "version": "0.12.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14"
    }
  },
  "variants": [
    {
      "name": "linuxX64ApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "linux_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.21"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.11.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-datetime",
          "version": {
            "requires": "0.7.1"
          }
        }
      ],
      "files": [
        {
          "name": "kotlin-compose-schema-linuxX64Main-0.12.0.klib",
          "url": "kotlin-compose-schema-linuxx64-0.12.0.klib",
          "size": 105970,
          "sha512": "6398687ae0f90d42b592ed7bacf70b07559cbda8c366d37960e1fbe9e7e3bb56affb4eae179ab15923ebe48eb838c95210eae0c0053d3ca9019c721d08f1fd4a",
          "sha256": "091629ffb4035bf962a68030dd0a51692aac3bf79c1d8867aadfcd717a520d73",
          "sha1": "ec2f2f701b5457f6a09fb8f9bb982dab450836c0",
          "md5": "04010d51602e69c2e3f8460b697c385b"
        }
      ]
    },
    {
      "name": "linuxX64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "linux_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "files": [
        {
          "name": "kotlin-compose-schema-linuxx64-0.12.0-sources.jar",
          "url": "kotlin-compose-schema-linuxx64-0.12.0-sources.jar",
          "size": 10431,
          "sha512": "65497e9f1b79ded1419239f5902e28854ab3911ec69f60d29143f61cbdece8bfe137295fa7f9bf73835797104001fc6b301228884cfcbf8bf51b2cdacda2bdfa",
          "sha256": "344aa06e2ec4a83d38a5a3b0ea40fe49f609a2c7e481f9651f5a14ae7e521289",
          "sha1": "9d2e4d772023580bd93ee3dd083caec090d0dec2",
          "md5": "6167dbe880a11516b725f687354df2b1"
        }
      ]
    }
  ]
}
