{
  "formatVersion": "1.1",
  "component": {
    "url": "../../kotlin-compose-schema/0.13.1/kotlin-compose-schema-0.13.1.module",
    "group": "ai.factoredui",
    "module": "kotlin-compose-schema",
    "version": "0.13.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14"
    }
  },
  "variants": [
    {
      "name": "releaseApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.21"
          }
        }
      ],
      "files": [
        {
          "name": "kotlin-compose-schema-release.aar",
          "url": "kotlin-compose-schema-android-0.13.1.aar",
          "size": 139990,
          "sha512": "c35b7f1d193e3bc2947eb8fc0e46fc41f87063f178d791a1a4d3c2c70eef990931928faf3cd5b0a86948602e9025ad331e548d89a2824acfe3c754af14ee641a",
          "sha256": "a402429ad8ff9bc9200823eaa0ec02768fc79c22132ff92bc3e82b643fa63c79",
          "sha1": "cdf300a30b36159d09502d48734e61ab4f1c8625",
          "md5": "2252e130706bdd31906591de98d2d862"
        }
      ]
    },
    {
      "name": "releaseRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.21"
          },
          "excludes": [
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-annotations-common"
            }
          ]
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.11.0"
          },
          "excludes": [
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-annotations-common"
            }
          ]
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-datetime",
          "version": {
            "requires": "0.7.1"
          },
          "excludes": [
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-annotations-common"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "kotlin-compose-schema-release.aar",
          "url": "kotlin-compose-schema-android-0.13.1.aar",
          "size": 139990,
          "sha512": "c35b7f1d193e3bc2947eb8fc0e46fc41f87063f178d791a1a4d3c2c70eef990931928faf3cd5b0a86948602e9025ad331e548d89a2824acfe3c754af14ee641a",
          "sha256": "a402429ad8ff9bc9200823eaa0ec02768fc79c22132ff92bc3e82b643fa63c79",
          "sha1": "cdf300a30b36159d09502d48734e61ab4f1c8625",
          "md5": "2252e130706bdd31906591de98d2d862"
        }
      ]
    },
    {
      "name": "releaseSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "android",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "files": [
        {
          "name": "kotlin-compose-schema-android-0.13.1-sources.jar",
          "url": "kotlin-compose-schema-android-0.13.1-sources.jar",
          "size": 10453,
          "sha512": "3fbb28a198d7de5ca01ed32f9501092fac1b6af51a9b0098c21108f5a5c0608e92c3bd97c5b73aba71a264a999817927b4ebb13dae14cfabad9be095964ba1cc",
          "sha256": "a0966f1f9d3e6583b8dcf8432881a0902108e4151fa59a8d8b62084378017fe3",
          "sha1": "5013c85243b90636719264022c566aa65725c334",
          "md5": "f46850ca8f5deae24a974bcf4cc1901b"
        }
      ]
    }
  ]
}
