{
  "formatVersion": "1.1",
  "component": {
    "url": "../../kotlin-compose/0.6.0/kotlin-compose-0.6.0.module",
    "group": "ai.factoredui",
    "module": "kotlin-compose",
    "version": "0.6.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.10.2"
    }
  },
  "variants": [
    {
      "name": "wasmJsApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "wasm",
        "org.jetbrains.kotlin.wasm.target": "js"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.21"
          }
        }
      ],
      "files": [
        {
          "name": "kotlin-compose-wasm-js-0.6.0.klib",
          "url": "kotlin-compose-wasm-js-0.6.0.klib",
          "size": 336814,
          "sha512": "8862ccde4acf2702445a2b7d1d9e5122951c32a2951525fe5c4decd5cc37ead95be7971ebea755126eb8fc8a5abc7f7182374455f6c8f11a2142f7b890a14c08",
          "sha256": "fc3f59725329ff4baa8ce6213dcbdfeb4ce245cafb3d5488bbf42b9beba5a096",
          "sha1": "7a3eb4fb6222b77c95435606a920685fe197836f",
          "md5": "caf68fca935d4a2eef639a4d1c552c9d"
        }
      ]
    },
    {
      "name": "wasmJsRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.platform.type": "wasm",
        "org.jetbrains.kotlin.wasm.target": "js"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.21"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-js",
          "version": {
            "requires": "3.0.3"
          }
        },
        {
          "group": "org.jetbrains.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "1.7.3"
          }
        },
        {
          "group": "org.jetbrains.compose.foundation",
          "module": "foundation",
          "version": {
            "requires": "1.7.3"
          }
        },
        {
          "group": "org.jetbrains.compose.material3",
          "module": "material3",
          "version": {
            "requires": "1.7.3"
          }
        },
        {
          "group": "org.jetbrains.compose.ui",
          "module": "ui",
          "version": {
            "requires": "1.7.3"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.7.3"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-datetime",
          "version": {
            "requires": "0.6.1"
          }
        },
        {
          "group": "io.coil-kt.coil3",
          "module": "coil-compose",
          "version": {
            "requires": "3.0.4"
          }
        },
        {
          "group": "io.coil-kt.coil3",
          "module": "coil-network-ktor3",
          "version": {
            "requires": "3.0.4"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-core",
          "version": {
            "requires": "3.0.3"
          }
        }
      ],
      "files": [
        {
          "name": "kotlin-compose-wasm-js-0.6.0.klib",
          "url": "kotlin-compose-wasm-js-0.6.0.klib",
          "size": 336814,
          "sha512": "8862ccde4acf2702445a2b7d1d9e5122951c32a2951525fe5c4decd5cc37ead95be7971ebea755126eb8fc8a5abc7f7182374455f6c8f11a2142f7b890a14c08",
          "sha256": "fc3f59725329ff4baa8ce6213dcbdfeb4ce245cafb3d5488bbf42b9beba5a096",
          "sha1": "7a3eb4fb6222b77c95435606a920685fe197836f",
          "md5": "caf68fca935d4a2eef639a4d1c552c9d"
        }
      ]
    },
    {
      "name": "wasmJsSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.platform.type": "wasm",
        "org.jetbrains.kotlin.wasm.target": "js"
      },
      "files": [
        {
          "name": "kotlin-compose-wasm-js-0.6.0-sources.jar",
          "url": "kotlin-compose-wasm-js-0.6.0-sources.jar",
          "size": 52362,
          "sha512": "c1cbf4a099e4b13a70a8527a204da81babbb547390384ca7b11294993ef7f8cfb328a1381025cdc57c7e254aeceddb51b0a332eef2b87b9b41c2cf3fce3a7d58",
          "sha256": "ee087cc593b3887b68ae480bcedda900c9c7c6fc9b15c6720f7bb70016dfd252",
          "sha1": "5418883fcdcfb4401291762562b719de3872f80c",
          "md5": "057d03e694e41f5cbec290d8affd7851"
        }
      ]
    },
    {
      "name": "wasmJsResourcesElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.libraryelements": "kotlin-multiplatformresourcesjs",
        "org.gradle.usage": "kotlin-multiplatformresourcesjs",
        "org.jetbrains.kotlin.platform.type": "wasm",
        "org.jetbrains.kotlin.wasm.target": "js"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.21"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-js",
          "version": {
            "requires": "3.0.3"
          }
        },
        {
          "group": "org.jetbrains.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "1.7.3"
          }
        },
        {
          "group": "org.jetbrains.compose.foundation",
          "module": "foundation",
          "version": {
            "requires": "1.7.3"
          }
        },
        {
          "group": "org.jetbrains.compose.material3",
          "module": "material3",
          "version": {
            "requires": "1.7.3"
          }
        },
        {
          "group": "org.jetbrains.compose.ui",
          "module": "ui",
          "version": {
            "requires": "1.7.3"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.7.3"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-datetime",
          "version": {
            "requires": "0.6.1"
          }
        },
        {
          "group": "io.coil-kt.coil3",
          "module": "coil-compose",
          "version": {
            "requires": "3.0.4"
          }
        },
        {
          "group": "io.coil-kt.coil3",
          "module": "coil-network-ktor3",
          "version": {
            "requires": "3.0.4"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-core",
          "version": {
            "requires": "3.0.3"
          }
        }
      ],
      "files": [
        {
          "name": "kotlin-compose-0.6.0.kotlin_resources.zip",
          "url": "kotlin-compose-wasm-js-0.6.0-kotlin_resources.kotlin_resources.zip",
          "size": 344,
          "sha512": "5190e727f69e2cff33fdccedf77185dc4b65cc6e9bb72388e5f2af447b559e99ea734254dda08a45dd5dca27df05ab394b785e1e009f68712dab5fd524ced8a9",
          "sha256": "ad9b18bd1a634d4db363073c325286c164385bb78e8931f026c82a3227b42021",
          "sha1": "69de672485becd351d125da1321f8755adc16724",
          "md5": "4dbdd01e518ae4861514e5c328bb7bd0"
        }
      ]
    }
  ]
}
