{
  "formatVersion": "1.1",
  "component": {
    "url": "../../kotlin-compose-schema/0.17.1/kotlin-compose-schema-0.17.1.module",
    "group": "ai.factoredui",
    "module": "kotlin-compose-schema",
    "version": "0.17.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14"
    }
  },
  "variants": [
    {
      "name": "iosSimulatorArm64ApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.21"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.11.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-datetime",
          "version": {
            "requires": "0.7.1"
          }
        }
      ],
      "files": [
        {
          "name": "kotlin-compose-schema-iosSimulatorArm64Main-0.17.1.klib",
          "url": "kotlin-compose-schema-iossimulatorarm64-0.17.1.klib",
          "size": 112110,
          "sha512": "a72d73ebff8fa5057a1762c8c6d034e670710c66b1a443f36f61c9797985b55ef926827c47985b6b453073e224d22364dd6763b453806e16d6671eef7aa50c74",
          "sha256": "5764a04a2b2eae33edd48154748b56e7b9f0774a4e4172ebf6c901a42cac4844",
          "sha1": "673c1e491b9533b19eeb369d82d824bcac67bdd4",
          "md5": "ee58c1c77cc274d1b9cd87ef6a2794f4"
        }
      ]
    },
    {
      "name": "iosSimulatorArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "files": [
        {
          "name": "kotlin-compose-schema-iossimulatorarm64-0.17.1-sources.jar",
          "url": "kotlin-compose-schema-iossimulatorarm64-0.17.1-sources.jar",
          "size": 11046,
          "sha512": "cae4c08ab3f9a8344d54c7e0e4fa9269ea8da377662bc4064d80a2cd79f09fee86747b36290041c447b7ad05a090b3b7bcfbbd8da350247fd6ee8dcdd79d58e9",
          "sha256": "ed1a6fb4bff7ef3d57fa32ea9d4747fa020577883dfc09c1f4431e7d0ca4534d",
          "sha1": "aef338a946cb47d02cec2a29e4662c43516a06c2",
          "md5": "96bcd168f6e86923ea03d2264bc834ae"
        }
      ]
    },
    {
      "name": "iosSimulatorArm64MetadataElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.21"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.11.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-datetime",
          "version": {
            "requires": "0.7.1"
          }
        }
      ],
      "files": [
        {
          "name": "kotlin-compose-schema-iossimulatorarm64-0.17.1-metadata.jar",
          "url": "kotlin-compose-schema-iossimulatorarm64-0.17.1-metadata.jar",
          "size": 261,
          "sha512": "63ce8385ec6aa3d2956c827e98a745f37df334af57096ec24804b3fb07c359ac4b8fcfdbf1be019c19c77c0613f47a99b974a77a356bbf1188ead07166db2dff",
          "sha256": "bd2457976f9f9417407c2bf477db23a283016d1462808bfdd76ab4652401fdcf",
          "sha1": "beed38b374acfea949b62adce384381a4c734685",
          "md5": "a11cde1fb196edf3726531d14ad021e9"
        }
      ]
    }
  ]
}
