{
  "formatVersion": "1.1",
  "component": {
    "url": "../../kotlin-compose/0.7.0/kotlin-compose-0.7.0.module",
    "group": "ai.factoredui",
    "module": "kotlin-compose",
    "version": "0.7.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14"
    }
  },
  "variants": [
    {
      "name": "wasmJsApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "wasm",
        "org.jetbrains.kotlin.wasm.target": "js"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.21"
          }
        }
      ],
      "files": [
        {
          "name": "kotlin-compose-wasm-js-0.7.0.klib",
          "url": "kotlin-compose-wasm-js-0.7.0.klib",
          "size": 320492,
          "sha512": "a6decaf602615fbfcf5cf813d55bccb5ccbc2efa9f77e2a9da7c0545764882b92cd4b605495a22e84c21859c8b6238222819bf9aebfab2801300147fffea44ad",
          "sha256": "d0a694c1812e640494b8bdb3c1937d5e5014c3f6dd24567daddc7f647dd5bd5d",
          "sha1": "334c738f22d762392f6162abec0d46dfe1472bf9",
          "md5": "913a6df1feeaac1478d1492be84a97dc"
        }
      ]
    },
    {
      "name": "wasmJsRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.platform.type": "wasm",
        "org.jetbrains.kotlin.wasm.target": "js"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.21"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-js",
          "version": {
            "requires": "3.2.0"
          }
        },
        {
          "group": "org.jetbrains.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "1.10.3"
          }
        },
        {
          "group": "org.jetbrains.compose.foundation",
          "module": "foundation",
          "version": {
            "requires": "1.10.3"
          }
        },
        {
          "group": "org.jetbrains.compose.material3",
          "module": "material3",
          "version": {
            "requires": "1.9.0-beta03"
          }
        },
        {
          "group": "org.jetbrains.compose.ui",
          "module": "ui",
          "version": {
            "requires": "1.10.3"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.11.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.10.2"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-datetime",
          "version": {
            "requires": "0.7.1"
          }
        },
        {
          "group": "io.coil-kt.coil3",
          "module": "coil-compose",
          "version": {
            "requires": "3.2.0"
          }
        },
        {
          "group": "io.coil-kt.coil3",
          "module": "coil-network-ktor3",
          "version": {
            "requires": "3.2.0"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-core",
          "version": {
            "requires": "3.2.0"
          }
        }
      ],
      "files": [
        {
          "name": "kotlin-compose-wasm-js-0.7.0.klib",
          "url": "kotlin-compose-wasm-js-0.7.0.klib",
          "size": 320492,
          "sha512": "a6decaf602615fbfcf5cf813d55bccb5ccbc2efa9f77e2a9da7c0545764882b92cd4b605495a22e84c21859c8b6238222819bf9aebfab2801300147fffea44ad",
          "sha256": "d0a694c1812e640494b8bdb3c1937d5e5014c3f6dd24567daddc7f647dd5bd5d",
          "sha1": "334c738f22d762392f6162abec0d46dfe1472bf9",
          "md5": "913a6df1feeaac1478d1492be84a97dc"
        }
      ]
    },
    {
      "name": "wasmJsSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.platform.type": "wasm",
        "org.jetbrains.kotlin.wasm.target": "js"
      },
      "files": [
        {
          "name": "kotlin-compose-wasm-js-0.7.0-sources.jar",
          "url": "kotlin-compose-wasm-js-0.7.0-sources.jar",
          "size": 52357,
          "sha512": "9c92a69ceeff1b9fdd367713b5bb248f03664ca1d15f4ba0c067f7c40682a505ba767a6ca8667aecc39d88a74fa1975c8d0e6342379d9183ba19d2c96f21fd33",
          "sha256": "99d482ce5680db1e25e8dc8f5697ef31a71e7171c8cac058d0ba2e3d2ec053dd",
          "sha1": "c12c0764535a0c111514dceac364045fa2a02c6b",
          "md5": "30217e5be8c03b1abc5af6323a86eea9"
        }
      ]
    },
    {
      "name": "wasmJsResourcesElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.libraryelements": "kotlin-multiplatformresourcesjs",
        "org.gradle.usage": "kotlin-multiplatformresourcesjs",
        "org.jetbrains.kotlin.platform.type": "wasm",
        "org.jetbrains.kotlin.wasm.target": "js"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.21"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-js",
          "version": {
            "requires": "3.2.0"
          }
        },
        {
          "group": "org.jetbrains.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "1.10.3"
          }
        },
        {
          "group": "org.jetbrains.compose.foundation",
          "module": "foundation",
          "version": {
            "requires": "1.10.3"
          }
        },
        {
          "group": "org.jetbrains.compose.material3",
          "module": "material3",
          "version": {
            "requires": "1.9.0-beta03"
          }
        },
        {
          "group": "org.jetbrains.compose.ui",
          "module": "ui",
          "version": {
            "requires": "1.10.3"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.11.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.10.2"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-datetime",
          "version": {
            "requires": "0.7.1"
          }
        },
        {
          "group": "io.coil-kt.coil3",
          "module": "coil-compose",
          "version": {
            "requires": "3.2.0"
          }
        },
        {
          "group": "io.coil-kt.coil3",
          "module": "coil-network-ktor3",
          "version": {
            "requires": "3.2.0"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-core",
          "version": {
            "requires": "3.2.0"
          }
        }
      ],
      "files": [
        {
          "name": "kotlin-compose-0.7.0.kotlin_resources.zip",
          "url": "kotlin-compose-wasm-js-0.7.0-kotlin_resources.kotlin_resources.zip",
          "size": 344,
          "sha512": "b66a6d99a55969858b635f50f6e03094b74548f17288be3206ce683ce58298fc49998df876fe0a9622f7aa1096baaa8acb3e0326ee8667b789630b389f7f014e",
          "sha256": "5d2cea51d84e6430ce8aeab3a8f02def556e17c9be671d8bb733bfc80f115b74",
          "sha1": "c99dcad5d0387a536cc1c42541f7a4c2862e5ad9",
          "md5": "9056f0ef6fc75ee6717610d745688fb1"
        }
      ]
    }
  ]
}
