{
  "formatVersion": "1.1",
  "component": {
    "url": "../../kotlin-compose/0.17.2/kotlin-compose-0.17.2.module",
    "group": "ai.factoredui",
    "module": "kotlin-compose",
    "version": "0.17.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14"
    }
  },
  "variants": [
    {
      "name": "desktopApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "ai.factoredui",
          "module": "kotlin-compose-schema",
          "version": {
            "requires": "0.17.2"
          }
        },
        {
          "group": "ai.factoredui",
          "module": "kotlin-compose-capture",
          "version": {
            "requires": "0.17.2"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.21"
          }
        }
      ],
      "files": [
        {
          "name": "kotlin-compose-desktop-0.17.2.jar",
          "url": "kotlin-compose-desktop-0.17.2.jar",
          "size": 620107,
          "sha512": "a718196e86775a94897bc3841b8661f4797071989ee94fb23a2bb1f706987393fdbe579883c248a6cd98ff27b08cd01760fb716fd4961807433d6e6239220b32",
          "sha256": "ee31938d8a4344703290ea4761e5ba186517c6fe1f61d5ea9702784e34ee90e9",
          "sha1": "ae84608f2942040809da32ca2633a4f4dd1678c4",
          "md5": "862c7608ae4f4e418e0fc4ebfa053b99"
        }
      ]
    },
    {
      "name": "desktopRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "ai.factoredui",
          "module": "kotlin-compose-schema",
          "version": {
            "requires": "0.17.2"
          }
        },
        {
          "group": "ai.factoredui",
          "module": "kotlin-compose-capture",
          "version": {
            "requires": "0.17.2"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.21"
          }
        },
        {
          "group": "org.jetbrains.compose.desktop",
          "module": "desktop",
          "version": {
            "requires": "1.10.3"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-okhttp",
          "version": {
            "requires": "3.2.4"
          }
        },
        {
          "group": "org.jetbrains.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "1.10.3"
          }
        },
        {
          "group": "org.jetbrains.compose.foundation",
          "module": "foundation",
          "version": {
            "requires": "1.10.3"
          }
        },
        {
          "group": "org.jetbrains.compose.material3",
          "module": "material3",
          "version": {
            "requires": "1.9.0-beta03"
          }
        },
        {
          "group": "org.jetbrains.compose.ui",
          "module": "ui",
          "version": {
            "requires": "1.10.3"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.11.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.10.2"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-datetime",
          "version": {
            "requires": "0.7.1"
          }
        },
        {
          "group": "io.coil-kt.coil3",
          "module": "coil-compose",
          "version": {
            "requires": "3.2.0"
          }
        },
        {
          "group": "io.coil-kt.coil3",
          "module": "coil-network-ktor3",
          "version": {
            "requires": "3.2.0"
          }
        },
        {
          "group": "io.coil-kt.coil3",
          "module": "coil-svg",
          "version": {
            "requires": "3.2.0"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-core",
          "version": {
            "requires": "3.2.4"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-content-negotiation",
          "version": {
            "requires": "3.2.4"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-serialization-kotlinx-json",
          "version": {
            "requires": "3.2.4"
          }
        }
      ],
      "files": [
        {
          "name": "kotlin-compose-desktop-0.17.2.jar",
          "url": "kotlin-compose-desktop-0.17.2.jar",
          "size": 620107,
          "sha512": "a718196e86775a94897bc3841b8661f4797071989ee94fb23a2bb1f706987393fdbe579883c248a6cd98ff27b08cd01760fb716fd4961807433d6e6239220b32",
          "sha256": "ee31938d8a4344703290ea4761e5ba186517c6fe1f61d5ea9702784e34ee90e9",
          "sha1": "ae84608f2942040809da32ca2633a4f4dd1678c4",
          "md5": "862c7608ae4f4e418e0fc4ebfa053b99"
        }
      ]
    },
    {
      "name": "desktopSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "kotlin-compose-desktop-0.17.2-sources.jar",
          "url": "kotlin-compose-desktop-0.17.2-sources.jar",
          "size": 73690,
          "sha512": "40d1d7d97d993e0e0602a2c8b9cec2d9cee948c700580ad7d6930f5248283f0d03e66b1dd705c6a403c3c4ca0952faff799a1f3be790bf1fb2c62b403d30a36f",
          "sha256": "a6581afa2f195cc654efe95d6b10e1bfd5cf251b249b69ad44ade3605b152b2e",
          "sha1": "452d06a9d9079ce0cf905b7fd3c9a066d942a7d7",
          "md5": "d20c716bf696ac160d44337f88b5cb76"
        }
      ]
    }
  ]
}
