{
  "formatVersion": "1.1",
  "component": {
    "url": "../../kotlin-compose-schema/0.20.6/kotlin-compose-schema-0.20.6.module",
    "group": "ai.factoredui",
    "module": "kotlin-compose-schema",
    "version": "0.20.6",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14"
    }
  },
  "variants": [
    {
      "name": "iosArm64ApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.21"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.11.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-datetime",
          "version": {
            "requires": "0.7.1"
          }
        }
      ],
      "files": [
        {
          "name": "kotlin-compose-schema-iosArm64Main-0.20.6.klib",
          "url": "kotlin-compose-schema-iosarm64-0.20.6.klib",
          "size": 140276,
          "sha512": "29b15d9889b1533f0a363b0732e49cc0a524b0150be81801b7e7ca52abfb603800ea6910699470ba7b2be55602f1e6e1b2dc7a8b47ea96765878e6788f57bb29",
          "sha256": "233329d06bd19dbdd934f0c2b46edb64f18aad069edf1906c68816566bce45e1",
          "sha1": "32c3947fdd474c5627f2aafdf36ac8be87aba786",
          "md5": "a886adee3f15a05e37b547a763b8d48c"
        }
      ]
    },
    {
      "name": "iosArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "files": [
        {
          "name": "kotlin-compose-schema-iosarm64-0.20.6-sources.jar",
          "url": "kotlin-compose-schema-iosarm64-0.20.6-sources.jar",
          "size": 12896,
          "sha512": "1f8eec231bb59f13ab0a1e2aac85f9f8e201081805972512f2f28ea743d54f2d8fc6bfdc9dd88970f7c8d64546cc78401c5c6f316204cbf20b1ea6368a8ef793",
          "sha256": "ca7b1c8612282eeb2c1391b6f3da13cfbcc0c44c72c0e6ca6193c844db9a5fdd",
          "sha1": "3dde30d0160d2f7d0843c764314d54909d01f06d",
          "md5": "d552ea9172056e2e5e0d8bf0aa4f36be"
        }
      ]
    },
    {
      "name": "iosArm64MetadataElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.21"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.11.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-datetime",
          "version": {
            "requires": "0.7.1"
          }
        }
      ],
      "files": [
        {
          "name": "kotlin-compose-schema-iosarm64-0.20.6-metadata.jar",
          "url": "kotlin-compose-schema-iosarm64-0.20.6-metadata.jar",
          "size": 261,
          "sha512": "105e228f9a01f99fc21de96d9aaaf00862484c21ce34ade4cbf1cc4006ad989a6f3777a9e2984a7c141b976973ad3b685ec0f1469ce55b5400a3fadbf2754bf1",
          "sha256": "c0f3f7f94906042a19ec556dd6a723388c39db24c522961aca30e5891100945c",
          "sha1": "f62c672ef811fbaa15dd9090182656ae2f1fe6bf",
          "md5": "781cf80f94c151639a76664a907c5238"
        }
      ]
    }
  ]
}
