{
  "formatVersion": "1.1",
  "component": {
    "url": "../../kotlin-compose-schema/0.9.0/kotlin-compose-schema-0.9.0.module",
    "group": "ai.factoredui",
    "module": "kotlin-compose-schema",
    "version": "0.9.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14"
    }
  },
  "variants": [
    {
      "name": "linuxX64ApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "linux_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.21"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.11.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-datetime",
          "version": {
            "requires": "0.7.1"
          }
        }
      ],
      "files": [
        {
          "name": "kotlin-compose-schema-linuxX64Main-0.9.0.klib",
          "url": "kotlin-compose-schema-linuxx64-0.9.0.klib",
          "size": 95703,
          "sha512": "3450c6ba6ee8b490daf292d3e38578c7a613a8dfccb5d142cb08763fcd7e150b5a8cd0a87d2d5ac87d6ac5ad54c4666acdf5ac0778b4f7431faad7f588e03217",
          "sha256": "0e67d3fdfe94c263f67910de5b5227a7d5a8550f96e683a9e6760834e9c38582",
          "sha1": "bd84f84416f2ddc02a3104fddb0da9482fba27f7",
          "md5": "25b9618e449478d6898326b16589c40b"
        }
      ]
    },
    {
      "name": "linuxX64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "linux_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "files": [
        {
          "name": "kotlin-compose-schema-linuxx64-0.9.0-sources.jar",
          "url": "kotlin-compose-schema-linuxx64-0.9.0-sources.jar",
          "size": 9238,
          "sha512": "4affb9330a226168437bcad22a19f8f492f87332b9c51c96580c010ee95755cf8883c32b4ce9371c7e3c9c54c909a2e2a17dece57bd3fe38fb1c6e7adcfe5637",
          "sha256": "e78bf3fee0afef260d2b7b9d2508411a3f75322d03950f74b61a4c43921cf425",
          "sha1": "cf4b1509d3d93b4bfbb46c0419551f4cbc1df5ad",
          "md5": "185746942c49e1f311e19e8f75d18e3e"
        }
      ]
    }
  ]
}
