{
  "formatVersion": "1.1",
  "component": {
    "url": "../../kotlin-compose/0.4.1/kotlin-compose-0.4.1.module",
    "group": "ai.factoredui",
    "module": "kotlin-compose",
    "version": "0.4.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.10.2"
    }
  },
  "variants": [
    {
      "name": "desktopApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.21"
          }
        }
      ],
      "files": [
        {
          "name": "kotlin-compose-desktop-0.4.1.jar",
          "url": "kotlin-compose-desktop-0.4.1.jar",
          "size": 378243,
          "sha512": "94b15cb384683b31d434375e9bc52cc057666ba2bc72e864347ca2b4e0e97f803a265860bdd49dd98cc8169302d953793426a41b8eb2aa1d970272f6677fab5c",
          "sha256": "edd81aa57bd11387ea422fdc4984c7ee750a08d1b96a496e52d33fdd8131e1fe",
          "sha1": "e1c0890729a643b0e431d165ec36c4f9876b3f15",
          "md5": "04f0fe90a13ed3a297426a254cde42f9"
        }
      ]
    },
    {
      "name": "desktopRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.21"
          }
        },
        {
          "group": "org.jetbrains.compose.desktop",
          "module": "desktop-jvm-linux-x64",
          "version": {
            "requires": "1.7.3"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-okhttp",
          "version": {
            "requires": "3.0.3"
          }
        },
        {
          "group": "org.jetbrains.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "1.7.3"
          }
        },
        {
          "group": "org.jetbrains.compose.foundation",
          "module": "foundation",
          "version": {
            "requires": "1.7.3"
          }
        },
        {
          "group": "org.jetbrains.compose.material3",
          "module": "material3",
          "version": {
            "requires": "1.7.3"
          }
        },
        {
          "group": "org.jetbrains.compose.ui",
          "module": "ui",
          "version": {
            "requires": "1.7.3"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.7.3"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-datetime",
          "version": {
            "requires": "0.6.1"
          }
        },
        {
          "group": "io.coil-kt.coil3",
          "module": "coil-compose",
          "version": {
            "requires": "3.0.4"
          }
        },
        {
          "group": "io.coil-kt.coil3",
          "module": "coil-network-ktor3",
          "version": {
            "requires": "3.0.4"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-core",
          "version": {
            "requires": "3.0.3"
          }
        }
      ],
      "files": [
        {
          "name": "kotlin-compose-desktop-0.4.1.jar",
          "url": "kotlin-compose-desktop-0.4.1.jar",
          "size": 378243,
          "sha512": "94b15cb384683b31d434375e9bc52cc057666ba2bc72e864347ca2b4e0e97f803a265860bdd49dd98cc8169302d953793426a41b8eb2aa1d970272f6677fab5c",
          "sha256": "edd81aa57bd11387ea422fdc4984c7ee750a08d1b96a496e52d33fdd8131e1fe",
          "sha1": "e1c0890729a643b0e431d165ec36c4f9876b3f15",
          "md5": "04f0fe90a13ed3a297426a254cde42f9"
        }
      ]
    },
    {
      "name": "desktopSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "kotlin-compose-desktop-0.4.1-sources.jar",
          "url": "kotlin-compose-desktop-0.4.1-sources.jar",
          "size": 41354,
          "sha512": "7326ec915e3dff4f0772b4bf74bd988615d829426d0967c17d350e143415bc1754e7d0f23a886354f55591916a528140bd5f16ec1a06d8fb51ecd8876718a2a4",
          "sha256": "54372791e1aa294bb08a9908a46c0e377dad5d0f100644c9088b4a8926997547",
          "sha1": "56b6f140498070c88f7830d1728985ad61186b04",
          "md5": "9da21adfeae190ded9a418291bde56a7"
        }
      ]
    }
  ]
}
