{
  "formatVersion": "1.1",
  "component": {
    "url": "../../kotlin-compose/0.20.7/kotlin-compose-0.20.7.module",
    "group": "ai.factoredui",
    "module": "kotlin-compose",
    "version": "0.20.7",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14"
    }
  },
  "variants": [
    {
      "name": "releaseApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "ai.factoredui",
          "module": "kotlin-compose-schema",
          "version": {
            "requires": "0.20.7"
          }
        },
        {
          "group": "ai.factoredui",
          "module": "kotlin-compose-capture",
          "version": {
            "requires": "0.20.7"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.21"
          }
        }
      ],
      "files": [
        {
          "name": "kotlin-compose-release.aar",
          "url": "kotlin-compose-android-0.20.7.aar",
          "size": 716580,
          "sha512": "68a31142fde30ab25c772c00d6dae3258bbc094d07b9eaa833b7e1b11aab142fb1d60cf7b75c8ce9d116e4f06e8f5212a486ce08c71e798fd33c61ec323e1f94",
          "sha256": "c82e9a2c63f9aa525756cf67fd89b8c27a0fb2feb203f5dc16157fd6b71e6290",
          "sha1": "a58f29c5c267241a5be558406dfa473287c9ce22",
          "md5": "6cc0967ba646d8c01be4794dfec37c0a"
        }
      ]
    },
    {
      "name": "releaseRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "androidx.activity",
          "module": "activity-compose",
          "version": {
            "requires": "1.9.3"
          },
          "excludes": [
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-annotations-common"
            }
          ]
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-okhttp",
          "version": {
            "requires": "3.2.4"
          },
          "excludes": [
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-annotations-common"
            }
          ]
        },
        {
          "group": "ai.factoredui",
          "module": "kotlin-compose-schema",
          "version": {
            "requires": "0.20.7"
          },
          "excludes": [
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-annotations-common"
            }
          ]
        },
        {
          "group": "ai.factoredui",
          "module": "kotlin-compose-capture",
          "version": {
            "requires": "0.20.7"
          },
          "excludes": [
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-annotations-common"
            }
          ]
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.21"
          },
          "excludes": [
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-annotations-common"
            }
          ]
        },
        {
          "group": "org.jetbrains.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "1.10.3"
          },
          "excludes": [
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-annotations-common"
            }
          ]
        },
        {
          "group": "org.jetbrains.compose.foundation",
          "module": "foundation",
          "version": {
            "requires": "1.10.3"
          },
          "excludes": [
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-annotations-common"
            }
          ]
        },
        {
          "group": "org.jetbrains.compose.material3",
          "module": "material3",
          "version": {
            "requires": "1.9.0-beta03"
          },
          "excludes": [
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-annotations-common"
            }
          ]
        },
        {
          "group": "org.jetbrains.compose.ui",
          "module": "ui",
          "version": {
            "requires": "1.10.3"
          },
          "excludes": [
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-annotations-common"
            }
          ]
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.11.0"
          },
          "excludes": [
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-annotations-common"
            }
          ]
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.10.2"
          },
          "excludes": [
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-annotations-common"
            }
          ]
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-datetime",
          "version": {
            "requires": "0.7.1"
          },
          "excludes": [
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-annotations-common"
            }
          ]
        },
        {
          "group": "io.coil-kt.coil3",
          "module": "coil-compose",
          "version": {
            "requires": "3.2.0"
          },
          "excludes": [
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-annotations-common"
            }
          ]
        },
        {
          "group": "io.coil-kt.coil3",
          "module": "coil-network-ktor3",
          "version": {
            "requires": "3.2.0"
          },
          "excludes": [
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-annotations-common"
            }
          ]
        },
        {
          "group": "io.coil-kt.coil3",
          "module": "coil-svg",
          "version": {
            "requires": "3.2.0"
          },
          "excludes": [
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-annotations-common"
            }
          ]
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-core",
          "version": {
            "requires": "3.2.4"
          },
          "excludes": [
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-annotations-common"
            }
          ]
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-content-negotiation",
          "version": {
            "requires": "3.2.4"
          },
          "excludes": [
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-annotations-common"
            }
          ]
        },
        {
          "group": "io.ktor",
          "module": "ktor-serialization-kotlinx-json",
          "version": {
            "requires": "3.2.4"
          },
          "excludes": [
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-annotations-common"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "kotlin-compose-release.aar",
          "url": "kotlin-compose-android-0.20.7.aar",
          "size": 716580,
          "sha512": "68a31142fde30ab25c772c00d6dae3258bbc094d07b9eaa833b7e1b11aab142fb1d60cf7b75c8ce9d116e4f06e8f5212a486ce08c71e798fd33c61ec323e1f94",
          "sha256": "c82e9a2c63f9aa525756cf67fd89b8c27a0fb2feb203f5dc16157fd6b71e6290",
          "sha1": "a58f29c5c267241a5be558406dfa473287c9ce22",
          "md5": "6cc0967ba646d8c01be4794dfec37c0a"
        }
      ]
    },
    {
      "name": "releaseSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "android",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "files": [
        {
          "name": "kotlin-compose-android-0.20.7-sources.jar",
          "url": "kotlin-compose-android-0.20.7-sources.jar",
          "size": 93048,
          "sha512": "5d8b9c74e0892268d1e8d14da0546e20ff1c3e3004a62279394361d7cabb9b712c994d69c52c5f44844b63f94289cd95f588642df6832ab1c9bcb4fe34b3f0ce",
          "sha256": "e9a69c6220e9f1e852652b6dcab60ecf7f9212a9cc9ebe3a723b8846ad896a48",
          "sha1": "ac52134aeaa76abc2589ae254c76355d1f94ddfd",
          "md5": "7461d166f7a03167937581e84d5aae3f"
        }
      ]
    }
  ]
}
