{
  "formatVersion": "1.1",
  "component": {
    "url": "../../kotlin-compose-schema/0.20.4/kotlin-compose-schema-0.20.4.module",
    "group": "ai.factoredui",
    "module": "kotlin-compose-schema",
    "version": "0.20.4",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14"
    }
  },
  "variants": [
    {
      "name": "iosX64ApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.21"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.11.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-datetime",
          "version": {
            "requires": "0.7.1"
          }
        }
      ],
      "files": [
        {
          "name": "kotlin-compose-schema-iosX64Main-0.20.4.klib",
          "url": "kotlin-compose-schema-iosx64-0.20.4.klib",
          "size": 140264,
          "sha512": "52135d88f3a1fb14cca523784db9dda15b350c7756dc9b607026a26f96cae2979e307b9b5481343de8d29b26fdd581d1095940f05aa1b93fa23c6a53ad20511d",
          "sha256": "fb24e72f3913f00390efb43df1cdbda24312a6cb81ffce397c6c32f4fe3121d1",
          "sha1": "e739cef0f2505a46b0c4f7b74e4637b388e3a33d",
          "md5": "94b2a2d7b5943c35041804610202a461"
        }
      ]
    },
    {
      "name": "iosX64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "files": [
        {
          "name": "kotlin-compose-schema-iosx64-0.20.4-sources.jar",
          "url": "kotlin-compose-schema-iosx64-0.20.4-sources.jar",
          "size": 12896,
          "sha512": "1f8eec231bb59f13ab0a1e2aac85f9f8e201081805972512f2f28ea743d54f2d8fc6bfdc9dd88970f7c8d64546cc78401c5c6f316204cbf20b1ea6368a8ef793",
          "sha256": "ca7b1c8612282eeb2c1391b6f3da13cfbcc0c44c72c0e6ca6193c844db9a5fdd",
          "sha1": "3dde30d0160d2f7d0843c764314d54909d01f06d",
          "md5": "d552ea9172056e2e5e0d8bf0aa4f36be"
        }
      ]
    },
    {
      "name": "iosX64MetadataElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.21"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.11.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-datetime",
          "version": {
            "requires": "0.7.1"
          }
        }
      ],
      "files": [
        {
          "name": "kotlin-compose-schema-iosx64-0.20.4-metadata.jar",
          "url": "kotlin-compose-schema-iosx64-0.20.4-metadata.jar",
          "size": 261,
          "sha512": "0d79a8d90c8b92d34db7452d8a5c98085c7257af071ab33c0c809e89b98ec17a87d2f30e151e0af11bc29b2296b4b82231658858438fefb5e018a62721c3bef1",
          "sha256": "ef14e3eb452ffc2c679875709b00887792165f3d0733f5e6bf61120ec493e70a",
          "sha1": "fe1fcb79ad1ba934351d05b3bdb59533493a35f6",
          "md5": "2135957ac860ae38973d596dc7577ac0"
        }
      ]
    }
  ]
}
