{
  "formatVersion": "1.1",
  "component": {
    "url": "../../kotlin-compose-schema/0.16.0/kotlin-compose-schema-0.16.0.module",
    "group": "ai.factoredui",
    "module": "kotlin-compose-schema",
    "version": "0.16.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14"
    }
  },
  "variants": [
    {
      "name": "linuxX64ApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "linux_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.21"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.11.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-datetime",
          "version": {
            "requires": "0.7.1"
          }
        }
      ],
      "files": [
        {
          "name": "kotlin-compose-schema-linuxX64Main-0.16.0.klib",
          "url": "kotlin-compose-schema-linuxx64-0.16.0.klib",
          "size": 121870,
          "sha512": "c5052b64fd7bed87430a6dd9578b8bbaa87b37a62dade716d8ab19e7024077805d114599427f62942c412f490eb222c5c65803f98442f492fafd236f3cf898d8",
          "sha256": "0efd574273bf8e002239229d6f5b5ebbb8221d94f4c1fe3ddd440c2d2996e193",
          "sha1": "bf0b63f6b0f94e707b3fed5b866edb3d628a693a",
          "md5": "9b06a0fee9eb5d99287bffa873196529"
        }
      ]
    },
    {
      "name": "linuxX64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "linux_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "files": [
        {
          "name": "kotlin-compose-schema-linuxx64-0.16.0-sources.jar",
          "url": "kotlin-compose-schema-linuxx64-0.16.0-sources.jar",
          "size": 12074,
          "sha512": "0f83535733491c1df2c8839f9e8cdd741d094d2fcf5c5867c4cf9aa6783766e31904264a5c2a531bc40e1042f24ec16f7cd966ade28eabb144589ed74e702521",
          "sha256": "8a0a6c9b47f3d952b1cbeb02da39bb2b5beac4745711c6131ad3ffefeb30fd2c",
          "sha1": "78b5446e4ba180e5bf8bb8332cadb6e52ddc94b6",
          "md5": "6b36540fbd346ac3266ff6fe483d0eca"
        }
      ]
    }
  ]
}
