{
  "formatVersion": "1.1",
  "component": {
    "group": "ai.factoredui",
    "module": "kotlin-server",
    "version": "0.9.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.21"
          }
        }
      ],
      "files": [
        {
          "name": "kotlin-server-0.9.0.jar",
          "url": "kotlin-server-0.9.0.jar",
          "size": 12937,
          "sha512": "b0fed8989a6f353390020a52423511e98c0dbb90968d1563f69eb080bdeb5e732c047ccd007264d7d8030e636db607d9be877545691233679e0a3cfa177e5d8e",
          "sha256": "acbb3600ce78a9c512d6e4d8efe06e467e1b7a31f460b7f82f128f69b24e7fd9",
          "sha1": "cb01b1515c1ec458f4d396dd9d92087d0fcdc2e3",
          "md5": "b51e414efc6b0e37f75f75dcd606d292"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "ai.factoredui",
          "module": "kotlin-compose-schema",
          "version": {
            "requires": "0.9.0"
          }
        },
        {
          "group": "ai.factoredui",
          "module": "kotlin-engine",
          "version": {
            "requires": "0.9.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.11.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.10.2"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-datetime",
          "version": {
            "requires": "0.7.1"
          }
        },
        {
          "group": "org.postgresql",
          "module": "postgresql",
          "version": {
            "requires": "42.7.4"
          }
        },
        {
          "group": "com.zaxxer",
          "module": "HikariCP",
          "version": {
            "requires": "5.1.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.21"
          }
        }
      ],
      "files": [
        {
          "name": "kotlin-server-0.9.0.jar",
          "url": "kotlin-server-0.9.0.jar",
          "size": 12937,
          "sha512": "b0fed8989a6f353390020a52423511e98c0dbb90968d1563f69eb080bdeb5e732c047ccd007264d7d8030e636db607d9be877545691233679e0a3cfa177e5d8e",
          "sha256": "acbb3600ce78a9c512d6e4d8efe06e467e1b7a31f460b7f82f128f69b24e7fd9",
          "sha1": "cb01b1515c1ec458f4d396dd9d92087d0fcdc2e3",
          "md5": "b51e414efc6b0e37f75f75dcd606d292"
        }
      ]
    }
  ]
}
