{
  "formatVersion": "1.1",
  "component": {
    "url": "../../kotlin-compose-schema/0.18.0/kotlin-compose-schema-0.18.0.module",
    "group": "ai.factoredui",
    "module": "kotlin-compose-schema",
    "version": "0.18.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14"
    }
  },
  "variants": [
    {
      "name": "iosArm64ApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.21"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.11.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-datetime",
          "version": {
            "requires": "0.7.1"
          }
        }
      ],
      "files": [
        {
          "name": "kotlin-compose-schema-iosArm64Main-0.18.0.klib",
          "url": "kotlin-compose-schema-iosarm64-0.18.0.klib",
          "size": 112879,
          "sha512": "2e17252b7697664759efa8189322febbe5a6cbf49986fb5cfb03a384a3c84579a4e2dc71a58301ed237d94b76794df2b5d527805beb3fb7e56f1c78779a8d710",
          "sha256": "10464db41f1490fd405f0e7b84ec7668958cb14385726812ce473bbe5f5653e5",
          "sha1": "11b459f5f44a42b2a86ca872d661c548bf9aafd8",
          "md5": "c4458c90b4092ca363a5fc4214c65127"
        }
      ]
    },
    {
      "name": "iosArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "files": [
        {
          "name": "kotlin-compose-schema-iosarm64-0.18.0-sources.jar",
          "url": "kotlin-compose-schema-iosarm64-0.18.0-sources.jar",
          "size": 11244,
          "sha512": "4f4fab68f47ca454347578d19a8686b5dc6d91880e982fd2ad2b00f30766de0e444f09cb6f94ced0f2cbd5a2748258be422665dcbc86dba910198bae1d2e7e23",
          "sha256": "98d201c5535c8ec3512dab69330bbbe3c2c19592d3a076c1131fc37ff0739ac7",
          "sha1": "f90a56dd668840053b36c36fb9bfaafba11c0ab9",
          "md5": "93f15f553e8b647097b619e1e104df7c"
        }
      ]
    },
    {
      "name": "iosArm64MetadataElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.21"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.11.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-datetime",
          "version": {
            "requires": "0.7.1"
          }
        }
      ],
      "files": [
        {
          "name": "kotlin-compose-schema-iosarm64-0.18.0-metadata.jar",
          "url": "kotlin-compose-schema-iosarm64-0.18.0-metadata.jar",
          "size": 261,
          "sha512": "230b4ae1f4171c564aa19ff9ea9b39b315a85eba933149bd5f7bc61156c306b6012b36c0d5283e127d72c64df953209c5cc52863ca4b5932a993a5a15c64b0c9",
          "sha256": "7c09187c603faf2b15e59bf7278f63d1706d53f8fd780687d094e4083d77cd5a",
          "sha1": "2aa8651b678d753cc9ac10d71ea8b9d0e1ff77bc",
          "md5": "42523b42a21cee1105aa1629a3e2fde2"
        }
      ]
    }
  ]
}
