{
  "formatVersion": "1.1",
  "component": {
    "url": "../../kotlin-compose-schema/0.9.0/kotlin-compose-schema-0.9.0.module",
    "group": "ai.factoredui",
    "module": "kotlin-compose-schema",
    "version": "0.9.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14"
    }
  },
  "variants": [
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.21"
          }
        }
      ],
      "files": [
        {
          "name": "kotlin-compose-schema-jvm-0.9.0.jar",
          "url": "kotlin-compose-schema-jvm-0.9.0.jar",
          "size": 138454,
          "sha512": "a2527d8ac5f69770ec0485fadc6127f98dd913f01241072a3679e6a371d4bdcfdd6e7ee2d232c52c7daf47fd6a1795c8dc9f3600c70db9933f46dba88478d8a1",
          "sha256": "9cb52ca70b0bc52c511260a75ed84cbcd33f8b44936dc34211d49bb626601838",
          "sha1": "f281249aacca0ea6e278730f716ee65f87d5b0d0",
          "md5": "4c6ef1c065cbe10a928b394b4ec10890"
        }
      ]
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.21"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.11.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-datetime",
          "version": {
            "requires": "0.7.1"
          }
        }
      ],
      "files": [
        {
          "name": "kotlin-compose-schema-jvm-0.9.0.jar",
          "url": "kotlin-compose-schema-jvm-0.9.0.jar",
          "size": 138454,
          "sha512": "a2527d8ac5f69770ec0485fadc6127f98dd913f01241072a3679e6a371d4bdcfdd6e7ee2d232c52c7daf47fd6a1795c8dc9f3600c70db9933f46dba88478d8a1",
          "sha256": "9cb52ca70b0bc52c511260a75ed84cbcd33f8b44936dc34211d49bb626601838",
          "sha1": "f281249aacca0ea6e278730f716ee65f87d5b0d0",
          "md5": "4c6ef1c065cbe10a928b394b4ec10890"
        }
      ]
    },
    {
      "name": "jvmSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "kotlin-compose-schema-jvm-0.9.0-sources.jar",
          "url": "kotlin-compose-schema-jvm-0.9.0-sources.jar",
          "size": 9238,
          "sha512": "4affb9330a226168437bcad22a19f8f492f87332b9c51c96580c010ee95755cf8883c32b4ce9371c7e3c9c54c909a2e2a17dece57bd3fe38fb1c6e7adcfe5637",
          "sha256": "e78bf3fee0afef260d2b7b9d2508411a3f75322d03950f74b61a4c43921cf425",
          "sha1": "cf4b1509d3d93b4bfbb46c0419551f4cbc1df5ad",
          "md5": "185746942c49e1f311e19e8f75d18e3e"
        }
      ]
    }
  ]
}
