{
  "formatVersion": "1.1",
  "component": {
    "url": "../../kotlin-compose-schema/0.20.7/kotlin-compose-schema-0.20.7.module",
    "group": "ai.factoredui",
    "module": "kotlin-compose-schema",
    "version": "0.20.7",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14"
    }
  },
  "variants": [
    {
      "name": "iosX64ApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.21"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.11.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-datetime",
          "version": {
            "requires": "0.7.1"
          }
        }
      ],
      "files": [
        {
          "name": "kotlin-compose-schema-iosX64Main-0.20.7.klib",
          "url": "kotlin-compose-schema-iosx64-0.20.7.klib",
          "size": 140264,
          "sha512": "52135d88f3a1fb14cca523784db9dda15b350c7756dc9b607026a26f96cae2979e307b9b5481343de8d29b26fdd581d1095940f05aa1b93fa23c6a53ad20511d",
          "sha256": "fb24e72f3913f00390efb43df1cdbda24312a6cb81ffce397c6c32f4fe3121d1",
          "sha1": "e739cef0f2505a46b0c4f7b74e4637b388e3a33d",
          "md5": "94b2a2d7b5943c35041804610202a461"
        }
      ]
    },
    {
      "name": "iosX64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "files": [
        {
          "name": "kotlin-compose-schema-iosx64-0.20.7-sources.jar",
          "url": "kotlin-compose-schema-iosx64-0.20.7-sources.jar",
          "size": 12896,
          "sha512": "1f8eec231bb59f13ab0a1e2aac85f9f8e201081805972512f2f28ea743d54f2d8fc6bfdc9dd88970f7c8d64546cc78401c5c6f316204cbf20b1ea6368a8ef793",
          "sha256": "ca7b1c8612282eeb2c1391b6f3da13cfbcc0c44c72c0e6ca6193c844db9a5fdd",
          "sha1": "3dde30d0160d2f7d0843c764314d54909d01f06d",
          "md5": "d552ea9172056e2e5e0d8bf0aa4f36be"
        }
      ]
    },
    {
      "name": "iosX64MetadataElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.21"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.11.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-datetime",
          "version": {
            "requires": "0.7.1"
          }
        }
      ],
      "files": [
        {
          "name": "kotlin-compose-schema-iosx64-0.20.7-metadata.jar",
          "url": "kotlin-compose-schema-iosx64-0.20.7-metadata.jar",
          "size": 261,
          "sha512": "f97199bda5aebeed2e9737b67e6c751a459af823f45cec99e830ab4cc41df92e013d96391af67c9c77aa33855062d548f8eaa4cc6dffcf26a79de7dba5fb3610",
          "sha256": "f2ef82cb4d053fc19688194f8229ed0cab55db73fd129b8b63cb5caab9f79f00",
          "sha1": "99bc08a7419384cdc01f340cf5f6b469bf64d28c",
          "md5": "f46be8be7e73d72d9f6d3ca8a986fa8c"
        }
      ]
    }
  ]
}
