{
  "formatVersion": "1.1",
  "component": {
    "url": "../../kotlin-compose/0.19.0/kotlin-compose-0.19.0.module",
    "group": "ai.factoredui",
    "module": "kotlin-compose",
    "version": "0.19.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14"
    }
  },
  "variants": [
    {
      "name": "desktopApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "ai.factoredui",
          "module": "kotlin-compose-schema",
          "version": {
            "requires": "0.19.0"
          }
        },
        {
          "group": "ai.factoredui",
          "module": "kotlin-compose-capture",
          "version": {
            "requires": "0.19.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.21"
          }
        }
      ],
      "files": [
        {
          "name": "kotlin-compose-desktop-0.19.0.jar",
          "url": "kotlin-compose-desktop-0.19.0.jar",
          "size": 643582,
          "sha512": "edd70818245c213fab0faf840289d361921999917eca51d21b1a9ba944d2f6262b92409a5711623ae768a3223bbe5f86cde01c203d2dab94054e45573c091aa3",
          "sha256": "eda7a7f0d1d4dc0455ea134c43cc285822ed1d32f3bef1bebdbea5997f10dd10",
          "sha1": "49db4e117c68d6aab08a26c3b94f76e58d40122e",
          "md5": "b10036e027c73e66ead89ec30b1fb379"
        }
      ]
    },
    {
      "name": "desktopRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "ai.factoredui",
          "module": "kotlin-compose-schema",
          "version": {
            "requires": "0.19.0"
          }
        },
        {
          "group": "ai.factoredui",
          "module": "kotlin-compose-capture",
          "version": {
            "requires": "0.19.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.21"
          }
        },
        {
          "group": "org.jetbrains.compose.desktop",
          "module": "desktop",
          "version": {
            "requires": "1.10.3"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-okhttp",
          "version": {
            "requires": "3.2.4"
          }
        },
        {
          "group": "org.jetbrains.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "1.10.3"
          }
        },
        {
          "group": "org.jetbrains.compose.foundation",
          "module": "foundation",
          "version": {
            "requires": "1.10.3"
          }
        },
        {
          "group": "org.jetbrains.compose.material3",
          "module": "material3",
          "version": {
            "requires": "1.9.0-beta03"
          }
        },
        {
          "group": "org.jetbrains.compose.ui",
          "module": "ui",
          "version": {
            "requires": "1.10.3"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.11.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.10.2"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-datetime",
          "version": {
            "requires": "0.7.1"
          }
        },
        {
          "group": "io.coil-kt.coil3",
          "module": "coil-compose",
          "version": {
            "requires": "3.2.0"
          }
        },
        {
          "group": "io.coil-kt.coil3",
          "module": "coil-network-ktor3",
          "version": {
            "requires": "3.2.0"
          }
        },
        {
          "group": "io.coil-kt.coil3",
          "module": "coil-svg",
          "version": {
            "requires": "3.2.0"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-core",
          "version": {
            "requires": "3.2.4"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-content-negotiation",
          "version": {
            "requires": "3.2.4"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-serialization-kotlinx-json",
          "version": {
            "requires": "3.2.4"
          }
        }
      ],
      "files": [
        {
          "name": "kotlin-compose-desktop-0.19.0.jar",
          "url": "kotlin-compose-desktop-0.19.0.jar",
          "size": 643582,
          "sha512": "edd70818245c213fab0faf840289d361921999917eca51d21b1a9ba944d2f6262b92409a5711623ae768a3223bbe5f86cde01c203d2dab94054e45573c091aa3",
          "sha256": "eda7a7f0d1d4dc0455ea134c43cc285822ed1d32f3bef1bebdbea5997f10dd10",
          "sha1": "49db4e117c68d6aab08a26c3b94f76e58d40122e",
          "md5": "b10036e027c73e66ead89ec30b1fb379"
        }
      ]
    },
    {
      "name": "desktopSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "kotlin-compose-desktop-0.19.0-sources.jar",
          "url": "kotlin-compose-desktop-0.19.0-sources.jar",
          "size": 79369,
          "sha512": "5057cb2a56ebaf2dec551432dd0521ffce59d02818b47dc0eda74925ce701e4dd333fd1ab49cad6e043e00ad40a97d4f963bc9864e955ee98546955b9e99673d",
          "sha256": "c0b70d45261d3f8a54e22049e73ac521ee02f65dc6b360d97d82b145389cc48b",
          "sha1": "6676d7191c65ed807109622ba4888dc073586f10",
          "md5": "2e7766dcc4aa93dc63d8a2e2d5214eef"
        }
      ]
    }
  ]
}
