{
  "formatVersion": "1.1",
  "component": {
    "group": "ai.factoredui",
    "module": "kotlin-compose-schema",
    "version": "0.11.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14"
    }
  },
  "variants": [
    {
      "name": "metadataApiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.21"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.11.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-datetime",
          "version": {
            "requires": "0.7.1"
          }
        }
      ],
      "files": [
        {
          "name": "kotlin-compose-schema-metadata-0.11.0.jar",
          "url": "kotlin-compose-schema-0.11.0.jar",
          "size": 11476,
          "sha512": "c51243bdd3abae718c5458f9821bd4bcb866a06d0b41f40eef39052f5f5d2f4a9d6157d2ed97a621dbe52a34cc7228e88bfbd671d6651330922786a7b5d7e74a",
          "sha256": "c7f4e609918be3e3e55bfdf6cf383a5bd69425937fb498903650b2022fd21205",
          "sha1": "3cc6b20199a6f0fef374eade0fdcbe6cde38f977",
          "md5": "e88ccb11d1ab3cd0e05672b416ae3170"
        }
      ]
    },
    {
      "name": "metadataSourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "files": [
        {
          "name": "kotlin-compose-schema-kotlin-0.11.0-sources.jar",
          "url": "kotlin-compose-schema-0.11.0-sources.jar",
          "size": 10330,
          "sha512": "a382fccd52fdda3052f9860ae1672b6ddec46e4a42b1e470b34abe77f572b3c7c6147c02fc717466e1728d23e9cfe6ba79773e05c07e1dd4eab4c783616c743c",
          "sha256": "56a70713b4824ac51521f5bf2b1de228e11b1f7f41ba3da94a83ac3f6562aba9",
          "sha1": "143eaa67fbf50a4e8d67677a653de0d876e21a0e",
          "md5": "2d6fb7c3de3193d0eebbfafcccb1d343"
        }
      ]
    },
    {
      "name": "releaseApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "available-at": {
        "url": "../../kotlin-compose-schema-android/0.11.0/kotlin-compose-schema-android-0.11.0.module",
        "group": "ai.factoredui",
        "module": "kotlin-compose-schema-android",
        "version": "0.11.0"
      }
    },
    {
      "name": "releaseRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "available-at": {
        "url": "../../kotlin-compose-schema-android/0.11.0/kotlin-compose-schema-android-0.11.0.module",
        "group": "ai.factoredui",
        "module": "kotlin-compose-schema-android",
        "version": "0.11.0"
      }
    },
    {
      "name": "releaseSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "android",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "available-at": {
        "url": "../../kotlin-compose-schema-android/0.11.0/kotlin-compose-schema-android-0.11.0.module",
        "group": "ai.factoredui",
        "module": "kotlin-compose-schema-android",
        "version": "0.11.0"
      }
    },
    {
      "name": "iosArm64ApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kotlin-compose-schema-iosarm64/0.11.0/kotlin-compose-schema-iosarm64-0.11.0.module",
        "group": "ai.factoredui",
        "module": "kotlin-compose-schema-iosarm64",
        "version": "0.11.0"
      }
    },
    {
      "name": "iosArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kotlin-compose-schema-iosarm64/0.11.0/kotlin-compose-schema-iosarm64-0.11.0.module",
        "group": "ai.factoredui",
        "module": "kotlin-compose-schema-iosarm64",
        "version": "0.11.0"
      }
    },
    {
      "name": "iosArm64MetadataElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kotlin-compose-schema-iosarm64/0.11.0/kotlin-compose-schema-iosarm64-0.11.0.module",
        "group": "ai.factoredui",
        "module": "kotlin-compose-schema-iosarm64",
        "version": "0.11.0"
      }
    },
    {
      "name": "iosSimulatorArm64ApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kotlin-compose-schema-iossimulatorarm64/0.11.0/kotlin-compose-schema-iossimulatorarm64-0.11.0.module",
        "group": "ai.factoredui",
        "module": "kotlin-compose-schema-iossimulatorarm64",
        "version": "0.11.0"
      }
    },
    {
      "name": "iosSimulatorArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kotlin-compose-schema-iossimulatorarm64/0.11.0/kotlin-compose-schema-iossimulatorarm64-0.11.0.module",
        "group": "ai.factoredui",
        "module": "kotlin-compose-schema-iossimulatorarm64",
        "version": "0.11.0"
      }
    },
    {
      "name": "iosSimulatorArm64MetadataElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kotlin-compose-schema-iossimulatorarm64/0.11.0/kotlin-compose-schema-iossimulatorarm64-0.11.0.module",
        "group": "ai.factoredui",
        "module": "kotlin-compose-schema-iossimulatorarm64",
        "version": "0.11.0"
      }
    },
    {
      "name": "iosX64ApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kotlin-compose-schema-iosx64/0.11.0/kotlin-compose-schema-iosx64-0.11.0.module",
        "group": "ai.factoredui",
        "module": "kotlin-compose-schema-iosx64",
        "version": "0.11.0"
      }
    },
    {
      "name": "iosX64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kotlin-compose-schema-iosx64/0.11.0/kotlin-compose-schema-iosx64-0.11.0.module",
        "group": "ai.factoredui",
        "module": "kotlin-compose-schema-iosx64",
        "version": "0.11.0"
      }
    },
    {
      "name": "iosX64MetadataElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kotlin-compose-schema-iosx64/0.11.0/kotlin-compose-schema-iosx64-0.11.0.module",
        "group": "ai.factoredui",
        "module": "kotlin-compose-schema-iosx64",
        "version": "0.11.0"
      }
    },
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../kotlin-compose-schema-jvm/0.11.0/kotlin-compose-schema-jvm-0.11.0.module",
        "group": "ai.factoredui",
        "module": "kotlin-compose-schema-jvm",
        "version": "0.11.0"
      }
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../kotlin-compose-schema-jvm/0.11.0/kotlin-compose-schema-jvm-0.11.0.module",
        "group": "ai.factoredui",
        "module": "kotlin-compose-schema-jvm",
        "version": "0.11.0"
      }
    },
    {
      "name": "jvmSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../kotlin-compose-schema-jvm/0.11.0/kotlin-compose-schema-jvm-0.11.0.module",
        "group": "ai.factoredui",
        "module": "kotlin-compose-schema-jvm",
        "version": "0.11.0"
      }
    },
    {
      "name": "linuxX64ApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "linux_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kotlin-compose-schema-linuxx64/0.11.0/kotlin-compose-schema-linuxx64-0.11.0.module",
        "group": "ai.factoredui",
        "module": "kotlin-compose-schema-linuxx64",
        "version": "0.11.0"
      }
    },
    {
      "name": "linuxX64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "linux_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kotlin-compose-schema-linuxx64/0.11.0/kotlin-compose-schema-linuxx64-0.11.0.module",
        "group": "ai.factoredui",
        "module": "kotlin-compose-schema-linuxx64",
        "version": "0.11.0"
      }
    },
    {
      "name": "wasmJsApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "wasm",
        "org.jetbrains.kotlin.wasm.target": "js"
      },
      "available-at": {
        "url": "../../kotlin-compose-schema-wasm-js/0.11.0/kotlin-compose-schema-wasm-js-0.11.0.module",
        "group": "ai.factoredui",
        "module": "kotlin-compose-schema-wasm-js",
        "version": "0.11.0"
      }
    },
    {
      "name": "wasmJsRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.platform.type": "wasm",
        "org.jetbrains.kotlin.wasm.target": "js"
      },
      "available-at": {
        "url": "../../kotlin-compose-schema-wasm-js/0.11.0/kotlin-compose-schema-wasm-js-0.11.0.module",
        "group": "ai.factoredui",
        "module": "kotlin-compose-schema-wasm-js",
        "version": "0.11.0"
      }
    },
    {
      "name": "wasmJsSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.platform.type": "wasm",
        "org.jetbrains.kotlin.wasm.target": "js"
      },
      "available-at": {
        "url": "../../kotlin-compose-schema-wasm-js/0.11.0/kotlin-compose-schema-wasm-js-0.11.0.module",
        "group": "ai.factoredui",
        "module": "kotlin-compose-schema-wasm-js",
        "version": "0.11.0"
      }
    }
  ]
}
