{
  "formatVersion": "1.1",
  "component": {
    "url": "../../kotlin-compose/0.15.3/kotlin-compose-0.15.3.module",
    "group": "ai.factoredui",
    "module": "kotlin-compose",
    "version": "0.15.3",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14"
    }
  },
  "variants": [
    {
      "name": "desktopApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "ai.factoredui",
          "module": "kotlin-compose-schema",
          "version": {
            "requires": "0.15.3"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.21"
          }
        }
      ],
      "files": [
        {
          "name": "kotlin-compose-desktop-0.15.3.jar",
          "url": "kotlin-compose-desktop-0.15.3.jar",
          "size": 813786,
          "sha512": "40d930f3a6ee762b29a2755fc8f654176ea8c438c2b04ad81bded6bd2bfb9dc2b14a07e3b2e4903abccc2e1413911d9a4ca3698f2dca8acf11ed5a931193934c",
          "sha256": "878acb4800873490a3d6afb2a75f9e084b53ce21a1c0b6b2812a63ae41ef6f00",
          "sha1": "23551952e0f0c09090c6cdd8c7654fa1e53c63f3",
          "md5": "0a9158ccb522b082b5d995f636a9dd67"
        }
      ]
    },
    {
      "name": "desktopRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "ai.factoredui",
          "module": "kotlin-compose-schema",
          "version": {
            "requires": "0.15.3"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.21"
          }
        },
        {
          "group": "org.jetbrains.compose.desktop",
          "module": "desktop-jvm-linux-x64",
          "version": {
            "requires": "1.10.3"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-okhttp",
          "version": {
            "requires": "3.2.0"
          }
        },
        {
          "group": "org.jetbrains.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "1.10.3"
          }
        },
        {
          "group": "org.jetbrains.compose.foundation",
          "module": "foundation",
          "version": {
            "requires": "1.10.3"
          }
        },
        {
          "group": "org.jetbrains.compose.material3",
          "module": "material3",
          "version": {
            "requires": "1.9.0-beta03"
          }
        },
        {
          "group": "org.jetbrains.compose.ui",
          "module": "ui",
          "version": {
            "requires": "1.10.3"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.11.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.10.2"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-datetime",
          "version": {
            "requires": "0.7.1"
          }
        },
        {
          "group": "io.coil-kt.coil3",
          "module": "coil-compose",
          "version": {
            "requires": "3.2.0"
          }
        },
        {
          "group": "io.coil-kt.coil3",
          "module": "coil-network-ktor3",
          "version": {
            "requires": "3.2.0"
          }
        },
        {
          "group": "io.coil-kt.coil3",
          "module": "coil-svg",
          "version": {
            "requires": "3.2.0"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-core",
          "version": {
            "requires": "3.2.0"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-content-negotiation",
          "version": {
            "requires": "3.2.0"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-serialization-kotlinx-json",
          "version": {
            "requires": "3.2.0"
          }
        }
      ],
      "files": [
        {
          "name": "kotlin-compose-desktop-0.15.3.jar",
          "url": "kotlin-compose-desktop-0.15.3.jar",
          "size": 813786,
          "sha512": "40d930f3a6ee762b29a2755fc8f654176ea8c438c2b04ad81bded6bd2bfb9dc2b14a07e3b2e4903abccc2e1413911d9a4ca3698f2dca8acf11ed5a931193934c",
          "sha256": "878acb4800873490a3d6afb2a75f9e084b53ce21a1c0b6b2812a63ae41ef6f00",
          "sha1": "23551952e0f0c09090c6cdd8c7654fa1e53c63f3",
          "md5": "0a9158ccb522b082b5d995f636a9dd67"
        }
      ]
    },
    {
      "name": "desktopSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "kotlin-compose-desktop-0.15.3-sources.jar",
          "url": "kotlin-compose-desktop-0.15.3-sources.jar",
          "size": 96853,
          "sha512": "71ff1943b75e94d3b88984d0deb5c278d89f32cef044fa6c6ad2193cfd3fae4060bb4b9006e5271667ee1f00813813f685f5962d808765ee379cc1d4253e63f4",
          "sha256": "2827fce28b9ff39c2c451885ec09d100186bbdc9ecb0b2d6d759bce09d4a2d35",
          "sha1": "a88ad43b6322165205b8ccbefcc77a2fa30613fc",
          "md5": "b4ffec8f80b2828b88b38fde41cbb4cd"
        }
      ]
    }
  ]
}
