{
  "formatVersion": "1.1",
  "component": {
    "group": "ai.factoredui",
    "module": "kotlin-compose-schema",
    "version": "0.15.3",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14"
    }
  },
  "variants": [
    {
      "name": "metadataApiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.21"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.11.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-datetime",
          "version": {
            "requires": "0.7.1"
          }
        }
      ],
      "files": [
        {
          "name": "kotlin-compose-schema-metadata-0.15.3.jar",
          "url": "kotlin-compose-schema-0.15.3.jar",
          "size": 11922,
          "sha512": "c887bd1d78716cc5a890733e4f8abe25dd0e78e7ad2e09c3ac43c65fe9e192901bc1bb82687739140dd80cfc5572bb00082f65cb289555758033d7204627a7ed",
          "sha256": "b8117052b9d539ba6a02bef3cbd6a313775a135da769bd738219272102ff4388",
          "sha1": "5af3eee2ad5a34d8168418307a6dcfbb8a368f11",
          "md5": "fac54276663469c34ea91dc65019426e"
        }
      ]
    },
    {
      "name": "metadataSourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "files": [
        {
          "name": "kotlin-compose-schema-kotlin-0.15.3-sources.jar",
          "url": "kotlin-compose-schema-0.15.3-sources.jar",
          "size": 10734,
          "sha512": "8bb963a75040d0549fbf0e36b5e8eaba9c9a9d6603399b476ddb6b19e625fe9943b42b3bebe396cee412e5cb883ba55c3b6584affdf244648c1d620804e7febc",
          "sha256": "3d6c413bcf91535ebb3c80493626ad98f2c2b739d23005f22882adedf303e5fd",
          "sha1": "02b9f0bec53bdb8497127112c1a764ecc6c67db5",
          "md5": "b28fd5ec9f16ced2abfaacd7dbe53c50"
        }
      ]
    },
    {
      "name": "releaseApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "available-at": {
        "url": "../../kotlin-compose-schema-android/0.15.3/kotlin-compose-schema-android-0.15.3.module",
        "group": "ai.factoredui",
        "module": "kotlin-compose-schema-android",
        "version": "0.15.3"
      }
    },
    {
      "name": "releaseRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "available-at": {
        "url": "../../kotlin-compose-schema-android/0.15.3/kotlin-compose-schema-android-0.15.3.module",
        "group": "ai.factoredui",
        "module": "kotlin-compose-schema-android",
        "version": "0.15.3"
      }
    },
    {
      "name": "releaseSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "android",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "available-at": {
        "url": "../../kotlin-compose-schema-android/0.15.3/kotlin-compose-schema-android-0.15.3.module",
        "group": "ai.factoredui",
        "module": "kotlin-compose-schema-android",
        "version": "0.15.3"
      }
    },
    {
      "name": "iosArm64ApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kotlin-compose-schema-iosarm64/0.15.3/kotlin-compose-schema-iosarm64-0.15.3.module",
        "group": "ai.factoredui",
        "module": "kotlin-compose-schema-iosarm64",
        "version": "0.15.3"
      }
    },
    {
      "name": "iosArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kotlin-compose-schema-iosarm64/0.15.3/kotlin-compose-schema-iosarm64-0.15.3.module",
        "group": "ai.factoredui",
        "module": "kotlin-compose-schema-iosarm64",
        "version": "0.15.3"
      }
    },
    {
      "name": "iosArm64MetadataElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kotlin-compose-schema-iosarm64/0.15.3/kotlin-compose-schema-iosarm64-0.15.3.module",
        "group": "ai.factoredui",
        "module": "kotlin-compose-schema-iosarm64",
        "version": "0.15.3"
      }
    },
    {
      "name": "iosSimulatorArm64ApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kotlin-compose-schema-iossimulatorarm64/0.15.3/kotlin-compose-schema-iossimulatorarm64-0.15.3.module",
        "group": "ai.factoredui",
        "module": "kotlin-compose-schema-iossimulatorarm64",
        "version": "0.15.3"
      }
    },
    {
      "name": "iosSimulatorArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kotlin-compose-schema-iossimulatorarm64/0.15.3/kotlin-compose-schema-iossimulatorarm64-0.15.3.module",
        "group": "ai.factoredui",
        "module": "kotlin-compose-schema-iossimulatorarm64",
        "version": "0.15.3"
      }
    },
    {
      "name": "iosSimulatorArm64MetadataElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kotlin-compose-schema-iossimulatorarm64/0.15.3/kotlin-compose-schema-iossimulatorarm64-0.15.3.module",
        "group": "ai.factoredui",
        "module": "kotlin-compose-schema-iossimulatorarm64",
        "version": "0.15.3"
      }
    },
    {
      "name": "iosX64ApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kotlin-compose-schema-iosx64/0.15.3/kotlin-compose-schema-iosx64-0.15.3.module",
        "group": "ai.factoredui",
        "module": "kotlin-compose-schema-iosx64",
        "version": "0.15.3"
      }
    },
    {
      "name": "iosX64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kotlin-compose-schema-iosx64/0.15.3/kotlin-compose-schema-iosx64-0.15.3.module",
        "group": "ai.factoredui",
        "module": "kotlin-compose-schema-iosx64",
        "version": "0.15.3"
      }
    },
    {
      "name": "iosX64MetadataElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kotlin-compose-schema-iosx64/0.15.3/kotlin-compose-schema-iosx64-0.15.3.module",
        "group": "ai.factoredui",
        "module": "kotlin-compose-schema-iosx64",
        "version": "0.15.3"
      }
    },
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../kotlin-compose-schema-jvm/0.15.3/kotlin-compose-schema-jvm-0.15.3.module",
        "group": "ai.factoredui",
        "module": "kotlin-compose-schema-jvm",
        "version": "0.15.3"
      }
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../kotlin-compose-schema-jvm/0.15.3/kotlin-compose-schema-jvm-0.15.3.module",
        "group": "ai.factoredui",
        "module": "kotlin-compose-schema-jvm",
        "version": "0.15.3"
      }
    },
    {
      "name": "jvmSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../kotlin-compose-schema-jvm/0.15.3/kotlin-compose-schema-jvm-0.15.3.module",
        "group": "ai.factoredui",
        "module": "kotlin-compose-schema-jvm",
        "version": "0.15.3"
      }
    },
    {
      "name": "linuxX64ApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "linux_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kotlin-compose-schema-linuxx64/0.15.3/kotlin-compose-schema-linuxx64-0.15.3.module",
        "group": "ai.factoredui",
        "module": "kotlin-compose-schema-linuxx64",
        "version": "0.15.3"
      }
    },
    {
      "name": "linuxX64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "linux_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kotlin-compose-schema-linuxx64/0.15.3/kotlin-compose-schema-linuxx64-0.15.3.module",
        "group": "ai.factoredui",
        "module": "kotlin-compose-schema-linuxx64",
        "version": "0.15.3"
      }
    },
    {
      "name": "wasmJsApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "wasm",
        "org.jetbrains.kotlin.wasm.target": "js"
      },
      "available-at": {
        "url": "../../kotlin-compose-schema-wasm-js/0.15.3/kotlin-compose-schema-wasm-js-0.15.3.module",
        "group": "ai.factoredui",
        "module": "kotlin-compose-schema-wasm-js",
        "version": "0.15.3"
      }
    },
    {
      "name": "wasmJsRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.platform.type": "wasm",
        "org.jetbrains.kotlin.wasm.target": "js"
      },
      "available-at": {
        "url": "../../kotlin-compose-schema-wasm-js/0.15.3/kotlin-compose-schema-wasm-js-0.15.3.module",
        "group": "ai.factoredui",
        "module": "kotlin-compose-schema-wasm-js",
        "version": "0.15.3"
      }
    },
    {
      "name": "wasmJsSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.platform.type": "wasm",
        "org.jetbrains.kotlin.wasm.target": "js"
      },
      "available-at": {
        "url": "../../kotlin-compose-schema-wasm-js/0.15.3/kotlin-compose-schema-wasm-js-0.15.3.module",
        "group": "ai.factoredui",
        "module": "kotlin-compose-schema-wasm-js",
        "version": "0.15.3"
      }
    }
  ]
}
