{
  "formatVersion": "1.1",
  "component": {
    "url": "../../kotlin-compose-schema/0.13.0/kotlin-compose-schema-0.13.0.module",
    "group": "ai.factoredui",
    "module": "kotlin-compose-schema",
    "version": "0.13.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14"
    }
  },
  "variants": [
    {
      "name": "iosX64ApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.21"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.11.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-datetime",
          "version": {
            "requires": "0.7.1"
          }
        }
      ],
      "files": [
        {
          "name": "kotlin-compose-schema-iosX64Main-0.13.0.klib",
          "url": "kotlin-compose-schema-iosx64-0.13.0.klib",
          "size": 106199,
          "sha512": "603fdcfa7025f280bf3de10632f934c89ac728f965dabaad88cdd185c507eee90fd2531df4e8d43e44225730f90b0e0a8e1248e5bd18c21ab2a940536a4026b8",
          "sha256": "10f87f794640e2ac05aca793d576289efd9b0c299b29957e97dd14aa6285d4ad",
          "sha1": "b690d64fbf2e79b558275d73aa2721b05db277f9",
          "md5": "96fdb63405b27279268167e5ce3f4b30"
        }
      ]
    },
    {
      "name": "iosX64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "files": [
        {
          "name": "kotlin-compose-schema-iosx64-0.13.0-sources.jar",
          "url": "kotlin-compose-schema-iosx64-0.13.0-sources.jar",
          "size": 10453,
          "sha512": "3fbb28a198d7de5ca01ed32f9501092fac1b6af51a9b0098c21108f5a5c0608e92c3bd97c5b73aba71a264a999817927b4ebb13dae14cfabad9be095964ba1cc",
          "sha256": "a0966f1f9d3e6583b8dcf8432881a0902108e4151fa59a8d8b62084378017fe3",
          "sha1": "5013c85243b90636719264022c566aa65725c334",
          "md5": "f46850ca8f5deae24a974bcf4cc1901b"
        }
      ]
    },
    {
      "name": "iosX64MetadataElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.21"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.11.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-datetime",
          "version": {
            "requires": "0.7.1"
          }
        }
      ],
      "files": [
        {
          "name": "kotlin-compose-schema-iosx64-0.13.0-metadata.jar",
          "url": "kotlin-compose-schema-iosx64-0.13.0-metadata.jar",
          "size": 261,
          "sha512": "d90629044f7f2952f7408c01d047e95aa09a8f3c52302b781b3c50c0cd2dbc7072853a139de68e37277969837df61a814e6ab79cf89592d0e18494c3e2ff1178",
          "sha256": "f766d9c958a9de6156cca70ae46b4b85069317ef03a5c0fc0e2323aa35f614a0",
          "sha1": "7aad09bc993a69de3073e816203759e4ccf9d552",
          "md5": "041c68099a8e7c226d7e5b5aa0a1e05b"
        }
      ]
    }
  ]
}
