{
  "formatVersion": "1.1",
  "component": {
    "url": "../../kotlin-compose/0.13.2/kotlin-compose-0.13.2.module",
    "group": "ai.factoredui",
    "module": "kotlin-compose",
    "version": "0.13.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14"
    }
  },
  "variants": [
    {
      "name": "desktopApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "ai.factoredui",
          "module": "kotlin-compose-schema",
          "version": {
            "requires": "0.13.2"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.21"
          }
        }
      ],
      "files": [
        {
          "name": "kotlin-compose-desktop-0.13.2.jar",
          "url": "kotlin-compose-desktop-0.13.2.jar",
          "size": 849099,
          "sha512": "c13ca31750248688e0591907ce369dab36f8e2e82cd6d55f939089760e7096b4af3c18979beb252380f2cd7eb94e9e04b49957d6d6e691936b1412973b26a872",
          "sha256": "2f5421360d16f27bd3beb0c616d94659d4355e1d8deedd0af9dd7c3487744806",
          "sha1": "6df757a33309cd7abd562e4de73a35a9e38d3336",
          "md5": "bafbdd8622bfa6531198dccbcb656403"
        }
      ]
    },
    {
      "name": "desktopRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "ai.factoredui",
          "module": "kotlin-compose-schema",
          "version": {
            "requires": "0.13.2"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.21"
          }
        },
        {
          "group": "org.jetbrains.compose.desktop",
          "module": "desktop-jvm-linux-x64",
          "version": {
            "requires": "1.10.3"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-okhttp",
          "version": {
            "requires": "3.2.0"
          }
        },
        {
          "group": "org.jetbrains.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "1.10.3"
          }
        },
        {
          "group": "org.jetbrains.compose.foundation",
          "module": "foundation",
          "version": {
            "requires": "1.10.3"
          }
        },
        {
          "group": "org.jetbrains.compose.material3",
          "module": "material3",
          "version": {
            "requires": "1.9.0-beta03"
          }
        },
        {
          "group": "org.jetbrains.compose.ui",
          "module": "ui",
          "version": {
            "requires": "1.10.3"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.11.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.10.2"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-datetime",
          "version": {
            "requires": "0.7.1"
          }
        },
        {
          "group": "io.coil-kt.coil3",
          "module": "coil-compose",
          "version": {
            "requires": "3.2.0"
          }
        },
        {
          "group": "io.coil-kt.coil3",
          "module": "coil-network-ktor3",
          "version": {
            "requires": "3.2.0"
          }
        },
        {
          "group": "io.coil-kt.coil3",
          "module": "coil-svg",
          "version": {
            "requires": "3.2.0"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-core",
          "version": {
            "requires": "3.2.0"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-content-negotiation",
          "version": {
            "requires": "3.2.0"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-serialization-kotlinx-json",
          "version": {
            "requires": "3.2.0"
          }
        }
      ],
      "files": [
        {
          "name": "kotlin-compose-desktop-0.13.2.jar",
          "url": "kotlin-compose-desktop-0.13.2.jar",
          "size": 849099,
          "sha512": "c13ca31750248688e0591907ce369dab36f8e2e82cd6d55f939089760e7096b4af3c18979beb252380f2cd7eb94e9e04b49957d6d6e691936b1412973b26a872",
          "sha256": "2f5421360d16f27bd3beb0c616d94659d4355e1d8deedd0af9dd7c3487744806",
          "sha1": "6df757a33309cd7abd562e4de73a35a9e38d3336",
          "md5": "bafbdd8622bfa6531198dccbcb656403"
        }
      ]
    },
    {
      "name": "desktopSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "kotlin-compose-desktop-0.13.2-sources.jar",
          "url": "kotlin-compose-desktop-0.13.2-sources.jar",
          "size": 96363,
          "sha512": "7b82fcd836065cac1c832e06e71d4422abdadbb11cad35e9889c9bbf401f6d16b5548278f99246ce62e9d1f093aac3a3349a32cf864430446a97bbd3e454efc6",
          "sha256": "21d9f360fbf4288e3da3f533a02007d29b3bafce9013de84175059a3aa5ed0a4",
          "sha1": "1aafc2c774132c4a6640c636b424a281c1bc6003",
          "md5": "e363a30a9cde2974638344a72af0c962"
        }
      ]
    }
  ]
}
