{
  "formatVersion": "1.1",
  "component": {
    "url": "../../kotlin-compose/0.7.0/kotlin-compose-0.7.0.module",
    "group": "ai.factoredui",
    "module": "kotlin-compose",
    "version": "0.7.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14"
    }
  },
  "variants": [
    {
      "name": "desktopApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.21"
          }
        }
      ],
      "files": [
        {
          "name": "kotlin-compose-desktop-0.7.0.jar",
          "url": "kotlin-compose-desktop-0.7.0.jar",
          "size": 425914,
          "sha512": "2e8e7ea6766a98b27c59e87246ea8ef267929772457c7384d62072439c7294e3b2b77f474a66b5bc2a14e718449e078fd9d5bde010ac39141b4a9a95b2f8b380",
          "sha256": "1aef0bda6b1e29fd19f7fbbbbe1218afa0ace7d92d1e574df40d7827b3a7f383",
          "sha1": "c4ddb437e8a11eefc641db6dc98fb6d867844a43",
          "md5": "d6062967a67e005c2230d7fec2bcd052"
        }
      ]
    },
    {
      "name": "desktopRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.21"
          }
        },
        {
          "group": "org.jetbrains.compose.desktop",
          "module": "desktop-jvm-linux-x64",
          "version": {
            "requires": "1.10.3"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-okhttp",
          "version": {
            "requires": "3.2.0"
          }
        },
        {
          "group": "org.jetbrains.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "1.10.3"
          }
        },
        {
          "group": "org.jetbrains.compose.foundation",
          "module": "foundation",
          "version": {
            "requires": "1.10.3"
          }
        },
        {
          "group": "org.jetbrains.compose.material3",
          "module": "material3",
          "version": {
            "requires": "1.9.0-beta03"
          }
        },
        {
          "group": "org.jetbrains.compose.ui",
          "module": "ui",
          "version": {
            "requires": "1.10.3"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.11.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.10.2"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-datetime",
          "version": {
            "requires": "0.7.1"
          }
        },
        {
          "group": "io.coil-kt.coil3",
          "module": "coil-compose",
          "version": {
            "requires": "3.2.0"
          }
        },
        {
          "group": "io.coil-kt.coil3",
          "module": "coil-network-ktor3",
          "version": {
            "requires": "3.2.0"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-core",
          "version": {
            "requires": "3.2.0"
          }
        }
      ],
      "files": [
        {
          "name": "kotlin-compose-desktop-0.7.0.jar",
          "url": "kotlin-compose-desktop-0.7.0.jar",
          "size": 425914,
          "sha512": "2e8e7ea6766a98b27c59e87246ea8ef267929772457c7384d62072439c7294e3b2b77f474a66b5bc2a14e718449e078fd9d5bde010ac39141b4a9a95b2f8b380",
          "sha256": "1aef0bda6b1e29fd19f7fbbbbe1218afa0ace7d92d1e574df40d7827b3a7f383",
          "sha1": "c4ddb437e8a11eefc641db6dc98fb6d867844a43",
          "md5": "d6062967a67e005c2230d7fec2bcd052"
        }
      ]
    },
    {
      "name": "desktopSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "kotlin-compose-desktop-0.7.0-sources.jar",
          "url": "kotlin-compose-desktop-0.7.0-sources.jar",
          "size": 51390,
          "sha512": "6309d3fd9aded73e09966168a3b7ad97c0da2281ae66f5c94e5e917f33f0c464d8b7531ef0503ea6ab6598016860891bfeece84b8991a516c0bd61ce05e04667",
          "sha256": "18ff00aaedfe71f564594b6251ea285fff246558713b6a693386def706e761cc",
          "sha1": "542f680765ef0e88e6c69a084cf53c9c8ca48986",
          "md5": "6ddb61e1b8b73eca11bc8ef328a8e0bd"
        }
      ]
    }
  ]
}
