{
  "formatVersion": "1.1",
  "component": {
    "url": "../../kotlin-compose-schema/0.17.0/kotlin-compose-schema-0.17.0.module",
    "group": "ai.factoredui",
    "module": "kotlin-compose-schema",
    "version": "0.17.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14"
    }
  },
  "variants": [
    {
      "name": "wasmJsApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "wasm",
        "org.jetbrains.kotlin.wasm.target": "js"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.21"
          }
        }
      ],
      "files": [
        {
          "name": "kotlin-compose-schema-wasm-js-0.17.0.klib",
          "url": "kotlin-compose-schema-wasm-js-0.17.0.klib",
          "size": 108554,
          "sha512": "23e2ad9104f74e1f7075e579c7038043dce21ff8f87b6ce3d6d96b7f8d648b01738076835619da7f98fa86afcedb29cd62cb1adc8bbb54a28690df53a9b630a2",
          "sha256": "b2944955f5eb8cd47d3393aff5081312b9a3879db76d46b0ae37175a2f354505",
          "sha1": "e5885e36fe6d5e36bb4989c578322a6f03a73aa4",
          "md5": "4d689836d0310cb0bb9a583bc1e336b1"
        }
      ]
    },
    {
      "name": "wasmJsRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.platform.type": "wasm",
        "org.jetbrains.kotlin.wasm.target": "js"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.21"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.11.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-datetime",
          "version": {
            "requires": "0.7.1"
          }
        }
      ],
      "files": [
        {
          "name": "kotlin-compose-schema-wasm-js-0.17.0.klib",
          "url": "kotlin-compose-schema-wasm-js-0.17.0.klib",
          "size": 108554,
          "sha512": "23e2ad9104f74e1f7075e579c7038043dce21ff8f87b6ce3d6d96b7f8d648b01738076835619da7f98fa86afcedb29cd62cb1adc8bbb54a28690df53a9b630a2",
          "sha256": "b2944955f5eb8cd47d3393aff5081312b9a3879db76d46b0ae37175a2f354505",
          "sha1": "e5885e36fe6d5e36bb4989c578322a6f03a73aa4",
          "md5": "4d689836d0310cb0bb9a583bc1e336b1"
        }
      ]
    },
    {
      "name": "wasmJsSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.platform.type": "wasm",
        "org.jetbrains.kotlin.wasm.target": "js"
      },
      "files": [
        {
          "name": "kotlin-compose-schema-wasm-js-0.17.0-sources.jar",
          "url": "kotlin-compose-schema-wasm-js-0.17.0-sources.jar",
          "size": 11046,
          "sha512": "cae4c08ab3f9a8344d54c7e0e4fa9269ea8da377662bc4064d80a2cd79f09fee86747b36290041c447b7ad05a090b3b7bcfbbd8da350247fd6ee8dcdd79d58e9",
          "sha256": "ed1a6fb4bff7ef3d57fa32ea9d4747fa020577883dfc09c1f4431e7d0ca4534d",
          "sha1": "aef338a946cb47d02cec2a29e4662c43516a06c2",
          "md5": "96bcd168f6e86923ea03d2264bc834ae"
        }
      ]
    }
  ]
}
