{
  "formatVersion": "1.1",
  "component": {
    "url": "../../kotlin-compose/0.5.1/kotlin-compose-0.5.1.module",
    "group": "ai.factoredui",
    "module": "kotlin-compose",
    "version": "0.5.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.10.2"
    }
  },
  "variants": [
    {
      "name": "wasmJsApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "wasm",
        "org.jetbrains.kotlin.wasm.target": "js"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.21"
          }
        }
      ],
      "files": [
        {
          "name": "kotlin-compose-wasm-js-0.5.1.klib",
          "url": "kotlin-compose-wasm-js-0.5.1.klib",
          "size": 329199,
          "sha512": "d37128195104a5c6dcddd3f53b224de78c0c3e12a980e4e777119119a61072bbdc00254de473a4e01f426bc0afdaa9d9434fdd250cf26564e31ca0b66b03677d",
          "sha256": "6395b7a136c06dc89e5e3eb52a6d424be66d4aa3a419bc9efbc97a4c36fee1eb",
          "sha1": "20cbb977a4e747b0c8f40e151e1d4cc9e8435c52",
          "md5": "0cdf0ba061ed64cc80fa0d495c802f0d"
        }
      ]
    },
    {
      "name": "wasmJsRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.platform.type": "wasm",
        "org.jetbrains.kotlin.wasm.target": "js"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.21"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-js",
          "version": {
            "requires": "3.0.3"
          }
        },
        {
          "group": "org.jetbrains.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "1.7.3"
          }
        },
        {
          "group": "org.jetbrains.compose.foundation",
          "module": "foundation",
          "version": {
            "requires": "1.7.3"
          }
        },
        {
          "group": "org.jetbrains.compose.material3",
          "module": "material3",
          "version": {
            "requires": "1.7.3"
          }
        },
        {
          "group": "org.jetbrains.compose.ui",
          "module": "ui",
          "version": {
            "requires": "1.7.3"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.7.3"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-datetime",
          "version": {
            "requires": "0.6.1"
          }
        },
        {
          "group": "io.coil-kt.coil3",
          "module": "coil-compose",
          "version": {
            "requires": "3.0.4"
          }
        },
        {
          "group": "io.coil-kt.coil3",
          "module": "coil-network-ktor3",
          "version": {
            "requires": "3.0.4"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-core",
          "version": {
            "requires": "3.0.3"
          }
        }
      ],
      "files": [
        {
          "name": "kotlin-compose-wasm-js-0.5.1.klib",
          "url": "kotlin-compose-wasm-js-0.5.1.klib",
          "size": 329199,
          "sha512": "d37128195104a5c6dcddd3f53b224de78c0c3e12a980e4e777119119a61072bbdc00254de473a4e01f426bc0afdaa9d9434fdd250cf26564e31ca0b66b03677d",
          "sha256": "6395b7a136c06dc89e5e3eb52a6d424be66d4aa3a419bc9efbc97a4c36fee1eb",
          "sha1": "20cbb977a4e747b0c8f40e151e1d4cc9e8435c52",
          "md5": "0cdf0ba061ed64cc80fa0d495c802f0d"
        }
      ]
    },
    {
      "name": "wasmJsSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.platform.type": "wasm",
        "org.jetbrains.kotlin.wasm.target": "js"
      },
      "files": [
        {
          "name": "kotlin-compose-wasm-js-0.5.1-sources.jar",
          "url": "kotlin-compose-wasm-js-0.5.1-sources.jar",
          "size": 48695,
          "sha512": "b043cbbd59fa308b53545a3e293f2582c16e9118cb7da6ee9603d3ca679eb808b7c85efe8efbd48b3482443a07831cbe1c625c1535e8b3f4cfe449903f701f5b",
          "sha256": "d91941f2267c770dde07075a50b8c5a2d4cdbc35debdda8ca57cdf4d81f495cc",
          "sha1": "ae941af3ae500932756f80a2db95d5a9a7b0bdaf",
          "md5": "f4230820a716ca98453d96590d612530"
        }
      ]
    },
    {
      "name": "wasmJsResourcesElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.libraryelements": "kotlin-multiplatformresourcesjs",
        "org.gradle.usage": "kotlin-multiplatformresourcesjs",
        "org.jetbrains.kotlin.platform.type": "wasm",
        "org.jetbrains.kotlin.wasm.target": "js"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.21"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-js",
          "version": {
            "requires": "3.0.3"
          }
        },
        {
          "group": "org.jetbrains.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "1.7.3"
          }
        },
        {
          "group": "org.jetbrains.compose.foundation",
          "module": "foundation",
          "version": {
            "requires": "1.7.3"
          }
        },
        {
          "group": "org.jetbrains.compose.material3",
          "module": "material3",
          "version": {
            "requires": "1.7.3"
          }
        },
        {
          "group": "org.jetbrains.compose.ui",
          "module": "ui",
          "version": {
            "requires": "1.7.3"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.7.3"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-datetime",
          "version": {
            "requires": "0.6.1"
          }
        },
        {
          "group": "io.coil-kt.coil3",
          "module": "coil-compose",
          "version": {
            "requires": "3.0.4"
          }
        },
        {
          "group": "io.coil-kt.coil3",
          "module": "coil-network-ktor3",
          "version": {
            "requires": "3.0.4"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-core",
          "version": {
            "requires": "3.0.3"
          }
        }
      ],
      "files": [
        {
          "name": "kotlin-compose-0.5.1.kotlin_resources.zip",
          "url": "kotlin-compose-wasm-js-0.5.1-kotlin_resources.kotlin_resources.zip",
          "size": 344,
          "sha512": "03b64871076ea4be7147564f6711fbdf71ae0f88d3d80be0ff945cb014a36735cee7e7bd31281b88930599f3aad69bb0e49ba4134df2022a65760549234b886c",
          "sha256": "65e414849ec80bbd6298feb84974b159d9399cdfd58732aa824d770437449100",
          "sha1": "48e1f780bd5714fbe2ab82646593bbdb71578353",
          "md5": "41a48f74fd449d54e8848d9666ee124e"
        }
      ]
    }
  ]
}
