{
  "formatVersion": "1.1",
  "component": {
    "url": "../../kotlin-compose/0.20.1/kotlin-compose-0.20.1.module",
    "group": "ai.factoredui",
    "module": "kotlin-compose",
    "version": "0.20.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14"
    }
  },
  "variants": [
    {
      "name": "desktopApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "ai.factoredui",
          "module": "kotlin-compose-schema",
          "version": {
            "requires": "0.20.1"
          }
        },
        {
          "group": "ai.factoredui",
          "module": "kotlin-compose-capture",
          "version": {
            "requires": "0.20.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.21"
          }
        }
      ],
      "files": [
        {
          "name": "kotlin-compose-desktop-0.20.1.jar",
          "url": "kotlin-compose-desktop-0.20.1.jar",
          "size": 838008,
          "sha512": "54d76fbd75f34b6f415270927b68cdcfc00d45bcfa00b764179afbe228008b107c7e428f47b49fe8313a25d27ea5a0cce20803c09a01adafc9def36c1d56e3ea",
          "sha256": "b4d1aa3f4e8450eb733e818d8a2d71e5260d4ff58bd953f7a55d4e29d1ccbc25",
          "sha1": "dbe399bc3dde31afe3e97bf7b7884673fdba4702",
          "md5": "f329368e9ae119b026ce8a73df7b5571"
        }
      ]
    },
    {
      "name": "desktopRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "ai.factoredui",
          "module": "kotlin-compose-schema",
          "version": {
            "requires": "0.20.1"
          }
        },
        {
          "group": "ai.factoredui",
          "module": "kotlin-compose-capture",
          "version": {
            "requires": "0.20.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.21"
          }
        },
        {
          "group": "org.jetbrains.compose.desktop",
          "module": "desktop",
          "version": {
            "requires": "1.10.3"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-okhttp",
          "version": {
            "requires": "3.2.4"
          }
        },
        {
          "group": "org.jetbrains.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "1.10.3"
          }
        },
        {
          "group": "org.jetbrains.compose.foundation",
          "module": "foundation",
          "version": {
            "requires": "1.10.3"
          }
        },
        {
          "group": "org.jetbrains.compose.material3",
          "module": "material3",
          "version": {
            "requires": "1.9.0-beta03"
          }
        },
        {
          "group": "org.jetbrains.compose.ui",
          "module": "ui",
          "version": {
            "requires": "1.10.3"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.11.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.10.2"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-datetime",
          "version": {
            "requires": "0.7.1"
          }
        },
        {
          "group": "io.coil-kt.coil3",
          "module": "coil-compose",
          "version": {
            "requires": "3.2.0"
          }
        },
        {
          "group": "io.coil-kt.coil3",
          "module": "coil-network-ktor3",
          "version": {
            "requires": "3.2.0"
          }
        },
        {
          "group": "io.coil-kt.coil3",
          "module": "coil-svg",
          "version": {
            "requires": "3.2.0"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-core",
          "version": {
            "requires": "3.2.4"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-content-negotiation",
          "version": {
            "requires": "3.2.4"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-serialization-kotlinx-json",
          "version": {
            "requires": "3.2.4"
          }
        }
      ],
      "files": [
        {
          "name": "kotlin-compose-desktop-0.20.1.jar",
          "url": "kotlin-compose-desktop-0.20.1.jar",
          "size": 838008,
          "sha512": "54d76fbd75f34b6f415270927b68cdcfc00d45bcfa00b764179afbe228008b107c7e428f47b49fe8313a25d27ea5a0cce20803c09a01adafc9def36c1d56e3ea",
          "sha256": "b4d1aa3f4e8450eb733e818d8a2d71e5260d4ff58bd953f7a55d4e29d1ccbc25",
          "sha1": "dbe399bc3dde31afe3e97bf7b7884673fdba4702",
          "md5": "f329368e9ae119b026ce8a73df7b5571"
        }
      ]
    },
    {
      "name": "desktopSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "kotlin-compose-desktop-0.20.1-sources.jar",
          "url": "kotlin-compose-desktop-0.20.1-sources.jar",
          "size": 101458,
          "sha512": "89cba15fa08b4e473d12efe6e27d51fa100c002f28afa7d92dfad4f6fb4f756bd49456e0af902cfed8bf12aec4d79a45e9687c0bf8c1e7d374c41e2514f953df",
          "sha256": "d33325134aaeb5183c77295adb673abf855b4d9dfa62ec4d48e5ff4a01a03171",
          "sha1": "1da701ede76f58691a9db49fdf51ecfb5ca12c2a",
          "md5": "39edfd7780ff33ce380d07014c1fef32"
        }
      ]
    }
  ]
}
