{
  "formatVersion": "1.1",
  "component": {
    "url": "../../kotlin-compose-schema/0.15.3/kotlin-compose-schema-0.15.3.module",
    "group": "ai.factoredui",
    "module": "kotlin-compose-schema",
    "version": "0.15.3",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14"
    }
  },
  "variants": [
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.21"
          }
        }
      ],
      "files": [
        {
          "name": "kotlin-compose-schema-jvm-0.15.3.jar",
          "url": "kotlin-compose-schema-jvm-0.15.3.jar",
          "size": 154385,
          "sha512": "1f188d6de981ed5dd924d19c6900c19a23a120881993c61b58c113d8222ebcdd8e921f5eb2ba92bde90816f6016735d7ca46212b94b63cfe70a0d2f8deef1e05",
          "sha256": "78c8929419b94e6ed082d795ab29abfaf7fff6ba4769cf863ab2bf8fa18910b8",
          "sha1": "3529f2af19d5b2e4b06557c9d7835c40e654fe1f",
          "md5": "5e3f7982b0c44f1b2fcfa1c757a42554"
        }
      ]
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.21"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.11.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-datetime",
          "version": {
            "requires": "0.7.1"
          }
        }
      ],
      "files": [
        {
          "name": "kotlin-compose-schema-jvm-0.15.3.jar",
          "url": "kotlin-compose-schema-jvm-0.15.3.jar",
          "size": 154385,
          "sha512": "1f188d6de981ed5dd924d19c6900c19a23a120881993c61b58c113d8222ebcdd8e921f5eb2ba92bde90816f6016735d7ca46212b94b63cfe70a0d2f8deef1e05",
          "sha256": "78c8929419b94e6ed082d795ab29abfaf7fff6ba4769cf863ab2bf8fa18910b8",
          "sha1": "3529f2af19d5b2e4b06557c9d7835c40e654fe1f",
          "md5": "5e3f7982b0c44f1b2fcfa1c757a42554"
        }
      ]
    },
    {
      "name": "jvmSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "kotlin-compose-schema-jvm-0.15.3-sources.jar",
          "url": "kotlin-compose-schema-jvm-0.15.3-sources.jar",
          "size": 10734,
          "sha512": "8bb963a75040d0549fbf0e36b5e8eaba9c9a9d6603399b476ddb6b19e625fe9943b42b3bebe396cee412e5cb883ba55c3b6584affdf244648c1d620804e7febc",
          "sha256": "3d6c413bcf91535ebb3c80493626ad98f2c2b739d23005f22882adedf303e5fd",
          "sha1": "02b9f0bec53bdb8497127112c1a764ecc6c67db5",
          "md5": "b28fd5ec9f16ced2abfaacd7dbe53c50"
        }
      ]
    }
  ]
}
