{
  "formatVersion": "1.1",
  "component": {
    "url": "../../kotlin-engine/0.9.0/kotlin-engine-0.9.0.module",
    "group": "ai.factoredui",
    "module": "kotlin-engine",
    "version": "0.9.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14"
    }
  },
  "variants": [
    {
      "name": "linuxX64ApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "linux_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "ai.factoredui",
          "module": "kotlin-compose-schema",
          "version": {
            "requires": "0.9.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.21"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.11.0"
          }
        }
      ],
      "files": [
        {
          "name": "kotlin-engine-linuxX64Main-0.9.0.klib",
          "url": "kotlin-engine-linuxx64-0.9.0.klib",
          "size": 74012,
          "sha512": "e0d79346a8da78700ddb2e73739ec6efd65ef595381e1573b37b395c01c79b609ebcf12d011b615bc9cb70a62e501225599462f065c3a4b80bc5b99a0437bcca",
          "sha256": "1430005c08a5a6148762cdb53543a5a0c1bfc14cb34101fc504e519a6a789199",
          "sha1": "9d099cd78a0da2347b828920223415c97b58d218",
          "md5": "d1ec3bae0fef8641207b7ef31eb73a45"
        }
      ]
    },
    {
      "name": "linuxX64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "linux_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "files": [
        {
          "name": "kotlin-engine-linuxx64-0.9.0-sources.jar",
          "url": "kotlin-engine-linuxx64-0.9.0-sources.jar",
          "size": 12466,
          "sha512": "64fd9f6420b2aea8e49b9b1c8e9f74b7b1590d51441509053c81d6938126bbd5376f8e3906583c32e296dd31055ab1b9756ddcfed6a9f30f6e8f968bad154fa1",
          "sha256": "dc8377b57cf44787664168ef1d1e1106cfba6c2299e91d4c1eb488ea0d5db025",
          "sha1": "eb97f38572b70bdbf1fe7cb88c68eac18830fc5a",
          "md5": "326b83071cbbb8de717754774c4007c1"
        }
      ]
    }
  ]
}
