{
  "formatVersion": "1.1",
  "component": {
    "url": "../../kotlin-compose-schema/0.13.0/kotlin-compose-schema-0.13.0.module",
    "group": "ai.factoredui",
    "module": "kotlin-compose-schema",
    "version": "0.13.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14"
    }
  },
  "variants": [
    {
      "name": "iosArm64ApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.21"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.11.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-datetime",
          "version": {
            "requires": "0.7.1"
          }
        }
      ],
      "files": [
        {
          "name": "kotlin-compose-schema-iosArm64Main-0.13.0.klib",
          "url": "kotlin-compose-schema-iosarm64-0.13.0.klib",
          "size": 106211,
          "sha512": "ace2650245043e3fb40c4d0f886677cdf31c84cf668830342622db68eff53735da634aba5f67774f1f9251660b3d31d68dd5694ca817f5931ed03d6c4f667e4c",
          "sha256": "8796d389cda4ed29dfd74bb6d1ec6dfb88933f1a60b8ae6233274c7fa8180d7f",
          "sha1": "91cdb8711aa3456362c280d456c33fbce2bd25f0",
          "md5": "24b9d4ccfbe345ad133f9601cb6a1f5d"
        }
      ]
    },
    {
      "name": "iosArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "files": [
        {
          "name": "kotlin-compose-schema-iosarm64-0.13.0-sources.jar",
          "url": "kotlin-compose-schema-iosarm64-0.13.0-sources.jar",
          "size": 10453,
          "sha512": "3fbb28a198d7de5ca01ed32f9501092fac1b6af51a9b0098c21108f5a5c0608e92c3bd97c5b73aba71a264a999817927b4ebb13dae14cfabad9be095964ba1cc",
          "sha256": "a0966f1f9d3e6583b8dcf8432881a0902108e4151fa59a8d8b62084378017fe3",
          "sha1": "5013c85243b90636719264022c566aa65725c334",
          "md5": "f46850ca8f5deae24a974bcf4cc1901b"
        }
      ]
    },
    {
      "name": "iosArm64MetadataElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.21"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.11.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-datetime",
          "version": {
            "requires": "0.7.1"
          }
        }
      ],
      "files": [
        {
          "name": "kotlin-compose-schema-iosarm64-0.13.0-metadata.jar",
          "url": "kotlin-compose-schema-iosarm64-0.13.0-metadata.jar",
          "size": 261,
          "sha512": "d90629044f7f2952f7408c01d047e95aa09a8f3c52302b781b3c50c0cd2dbc7072853a139de68e37277969837df61a814e6ab79cf89592d0e18494c3e2ff1178",
          "sha256": "f766d9c958a9de6156cca70ae46b4b85069317ef03a5c0fc0e2323aa35f614a0",
          "sha1": "7aad09bc993a69de3073e816203759e4ccf9d552",
          "md5": "041c68099a8e7c226d7e5b5aa0a1e05b"
        }
      ]
    }
  ]
}
