{
  "formatVersion": "1.1",
  "component": {
    "url": "../../kotlin-compose-schema/0.17.2/kotlin-compose-schema-0.17.2.module",
    "group": "ai.factoredui",
    "module": "kotlin-compose-schema",
    "version": "0.17.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14"
    }
  },
  "variants": [
    {
      "name": "iosSimulatorArm64ApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.21"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.11.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-datetime",
          "version": {
            "requires": "0.7.1"
          }
        }
      ],
      "files": [
        {
          "name": "kotlin-compose-schema-iosSimulatorArm64Main-0.17.2.klib",
          "url": "kotlin-compose-schema-iossimulatorarm64-0.17.2.klib",
          "size": 112944,
          "sha512": "919217386614aff2684a62d729b50790e04b8397a697a55db9999e81d5e960ccf60c65439d587aad3a91b55d06edcb90099354e664c4f962b6e95d41e511f76c",
          "sha256": "c33d6da0222814acad0e101dc36b9e70d368601e81e593c0fa82dc33bbbcd92c",
          "sha1": "4f12661a6ace529a4fd122465a8ee93d07b30c46",
          "md5": "1f1c5b718baf33435a19322a7fc63d65"
        }
      ]
    },
    {
      "name": "iosSimulatorArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "files": [
        {
          "name": "kotlin-compose-schema-iossimulatorarm64-0.17.2-sources.jar",
          "url": "kotlin-compose-schema-iossimulatorarm64-0.17.2-sources.jar",
          "size": 11244,
          "sha512": "4f4fab68f47ca454347578d19a8686b5dc6d91880e982fd2ad2b00f30766de0e444f09cb6f94ced0f2cbd5a2748258be422665dcbc86dba910198bae1d2e7e23",
          "sha256": "98d201c5535c8ec3512dab69330bbbe3c2c19592d3a076c1131fc37ff0739ac7",
          "sha1": "f90a56dd668840053b36c36fb9bfaafba11c0ab9",
          "md5": "93f15f553e8b647097b619e1e104df7c"
        }
      ]
    },
    {
      "name": "iosSimulatorArm64MetadataElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.21"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.11.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-datetime",
          "version": {
            "requires": "0.7.1"
          }
        }
      ],
      "files": [
        {
          "name": "kotlin-compose-schema-iossimulatorarm64-0.17.2-metadata.jar",
          "url": "kotlin-compose-schema-iossimulatorarm64-0.17.2-metadata.jar",
          "size": 261,
          "sha512": "359c5dc6a0e7c32bd300fd1526422962ebef3c9e61a5563055ba01bfda27445f39c914acb32eccf7ca48f3f1b6fb62706b73afa8cc967e639bedef5b2c0f6d5b",
          "sha256": "e7295d4d4109889a057812e3d0bbcc9f6f22b6ef44eb9ed71402ce1936260b20",
          "sha1": "a00ff4527e81b2bede020a7faef78b2154ac38fd",
          "md5": "429b98cd3237568f011a7dc8e1493238"
        }
      ]
    }
  ]
}
