{
  "formatVersion": "1.1",
  "component": {
    "group": "ai.factoredui",
    "module": "kotlin-server",
    "version": "0.20.3",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.21"
          }
        }
      ],
      "files": [
        {
          "name": "kotlin-server-0.20.3.jar",
          "url": "kotlin-server-0.20.3.jar",
          "size": 12937,
          "sha512": "6853d1627ea4a6d017dfb59581c07840733e80319257181e92e3050ee016624dc1d421c8669f502cec671ab141dd308f660a205463b1009cb85186f56d174ecb",
          "sha256": "fd039f2e5ac2c21c1463b14fd69f666fa559f53a915e204132960f6a334b34d3",
          "sha1": "12681fbfc9b6370c9b84a4d052c4a131e2710f72",
          "md5": "e3787465b373bfa8e9fc03769612c079"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "ai.factoredui",
          "module": "kotlin-compose-schema",
          "version": {
            "requires": "0.20.3"
          }
        },
        {
          "group": "ai.factoredui",
          "module": "kotlin-compose-capture",
          "version": {
            "requires": "0.20.3"
          }
        },
        {
          "group": "ai.factoredui",
          "module": "kotlin-engine",
          "version": {
            "requires": "0.20.3"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.11.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.10.2"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-datetime",
          "version": {
            "requires": "0.7.1"
          }
        },
        {
          "group": "org.postgresql",
          "module": "postgresql",
          "version": {
            "requires": "42.7.4"
          }
        },
        {
          "group": "com.zaxxer",
          "module": "HikariCP",
          "version": {
            "requires": "5.1.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.21"
          }
        }
      ],
      "files": [
        {
          "name": "kotlin-server-0.20.3.jar",
          "url": "kotlin-server-0.20.3.jar",
          "size": 12937,
          "sha512": "6853d1627ea4a6d017dfb59581c07840733e80319257181e92e3050ee016624dc1d421c8669f502cec671ab141dd308f660a205463b1009cb85186f56d174ecb",
          "sha256": "fd039f2e5ac2c21c1463b14fd69f666fa559f53a915e204132960f6a334b34d3",
          "sha1": "12681fbfc9b6370c9b84a4d052c4a131e2710f72",
          "md5": "e3787465b373bfa8e9fc03769612c079"
        }
      ]
    }
  ]
}
