{
  "formatVersion": "1.1",
  "component": {
    "url": "../../kotlin-compose-schema/0.15.3/kotlin-compose-schema-0.15.3.module",
    "group": "ai.factoredui",
    "module": "kotlin-compose-schema",
    "version": "0.15.3",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14"
    }
  },
  "variants": [
    {
      "name": "wasmJsApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "wasm",
        "org.jetbrains.kotlin.wasm.target": "js"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.21"
          }
        }
      ],
      "files": [
        {
          "name": "kotlin-compose-schema-wasm-js-0.15.3.klib",
          "url": "kotlin-compose-schema-wasm-js-0.15.3.klib",
          "size": 107541,
          "sha512": "ae45d65deea8fb64a1dcf9ccb22aed63ab351bdbf531085f14df7c95cc6426934707f67c761c97123d3bb7b43e1485e1b5a4e296a1265830a07836813e05545e",
          "sha256": "96715e5293984ea45d425f2dba9853a81ab6b34e3b8fb2a17151f9c40d77ef6e",
          "sha1": "010d21062dbaa266c80a7a3f23c6308ea3d1324c",
          "md5": "fe15f3ea7fc5a09dc303326c0704fa78"
        }
      ]
    },
    {
      "name": "wasmJsRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.platform.type": "wasm",
        "org.jetbrains.kotlin.wasm.target": "js"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.21"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.11.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-datetime",
          "version": {
            "requires": "0.7.1"
          }
        }
      ],
      "files": [
        {
          "name": "kotlin-compose-schema-wasm-js-0.15.3.klib",
          "url": "kotlin-compose-schema-wasm-js-0.15.3.klib",
          "size": 107541,
          "sha512": "ae45d65deea8fb64a1dcf9ccb22aed63ab351bdbf531085f14df7c95cc6426934707f67c761c97123d3bb7b43e1485e1b5a4e296a1265830a07836813e05545e",
          "sha256": "96715e5293984ea45d425f2dba9853a81ab6b34e3b8fb2a17151f9c40d77ef6e",
          "sha1": "010d21062dbaa266c80a7a3f23c6308ea3d1324c",
          "md5": "fe15f3ea7fc5a09dc303326c0704fa78"
        }
      ]
    },
    {
      "name": "wasmJsSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.platform.type": "wasm",
        "org.jetbrains.kotlin.wasm.target": "js"
      },
      "files": [
        {
          "name": "kotlin-compose-schema-wasm-js-0.15.3-sources.jar",
          "url": "kotlin-compose-schema-wasm-js-0.15.3-sources.jar",
          "size": 10734,
          "sha512": "8bb963a75040d0549fbf0e36b5e8eaba9c9a9d6603399b476ddb6b19e625fe9943b42b3bebe396cee412e5cb883ba55c3b6584affdf244648c1d620804e7febc",
          "sha256": "3d6c413bcf91535ebb3c80493626ad98f2c2b739d23005f22882adedf303e5fd",
          "sha1": "02b9f0bec53bdb8497127112c1a764ecc6c67db5",
          "md5": "b28fd5ec9f16ced2abfaacd7dbe53c50"
        }
      ]
    }
  ]
}
