{
  "formatVersion": "1.1",
  "component": {
    "url": "../../kotlin-compose-schema/0.15.1/kotlin-compose-schema-0.15.1.module",
    "group": "ai.factoredui",
    "module": "kotlin-compose-schema",
    "version": "0.15.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14"
    }
  },
  "variants": [
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.21"
          }
        }
      ],
      "files": [
        {
          "name": "kotlin-compose-schema-jvm-0.15.1.jar",
          "url": "kotlin-compose-schema-jvm-0.15.1.jar",
          "size": 154076,
          "sha512": "bba99e9d3d8443dec1073b6572d2a234271ef760d04c2bdaa52a89b066e5983dfbfeb9d65b150a038435061713f2a4089b94f9686eb6060a206a26fa2d9b5b02",
          "sha256": "49e07738b69836c502d4bc2a1a98e6549ba96511f5660d35bc2cc7ef827dea67",
          "sha1": "54dae23a7543cacad7ebf75bb525cc44a4dea2bf",
          "md5": "729259ba51a56d51ff6a2fdcb182a649"
        }
      ]
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.21"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.11.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-datetime",
          "version": {
            "requires": "0.7.1"
          }
        }
      ],
      "files": [
        {
          "name": "kotlin-compose-schema-jvm-0.15.1.jar",
          "url": "kotlin-compose-schema-jvm-0.15.1.jar",
          "size": 154076,
          "sha512": "bba99e9d3d8443dec1073b6572d2a234271ef760d04c2bdaa52a89b066e5983dfbfeb9d65b150a038435061713f2a4089b94f9686eb6060a206a26fa2d9b5b02",
          "sha256": "49e07738b69836c502d4bc2a1a98e6549ba96511f5660d35bc2cc7ef827dea67",
          "sha1": "54dae23a7543cacad7ebf75bb525cc44a4dea2bf",
          "md5": "729259ba51a56d51ff6a2fdcb182a649"
        }
      ]
    },
    {
      "name": "jvmSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "kotlin-compose-schema-jvm-0.15.1-sources.jar",
          "url": "kotlin-compose-schema-jvm-0.15.1-sources.jar",
          "size": 10701,
          "sha512": "e03eabd24f7ad18525a53b2efdcbcd0587aeb9e5b04013ab6bf4e2cfdfa0ddd43e12eb8438375e892759fc85f72eeb0cf7b860ee4879b8d7139d14920dad2276",
          "sha256": "a7fe9cc4be4ffcf073a969764e26d8bb7269094079301e8370e5a752d9e90dd9",
          "sha1": "a1431a695180b1ca4b85418facb62d09da7942eb",
          "md5": "7aa00ebdc36bf4eddfd3db43fe3759a1"
        }
      ]
    }
  ]
}
