{
  "formatVersion": "1.1",
  "component": {
    "url": "../../kotlin-compose-schema/0.10.0/kotlin-compose-schema-0.10.0.module",
    "group": "ai.factoredui",
    "module": "kotlin-compose-schema",
    "version": "0.10.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14"
    }
  },
  "variants": [
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.21"
          }
        }
      ],
      "files": [
        {
          "name": "kotlin-compose-schema-jvm-0.10.0.jar",
          "url": "kotlin-compose-schema-jvm-0.10.0.jar",
          "size": 143059,
          "sha512": "0e0fb1aced9b6ee8e2b8ca75ae8b1d2059958400f2813596281c2819e09f0f0e694981db4a21a30b5bbb2b1a2ee57b6082bd2f7b160bd844cc47a41f5a68aeb4",
          "sha256": "a363a72879876cfed06be94469cca133fcaedaae9029033cf9ea6d3a50f40d54",
          "sha1": "8efed3e4d9e861b2181b1986603601485afa630e",
          "md5": "4938a3a0c52f912dfec81b64a4b7f84d"
        }
      ]
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.21"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.11.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-datetime",
          "version": {
            "requires": "0.7.1"
          }
        }
      ],
      "files": [
        {
          "name": "kotlin-compose-schema-jvm-0.10.0.jar",
          "url": "kotlin-compose-schema-jvm-0.10.0.jar",
          "size": 143059,
          "sha512": "0e0fb1aced9b6ee8e2b8ca75ae8b1d2059958400f2813596281c2819e09f0f0e694981db4a21a30b5bbb2b1a2ee57b6082bd2f7b160bd844cc47a41f5a68aeb4",
          "sha256": "a363a72879876cfed06be94469cca133fcaedaae9029033cf9ea6d3a50f40d54",
          "sha1": "8efed3e4d9e861b2181b1986603601485afa630e",
          "md5": "4938a3a0c52f912dfec81b64a4b7f84d"
        }
      ]
    },
    {
      "name": "jvmSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "kotlin-compose-schema-jvm-0.10.0-sources.jar",
          "url": "kotlin-compose-schema-jvm-0.10.0-sources.jar",
          "size": 10001,
          "sha512": "71cec9d5887d8c8550ef4f906682c9132c7f5c113b54a19b2cab1f702ab714693db442e4ec6308070795d47a25976d72d12638f368a0fb9b42b198d33e43d898",
          "sha256": "f7c01cbaa1bdaea32adcfe422e834bd8a159d7552b9f210042929c82ad087f32",
          "sha1": "f4b105061fc01c35414b5766a1200f469695849b",
          "md5": "129b40ea92cc22a10556906f7c1ac502"
        }
      ]
    }
  ]
}
