{
  "formatVersion": "1.1",
  "component": {
    "url": "../../kotlin-compose-schema/0.13.1/kotlin-compose-schema-0.13.1.module",
    "group": "ai.factoredui",
    "module": "kotlin-compose-schema",
    "version": "0.13.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14"
    }
  },
  "variants": [
    {
      "name": "wasmJsApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "wasm",
        "org.jetbrains.kotlin.wasm.target": "js"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.21"
          }
        }
      ],
      "files": [
        {
          "name": "kotlin-compose-schema-wasm-js-0.13.1.klib",
          "url": "kotlin-compose-schema-wasm-js-0.13.1.klib",
          "size": 102192,
          "sha512": "8f191c69c1f84e5c42f24ddf12f82e3d87f115ccfc8248323214868e61c91019df31bf6b43fda7076169e715ce8ecfde83afd906c82dbd8709dde96cb2fd1725",
          "sha256": "287d33b5fb22df12a55992a5896517d3b6be979826d630642e1fb16975eb1226",
          "sha1": "9307b8f9ab2c995f94889e5b0eea308339651c2e",
          "md5": "300086004f57eeffc2746ba40c1ce679"
        }
      ]
    },
    {
      "name": "wasmJsRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.platform.type": "wasm",
        "org.jetbrains.kotlin.wasm.target": "js"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.21"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.11.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-datetime",
          "version": {
            "requires": "0.7.1"
          }
        }
      ],
      "files": [
        {
          "name": "kotlin-compose-schema-wasm-js-0.13.1.klib",
          "url": "kotlin-compose-schema-wasm-js-0.13.1.klib",
          "size": 102192,
          "sha512": "8f191c69c1f84e5c42f24ddf12f82e3d87f115ccfc8248323214868e61c91019df31bf6b43fda7076169e715ce8ecfde83afd906c82dbd8709dde96cb2fd1725",
          "sha256": "287d33b5fb22df12a55992a5896517d3b6be979826d630642e1fb16975eb1226",
          "sha1": "9307b8f9ab2c995f94889e5b0eea308339651c2e",
          "md5": "300086004f57eeffc2746ba40c1ce679"
        }
      ]
    },
    {
      "name": "wasmJsSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.platform.type": "wasm",
        "org.jetbrains.kotlin.wasm.target": "js"
      },
      "files": [
        {
          "name": "kotlin-compose-schema-wasm-js-0.13.1-sources.jar",
          "url": "kotlin-compose-schema-wasm-js-0.13.1-sources.jar",
          "size": 10453,
          "sha512": "3fbb28a198d7de5ca01ed32f9501092fac1b6af51a9b0098c21108f5a5c0608e92c3bd97c5b73aba71a264a999817927b4ebb13dae14cfabad9be095964ba1cc",
          "sha256": "a0966f1f9d3e6583b8dcf8432881a0902108e4151fa59a8d8b62084378017fe3",
          "sha1": "5013c85243b90636719264022c566aa65725c334",
          "md5": "f46850ca8f5deae24a974bcf4cc1901b"
        }
      ]
    }
  ]
}
