{
  "formatVersion": "1.1",
  "component": {
    "url": "../../kotlin-compose/0.18.0/kotlin-compose-0.18.0.module",
    "group": "ai.factoredui",
    "module": "kotlin-compose",
    "version": "0.18.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14"
    }
  },
  "variants": [
    {
      "name": "releaseApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "ai.factoredui",
          "module": "kotlin-compose-schema",
          "version": {
            "requires": "0.18.0"
          }
        },
        {
          "group": "ai.factoredui",
          "module": "kotlin-compose-capture",
          "version": {
            "requires": "0.18.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.21"
          }
        }
      ],
      "files": [
        {
          "name": "kotlin-compose-release.aar",
          "url": "kotlin-compose-android-0.18.0.aar",
          "size": 589832,
          "sha512": "20b73c6a8cb2bea061aadf374bf8fa5d6c9ca6a2a516a9de43f0339f1fb3d3f43ebbc92e2d39d6407c6fdc80e0eece9fedc48797cf0af398800a7da4a7609683",
          "sha256": "e8131f00570d1233d1e874d654439373753bdadbfbea0ae660dc9867e77cec79",
          "sha1": "ccc9c4f9199a22962b5448a42c460e61a05cbf3c",
          "md5": "460f406c8d942bf2f05fd72aadafad71"
        }
      ]
    },
    {
      "name": "releaseRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "androidx.activity",
          "module": "activity-compose",
          "version": {
            "requires": "1.9.3"
          },
          "excludes": [
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-annotations-common"
            }
          ]
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-okhttp",
          "version": {
            "requires": "3.2.4"
          },
          "excludes": [
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-annotations-common"
            }
          ]
        },
        {
          "group": "ai.factoredui",
          "module": "kotlin-compose-schema",
          "version": {
            "requires": "0.18.0"
          },
          "excludes": [
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-annotations-common"
            }
          ]
        },
        {
          "group": "ai.factoredui",
          "module": "kotlin-compose-capture",
          "version": {
            "requires": "0.18.0"
          },
          "excludes": [
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-annotations-common"
            }
          ]
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.21"
          },
          "excludes": [
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-annotations-common"
            }
          ]
        },
        {
          "group": "org.jetbrains.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "1.10.3"
          },
          "excludes": [
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-annotations-common"
            }
          ]
        },
        {
          "group": "org.jetbrains.compose.foundation",
          "module": "foundation",
          "version": {
            "requires": "1.10.3"
          },
          "excludes": [
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-annotations-common"
            }
          ]
        },
        {
          "group": "org.jetbrains.compose.material3",
          "module": "material3",
          "version": {
            "requires": "1.9.0-beta03"
          },
          "excludes": [
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-annotations-common"
            }
          ]
        },
        {
          "group": "org.jetbrains.compose.ui",
          "module": "ui",
          "version": {
            "requires": "1.10.3"
          },
          "excludes": [
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-annotations-common"
            }
          ]
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.11.0"
          },
          "excludes": [
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-annotations-common"
            }
          ]
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.10.2"
          },
          "excludes": [
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-annotations-common"
            }
          ]
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-datetime",
          "version": {
            "requires": "0.7.1"
          },
          "excludes": [
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-annotations-common"
            }
          ]
        },
        {
          "group": "io.coil-kt.coil3",
          "module": "coil-compose",
          "version": {
            "requires": "3.2.0"
          },
          "excludes": [
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-annotations-common"
            }
          ]
        },
        {
          "group": "io.coil-kt.coil3",
          "module": "coil-network-ktor3",
          "version": {
            "requires": "3.2.0"
          },
          "excludes": [
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-annotations-common"
            }
          ]
        },
        {
          "group": "io.coil-kt.coil3",
          "module": "coil-svg",
          "version": {
            "requires": "3.2.0"
          },
          "excludes": [
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-annotations-common"
            }
          ]
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-core",
          "version": {
            "requires": "3.2.4"
          },
          "excludes": [
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-annotations-common"
            }
          ]
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-content-negotiation",
          "version": {
            "requires": "3.2.4"
          },
          "excludes": [
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-annotations-common"
            }
          ]
        },
        {
          "group": "io.ktor",
          "module": "ktor-serialization-kotlinx-json",
          "version": {
            "requires": "3.2.4"
          },
          "excludes": [
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-annotations-common"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "kotlin-compose-release.aar",
          "url": "kotlin-compose-android-0.18.0.aar",
          "size": 589832,
          "sha512": "20b73c6a8cb2bea061aadf374bf8fa5d6c9ca6a2a516a9de43f0339f1fb3d3f43ebbc92e2d39d6407c6fdc80e0eece9fedc48797cf0af398800a7da4a7609683",
          "sha256": "e8131f00570d1233d1e874d654439373753bdadbfbea0ae660dc9867e77cec79",
          "sha1": "ccc9c4f9199a22962b5448a42c460e61a05cbf3c",
          "md5": "460f406c8d942bf2f05fd72aadafad71"
        }
      ]
    },
    {
      "name": "releaseSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "android",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "files": [
        {
          "name": "kotlin-compose-android-0.18.0-sources.jar",
          "url": "kotlin-compose-android-0.18.0-sources.jar",
          "size": 73794,
          "sha512": "b79ef87b9357ea214a11d2b1f94f95bf4e7183893bb4e90a984a2d806e374fb8d18b07c406f042d86636d334ec4f1f2423399731afb58ff4183314b4933d5277",
          "sha256": "3eb66341779553574f58fb3e7d2eec26b2489fde6264361339400ccf8d203c4b",
          "sha1": "2d489dfe1083f8d09a52def1aacee1ddc9ae1d84",
          "md5": "da0d1f9f3a90071a6dc4ae452e36c12c"
        }
      ]
    }
  ]
}
