{
  "formatVersion": "1.1",
  "component": {
    "url": "../../kotlin-compose-schema/0.13.2/kotlin-compose-schema-0.13.2.module",
    "group": "ai.factoredui",
    "module": "kotlin-compose-schema",
    "version": "0.13.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14"
    }
  },
  "variants": [
    {
      "name": "iosSimulatorArm64ApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.21"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.11.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-datetime",
          "version": {
            "requires": "0.7.1"
          }
        }
      ],
      "files": [
        {
          "name": "kotlin-compose-schema-iosSimulatorArm64Main-0.13.2.klib",
          "url": "kotlin-compose-schema-iossimulatorarm64-0.13.2.klib",
          "size": 106276,
          "sha512": "8e422fe0e9540e3701774f37553f0211a5b593189d944c85b4f877d1ccc2f5c2a58aecc198383575ed213103a0060248df2f8a15e24b36b1bfb3ba6b32b8881d",
          "sha256": "b5a8445845f83376ba8fc8195c0b3917c40316066b419c288533c55d2abc96d7",
          "sha1": "0950540223de8c4adb93e798f5fc1c8635f81472",
          "md5": "6e436776a62b62b6da17340dcbcfe1d3"
        }
      ]
    },
    {
      "name": "iosSimulatorArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "files": [
        {
          "name": "kotlin-compose-schema-iossimulatorarm64-0.13.2-sources.jar",
          "url": "kotlin-compose-schema-iossimulatorarm64-0.13.2-sources.jar",
          "size": 10453,
          "sha512": "3fbb28a198d7de5ca01ed32f9501092fac1b6af51a9b0098c21108f5a5c0608e92c3bd97c5b73aba71a264a999817927b4ebb13dae14cfabad9be095964ba1cc",
          "sha256": "a0966f1f9d3e6583b8dcf8432881a0902108e4151fa59a8d8b62084378017fe3",
          "sha1": "5013c85243b90636719264022c566aa65725c334",
          "md5": "f46850ca8f5deae24a974bcf4cc1901b"
        }
      ]
    },
    {
      "name": "iosSimulatorArm64MetadataElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.21"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.11.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-datetime",
          "version": {
            "requires": "0.7.1"
          }
        }
      ],
      "files": [
        {
          "name": "kotlin-compose-schema-iossimulatorarm64-0.13.2-metadata.jar",
          "url": "kotlin-compose-schema-iossimulatorarm64-0.13.2-metadata.jar",
          "size": 261,
          "sha512": "24e78c94c9d5826f2c380be14b6ea9d47d18f3ee3260422857ae6b566454f42f48a2cddf994c4d1228d59dff54da9237baf5b4936440d252398b5aa5b50e28c9",
          "sha256": "2702e4442c289999e4cd4690cb301236e52c41db276c9fcc241a5725c7d635a2",
          "sha1": "59bde2a1856369381098cdff3892c124639847cf",
          "md5": "22cfbea5d5d229b5c0f202a43fe01456"
        }
      ]
    }
  ]
}
