{
  "formatVersion": "1.1",
  "component": {
    "url": "../../kotlin-compose-schema/0.17.1/kotlin-compose-schema-0.17.1.module",
    "group": "ai.factoredui",
    "module": "kotlin-compose-schema",
    "version": "0.17.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14"
    }
  },
  "variants": [
    {
      "name": "iosArm64ApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.21"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.11.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-datetime",
          "version": {
            "requires": "0.7.1"
          }
        }
      ],
      "files": [
        {
          "name": "kotlin-compose-schema-iosArm64Main-0.17.1.klib",
          "url": "kotlin-compose-schema-iosarm64-0.17.1.klib",
          "size": 112045,
          "sha512": "6a0bf526c639f396ae562de3b9bb06df27788f38caa69bbf7dd913152fba471aa04f6e59d9a37f502f8b511b1de5743457ad562f63bdfe904b87616877496b15",
          "sha256": "c67fc5e74cdcff1d0bb892d5495a1a1ac8b5283f66971177fe646eb0f260680e",
          "sha1": "6f034e2e434f082f8e1346356c2946815e296acf",
          "md5": "3ed94b4eee4e7a5266ec4225f10caee1"
        }
      ]
    },
    {
      "name": "iosArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "files": [
        {
          "name": "kotlin-compose-schema-iosarm64-0.17.1-sources.jar",
          "url": "kotlin-compose-schema-iosarm64-0.17.1-sources.jar",
          "size": 11046,
          "sha512": "cae4c08ab3f9a8344d54c7e0e4fa9269ea8da377662bc4064d80a2cd79f09fee86747b36290041c447b7ad05a090b3b7bcfbbd8da350247fd6ee8dcdd79d58e9",
          "sha256": "ed1a6fb4bff7ef3d57fa32ea9d4747fa020577883dfc09c1f4431e7d0ca4534d",
          "sha1": "aef338a946cb47d02cec2a29e4662c43516a06c2",
          "md5": "96bcd168f6e86923ea03d2264bc834ae"
        }
      ]
    },
    {
      "name": "iosArm64MetadataElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.21"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.11.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-datetime",
          "version": {
            "requires": "0.7.1"
          }
        }
      ],
      "files": [
        {
          "name": "kotlin-compose-schema-iosarm64-0.17.1-metadata.jar",
          "url": "kotlin-compose-schema-iosarm64-0.17.1-metadata.jar",
          "size": 261,
          "sha512": "63ce8385ec6aa3d2956c827e98a745f37df334af57096ec24804b3fb07c359ac4b8fcfdbf1be019c19c77c0613f47a99b974a77a356bbf1188ead07166db2dff",
          "sha256": "bd2457976f9f9417407c2bf477db23a283016d1462808bfdd76ab4652401fdcf",
          "sha1": "beed38b374acfea949b62adce384381a4c734685",
          "md5": "a11cde1fb196edf3726531d14ad021e9"
        }
      ]
    }
  ]
}
