{
  "formatVersion": "1.1",
  "component": {
    "url": "../../kotlin-compose-schema/0.17.1/kotlin-compose-schema-0.17.1.module",
    "group": "ai.factoredui",
    "module": "kotlin-compose-schema",
    "version": "0.17.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14"
    }
  },
  "variants": [
    {
      "name": "iosX64ApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.21"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.11.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-datetime",
          "version": {
            "requires": "0.7.1"
          }
        }
      ],
      "files": [
        {
          "name": "kotlin-compose-schema-iosX64Main-0.17.1.klib",
          "url": "kotlin-compose-schema-iosx64-0.17.1.klib",
          "size": 112033,
          "sha512": "fd9fd22ee02861105bfe1d42aba1578eabfef6a1108d4adbfb8a1d936cdc89646836c8b54b945c8579ccda400092c2a5b114add24ead6af208075ce4e47f3329",
          "sha256": "beaaf7765ae4434090a24c00f38c0bf2b18f6475ba046b4786f7ea56a367bf2e",
          "sha1": "8666a6d3f637e4bc349178056a19ad752257f1c8",
          "md5": "6de1191662e9abe782c68ef77fcf3671"
        }
      ]
    },
    {
      "name": "iosX64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "files": [
        {
          "name": "kotlin-compose-schema-iosx64-0.17.1-sources.jar",
          "url": "kotlin-compose-schema-iosx64-0.17.1-sources.jar",
          "size": 11046,
          "sha512": "cae4c08ab3f9a8344d54c7e0e4fa9269ea8da377662bc4064d80a2cd79f09fee86747b36290041c447b7ad05a090b3b7bcfbbd8da350247fd6ee8dcdd79d58e9",
          "sha256": "ed1a6fb4bff7ef3d57fa32ea9d4747fa020577883dfc09c1f4431e7d0ca4534d",
          "sha1": "aef338a946cb47d02cec2a29e4662c43516a06c2",
          "md5": "96bcd168f6e86923ea03d2264bc834ae"
        }
      ]
    },
    {
      "name": "iosX64MetadataElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.21"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.11.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-datetime",
          "version": {
            "requires": "0.7.1"
          }
        }
      ],
      "files": [
        {
          "name": "kotlin-compose-schema-iosx64-0.17.1-metadata.jar",
          "url": "kotlin-compose-schema-iosx64-0.17.1-metadata.jar",
          "size": 261,
          "sha512": "63ce8385ec6aa3d2956c827e98a745f37df334af57096ec24804b3fb07c359ac4b8fcfdbf1be019c19c77c0613f47a99b974a77a356bbf1188ead07166db2dff",
          "sha256": "bd2457976f9f9417407c2bf477db23a283016d1462808bfdd76ab4652401fdcf",
          "sha1": "beed38b374acfea949b62adce384381a4c734685",
          "md5": "a11cde1fb196edf3726531d14ad021e9"
        }
      ]
    }
  ]
}
