{
  "formatVersion": "1.1",
  "component": {
    "url": "../../kotlin-compose-schema/0.15.4/kotlin-compose-schema-0.15.4.module",
    "group": "ai.factoredui",
    "module": "kotlin-compose-schema",
    "version": "0.15.4",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14"
    }
  },
  "variants": [
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.21"
          }
        }
      ],
      "files": [
        {
          "name": "kotlin-compose-schema-jvm-0.15.4.jar",
          "url": "kotlin-compose-schema-jvm-0.15.4.jar",
          "size": 156686,
          "sha512": "f9ea27be4560cc4eb316f7c4acfad8dd0ad177d1942465caa62c0fa6cb9c6b3914e2ac14ceb775c8eab53d0090d20cc92f3c8590509e4a61513e0494663bb243",
          "sha256": "d143b2101f5023343a55b0b358d04446a6db7139c8bd08d7929986ec5561e57b",
          "sha1": "6364f680b623a47bd77e75f9c28082897d849905",
          "md5": "f287534107ca2523a7f9680b2d46a15f"
        }
      ]
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.21"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.11.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-datetime",
          "version": {
            "requires": "0.7.1"
          }
        }
      ],
      "files": [
        {
          "name": "kotlin-compose-schema-jvm-0.15.4.jar",
          "url": "kotlin-compose-schema-jvm-0.15.4.jar",
          "size": 156686,
          "sha512": "f9ea27be4560cc4eb316f7c4acfad8dd0ad177d1942465caa62c0fa6cb9c6b3914e2ac14ceb775c8eab53d0090d20cc92f3c8590509e4a61513e0494663bb243",
          "sha256": "d143b2101f5023343a55b0b358d04446a6db7139c8bd08d7929986ec5561e57b",
          "sha1": "6364f680b623a47bd77e75f9c28082897d849905",
          "md5": "f287534107ca2523a7f9680b2d46a15f"
        }
      ]
    },
    {
      "name": "jvmSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "kotlin-compose-schema-jvm-0.15.4-sources.jar",
          "url": "kotlin-compose-schema-jvm-0.15.4-sources.jar",
          "size": 11588,
          "sha512": "5e28f9bc1fcae12211469a8e00b90cebd2610c98990274989efc47861ffe49584e0866fbc69b64e701bc710db1771905a843e192c5c4a363eb150652457571d6",
          "sha256": "fa33044056bee36340dfa96ecf7fe89c2ceea9ef3b834e81859f55f3fb90693f",
          "sha1": "5b2f15d3c6ae43a4f51694f196ed5d83349cac80",
          "md5": "06bc1eb9a2fe76aa52bc389e5caaaf5f"
        }
      ]
    }
  ]
}
