{
  "formatVersion": "1.1",
  "component": {
    "url": "../../kotlin-compose-schema/0.19.0/kotlin-compose-schema-0.19.0.module",
    "group": "ai.factoredui",
    "module": "kotlin-compose-schema",
    "version": "0.19.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14"
    }
  },
  "variants": [
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.21"
          }
        }
      ],
      "files": [
        {
          "name": "kotlin-compose-schema-jvm-0.19.0.jar",
          "url": "kotlin-compose-schema-jvm-0.19.0.jar",
          "size": 149918,
          "sha512": "ec8c3421e6a09eecf0ecd7f4ecfae26e6ddbc6dcce7d5a7878a826369b8b258c7af20ab070587b8c79e88c0d653f453bcc216b3dd91e8756a7b8e324bd9e8724",
          "sha256": "088b5b30b62f2d3808d4460c5e2624a1808f647e625376043f9b1bd20092f87a",
          "sha1": "a566218ec1d97a8429a5bc69befdd02b1dc7b3e6",
          "md5": "7d85d7803f92cd2491915a0a3a3b3c7c"
        }
      ]
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.21"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.11.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-datetime",
          "version": {
            "requires": "0.7.1"
          }
        }
      ],
      "files": [
        {
          "name": "kotlin-compose-schema-jvm-0.19.0.jar",
          "url": "kotlin-compose-schema-jvm-0.19.0.jar",
          "size": 149918,
          "sha512": "ec8c3421e6a09eecf0ecd7f4ecfae26e6ddbc6dcce7d5a7878a826369b8b258c7af20ab070587b8c79e88c0d653f453bcc216b3dd91e8756a7b8e324bd9e8724",
          "sha256": "088b5b30b62f2d3808d4460c5e2624a1808f647e625376043f9b1bd20092f87a",
          "sha1": "a566218ec1d97a8429a5bc69befdd02b1dc7b3e6",
          "md5": "7d85d7803f92cd2491915a0a3a3b3c7c"
        }
      ]
    },
    {
      "name": "jvmSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "kotlin-compose-schema-jvm-0.19.0-sources.jar",
          "url": "kotlin-compose-schema-jvm-0.19.0-sources.jar",
          "size": 11244,
          "sha512": "4f4fab68f47ca454347578d19a8686b5dc6d91880e982fd2ad2b00f30766de0e444f09cb6f94ced0f2cbd5a2748258be422665dcbc86dba910198bae1d2e7e23",
          "sha256": "98d201c5535c8ec3512dab69330bbbe3c2c19592d3a076c1131fc37ff0739ac7",
          "sha1": "f90a56dd668840053b36c36fb9bfaafba11c0ab9",
          "md5": "93f15f553e8b647097b619e1e104df7c"
        }
      ]
    }
  ]
}
