{
  "formatVersion": "1.1",
  "component": {
    "url": "../../kotlin-compose-schema/0.20.2/kotlin-compose-schema-0.20.2.module",
    "group": "ai.factoredui",
    "module": "kotlin-compose-schema",
    "version": "0.20.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14"
    }
  },
  "variants": [
    {
      "name": "wasmJsApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "wasm",
        "org.jetbrains.kotlin.wasm.target": "js"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.21"
          }
        }
      ],
      "files": [
        {
          "name": "kotlin-compose-schema-wasm-js-0.20.2.klib",
          "url": "kotlin-compose-schema-wasm-js-0.20.2.klib",
          "size": 127846,
          "sha512": "3f3a90a6b895193232f4b6d427fb00aa26282b04bd082cb2eecbf1c440b29c05dd55f9137e4c41a5b60caa4af7da854363976fc54b08464608cb5cf7838f235d",
          "sha256": "1bfb07f61283ee69b921fa26e293f8cba6a661c209a7fb61904b60a7d298fd6c",
          "sha1": "78d6fb0f5e3b02c76c5afcf5cbc5e14b87da8038",
          "md5": "4940363e515e21fc635ff5bf27c6bbe3"
        }
      ]
    },
    {
      "name": "wasmJsRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.platform.type": "wasm",
        "org.jetbrains.kotlin.wasm.target": "js"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.21"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.11.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-datetime",
          "version": {
            "requires": "0.7.1"
          }
        }
      ],
      "files": [
        {
          "name": "kotlin-compose-schema-wasm-js-0.20.2.klib",
          "url": "kotlin-compose-schema-wasm-js-0.20.2.klib",
          "size": 127846,
          "sha512": "3f3a90a6b895193232f4b6d427fb00aa26282b04bd082cb2eecbf1c440b29c05dd55f9137e4c41a5b60caa4af7da854363976fc54b08464608cb5cf7838f235d",
          "sha256": "1bfb07f61283ee69b921fa26e293f8cba6a661c209a7fb61904b60a7d298fd6c",
          "sha1": "78d6fb0f5e3b02c76c5afcf5cbc5e14b87da8038",
          "md5": "4940363e515e21fc635ff5bf27c6bbe3"
        }
      ]
    },
    {
      "name": "wasmJsSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.platform.type": "wasm",
        "org.jetbrains.kotlin.wasm.target": "js"
      },
      "files": [
        {
          "name": "kotlin-compose-schema-wasm-js-0.20.2-sources.jar",
          "url": "kotlin-compose-schema-wasm-js-0.20.2-sources.jar",
          "size": 12227,
          "sha512": "5db475c4b75a6cc059c089fcf69d18564941622e5a810c8f3fdde229351edc07975303b83f2edfd9da46d15a48aea3d9f271f9afbe21b858914f06fe34feffe7",
          "sha256": "d4edad5c0c1cbc5e0fb2f061b7c94c482e244a006cab0f66be88b71caa346434",
          "sha1": "7df2897c68f265f63bc65f877a394cb724681794",
          "md5": "2f93944aaafde82ab59bffdf39087647"
        }
      ]
    }
  ]
}
