{
  "formatVersion": "1.1",
  "component": {
    "url": "../../kotlin-compose/0.5.1/kotlin-compose-0.5.1.module",
    "group": "ai.factoredui",
    "module": "kotlin-compose",
    "version": "0.5.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.10.2"
    }
  },
  "variants": [
    {
      "name": "desktopApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.21"
          }
        }
      ],
      "files": [
        {
          "name": "kotlin-compose-desktop-0.5.1.jar",
          "url": "kotlin-compose-desktop-0.5.1.jar",
          "size": 424868,
          "sha512": "7bc0fee063a6af09a50c23999d5f62243ca9c68eebbc38be5ba3f7f0610e36aed9bbfcbf0036f5821c2db323754566884c21183639ee8a71d11844363774b40d",
          "sha256": "ae35ff8c4e24055364e0d0845a843f3ba92bb9f32b761832bd33b2f96b63e965",
          "sha1": "4f20b806f5f785b9a9d1ebb73466ff496ff44b01",
          "md5": "eab49eae83af5c218bd8931227ee82df"
        }
      ]
    },
    {
      "name": "desktopRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.21"
          }
        },
        {
          "group": "org.jetbrains.compose.desktop",
          "module": "desktop-jvm-linux-x64",
          "version": {
            "requires": "1.7.3"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-okhttp",
          "version": {
            "requires": "3.0.3"
          }
        },
        {
          "group": "org.jetbrains.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "1.7.3"
          }
        },
        {
          "group": "org.jetbrains.compose.foundation",
          "module": "foundation",
          "version": {
            "requires": "1.7.3"
          }
        },
        {
          "group": "org.jetbrains.compose.material3",
          "module": "material3",
          "version": {
            "requires": "1.7.3"
          }
        },
        {
          "group": "org.jetbrains.compose.ui",
          "module": "ui",
          "version": {
            "requires": "1.7.3"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.7.3"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-datetime",
          "version": {
            "requires": "0.6.1"
          }
        },
        {
          "group": "io.coil-kt.coil3",
          "module": "coil-compose",
          "version": {
            "requires": "3.0.4"
          }
        },
        {
          "group": "io.coil-kt.coil3",
          "module": "coil-network-ktor3",
          "version": {
            "requires": "3.0.4"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-core",
          "version": {
            "requires": "3.0.3"
          }
        }
      ],
      "files": [
        {
          "name": "kotlin-compose-desktop-0.5.1.jar",
          "url": "kotlin-compose-desktop-0.5.1.jar",
          "size": 424868,
          "sha512": "7bc0fee063a6af09a50c23999d5f62243ca9c68eebbc38be5ba3f7f0610e36aed9bbfcbf0036f5821c2db323754566884c21183639ee8a71d11844363774b40d",
          "sha256": "ae35ff8c4e24055364e0d0845a843f3ba92bb9f32b761832bd33b2f96b63e965",
          "sha1": "4f20b806f5f785b9a9d1ebb73466ff496ff44b01",
          "md5": "eab49eae83af5c218bd8931227ee82df"
        }
      ]
    },
    {
      "name": "desktopSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "kotlin-compose-desktop-0.5.1-sources.jar",
          "url": "kotlin-compose-desktop-0.5.1-sources.jar",
          "size": 48674,
          "sha512": "5d1a4d874bb988f6df2abb1e85b36393bf060e664569cad3e7e0c7f539aa5d35339391c769cd7903f83778c660f0d77f8ba53611e6cdefd0dcf023040c118e6b",
          "sha256": "c8a1733914a1da191491a1144eb5c00954cc4115e65cb21d788fcca2b91ec0e2",
          "sha1": "a1829b70e9da1a426a754bc131b288d9f2673ae0",
          "md5": "45bbd8fe998256db19128be787b84129"
        }
      ]
    }
  ]
}
