{
  "formatVersion": "1.1",
  "component": {
    "url": "../../kotlin-compose/0.21.0/kotlin-compose-0.21.0.module",
    "group": "ai.factoredui",
    "module": "kotlin-compose",
    "version": "0.21.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14"
    }
  },
  "variants": [
    {
      "name": "desktopApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "ai.factoredui",
          "module": "kotlin-compose-schema",
          "version": {
            "requires": "0.21.0"
          }
        },
        {
          "group": "ai.factoredui",
          "module": "kotlin-compose-capture",
          "version": {
            "requires": "0.21.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.21"
          }
        }
      ],
      "files": [
        {
          "name": "kotlin-compose-desktop-0.21.0.jar",
          "url": "kotlin-compose-desktop-0.21.0.jar",
          "size": 996310,
          "sha512": "32d51a8cfa27211c30dc1ca2fbb415faa580296ea93ea920de04f8ed543dda2246212a6aab9c711dd570c66cbedcf06dbce021b71abfeff9ee14a07daaf1a7ea",
          "sha256": "59ac999ef365c3c0c513406ba73e3efbdb5246166ef64f3e5d90488618e89960",
          "sha1": "05d071910f51611340f1e9ca03d16f14f3e372d3",
          "md5": "ec3f09989f0fbac03e521bd06cfe2bb1"
        }
      ]
    },
    {
      "name": "desktopRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "ai.factoredui",
          "module": "kotlin-compose-schema",
          "version": {
            "requires": "0.21.0"
          }
        },
        {
          "group": "ai.factoredui",
          "module": "kotlin-compose-capture",
          "version": {
            "requires": "0.21.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.21"
          }
        },
        {
          "group": "org.jetbrains.compose.desktop",
          "module": "desktop",
          "version": {
            "requires": "1.10.3"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-okhttp",
          "version": {
            "requires": "3.2.4"
          }
        },
        {
          "group": "org.jetbrains.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "1.10.3"
          }
        },
        {
          "group": "org.jetbrains.compose.foundation",
          "module": "foundation",
          "version": {
            "requires": "1.10.3"
          }
        },
        {
          "group": "org.jetbrains.compose.material3",
          "module": "material3",
          "version": {
            "requires": "1.9.0-beta03"
          }
        },
        {
          "group": "org.jetbrains.compose.ui",
          "module": "ui",
          "version": {
            "requires": "1.10.3"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.11.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.10.2"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-datetime",
          "version": {
            "requires": "0.7.1"
          }
        },
        {
          "group": "io.coil-kt.coil3",
          "module": "coil-compose",
          "version": {
            "requires": "3.2.0"
          }
        },
        {
          "group": "io.coil-kt.coil3",
          "module": "coil-network-ktor3",
          "version": {
            "requires": "3.2.0"
          }
        },
        {
          "group": "io.coil-kt.coil3",
          "module": "coil-svg",
          "version": {
            "requires": "3.2.0"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-core",
          "version": {
            "requires": "3.2.4"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-content-negotiation",
          "version": {
            "requires": "3.2.4"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-serialization-kotlinx-json",
          "version": {
            "requires": "3.2.4"
          }
        }
      ],
      "files": [
        {
          "name": "kotlin-compose-desktop-0.21.0.jar",
          "url": "kotlin-compose-desktop-0.21.0.jar",
          "size": 996310,
          "sha512": "32d51a8cfa27211c30dc1ca2fbb415faa580296ea93ea920de04f8ed543dda2246212a6aab9c711dd570c66cbedcf06dbce021b71abfeff9ee14a07daaf1a7ea",
          "sha256": "59ac999ef365c3c0c513406ba73e3efbdb5246166ef64f3e5d90488618e89960",
          "sha1": "05d071910f51611340f1e9ca03d16f14f3e372d3",
          "md5": "ec3f09989f0fbac03e521bd06cfe2bb1"
        }
      ]
    },
    {
      "name": "desktopSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "kotlin-compose-desktop-0.21.0-sources.jar",
          "url": "kotlin-compose-desktop-0.21.0-sources.jar",
          "size": 122359,
          "sha512": "2e2d313167d102e903abb39a510f42aaee638e2b7b23d2f88e8d3370f25e608c9f2c00bc2306a91755c24de83e8492286f0825ca340af04ba671b602aea8c7ff",
          "sha256": "c1ba7046a03883e2e862338b38784d2260f3116842361120c6314f2bb2bbf6b6",
          "sha1": "42b64686f5875cc8d47c86f96f11148c2716a5f7",
          "md5": "8f3b8f016b4ce6aeb22274c0c505ec42"
        }
      ]
    }
  ]
}
