{
  "formatVersion": "1.1",
  "component": {
    "url": "../../kotlin-compose/0.20.0/kotlin-compose-0.20.0.module",
    "group": "ai.factoredui",
    "module": "kotlin-compose",
    "version": "0.20.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14"
    }
  },
  "variants": [
    {
      "name": "desktopApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "ai.factoredui",
          "module": "kotlin-compose-schema",
          "version": {
            "requires": "0.20.0"
          }
        },
        {
          "group": "ai.factoredui",
          "module": "kotlin-compose-capture",
          "version": {
            "requires": "0.20.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.21"
          }
        }
      ],
      "files": [
        {
          "name": "kotlin-compose-desktop-0.20.0.jar",
          "url": "kotlin-compose-desktop-0.20.0.jar",
          "size": 831241,
          "sha512": "b7320b45bfe92c8ddbdd037092cf16ce14fca543d12bac13908f720159b0ae503d341542d32fdd2b15522acdd1e154abcf31872acd336e311ec4287f09f82a7f",
          "sha256": "2b016a3884e353277ec40e2e783bec8fb5b3c94cef88c82a925872a264aa2783",
          "sha1": "175d475347a9867a8abc8dec3ffb49992328f627",
          "md5": "fb8dd9a1247558ece82e7ac6337285fb"
        }
      ]
    },
    {
      "name": "desktopRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "ai.factoredui",
          "module": "kotlin-compose-schema",
          "version": {
            "requires": "0.20.0"
          }
        },
        {
          "group": "ai.factoredui",
          "module": "kotlin-compose-capture",
          "version": {
            "requires": "0.20.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.21"
          }
        },
        {
          "group": "org.jetbrains.compose.desktop",
          "module": "desktop",
          "version": {
            "requires": "1.10.3"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-okhttp",
          "version": {
            "requires": "3.2.4"
          }
        },
        {
          "group": "org.jetbrains.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "1.10.3"
          }
        },
        {
          "group": "org.jetbrains.compose.foundation",
          "module": "foundation",
          "version": {
            "requires": "1.10.3"
          }
        },
        {
          "group": "org.jetbrains.compose.material3",
          "module": "material3",
          "version": {
            "requires": "1.9.0-beta03"
          }
        },
        {
          "group": "org.jetbrains.compose.ui",
          "module": "ui",
          "version": {
            "requires": "1.10.3"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.11.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.10.2"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-datetime",
          "version": {
            "requires": "0.7.1"
          }
        },
        {
          "group": "io.coil-kt.coil3",
          "module": "coil-compose",
          "version": {
            "requires": "3.2.0"
          }
        },
        {
          "group": "io.coil-kt.coil3",
          "module": "coil-network-ktor3",
          "version": {
            "requires": "3.2.0"
          }
        },
        {
          "group": "io.coil-kt.coil3",
          "module": "coil-svg",
          "version": {
            "requires": "3.2.0"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-core",
          "version": {
            "requires": "3.2.4"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-content-negotiation",
          "version": {
            "requires": "3.2.4"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-serialization-kotlinx-json",
          "version": {
            "requires": "3.2.4"
          }
        }
      ],
      "files": [
        {
          "name": "kotlin-compose-desktop-0.20.0.jar",
          "url": "kotlin-compose-desktop-0.20.0.jar",
          "size": 831241,
          "sha512": "b7320b45bfe92c8ddbdd037092cf16ce14fca543d12bac13908f720159b0ae503d341542d32fdd2b15522acdd1e154abcf31872acd336e311ec4287f09f82a7f",
          "sha256": "2b016a3884e353277ec40e2e783bec8fb5b3c94cef88c82a925872a264aa2783",
          "sha1": "175d475347a9867a8abc8dec3ffb49992328f627",
          "md5": "fb8dd9a1247558ece82e7ac6337285fb"
        }
      ]
    },
    {
      "name": "desktopSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "kotlin-compose-desktop-0.20.0-sources.jar",
          "url": "kotlin-compose-desktop-0.20.0-sources.jar",
          "size": 101112,
          "sha512": "f6746ba2a1a95e97faa18ddab07e7125d4c2387554351a2e0b097b0135033a15b4c40e878c30191ed0b41660ef108bf92f09cfd80f880335d5d00d35c7edc52f",
          "sha256": "12071a5d9336b30f24ca190ef1192612cafee6d7656ee750f35160845d83805c",
          "sha1": "89003e853b5c2e8b43ddcedb6ae292f540418fd3",
          "md5": "b5b64c56caa8f0cb13eb1745b6520a84"
        }
      ]
    }
  ]
}
