{
  "formatVersion": "1.1",
  "component": {
    "url": "../../kotlin-compose/0.15.0/kotlin-compose-0.15.0.module",
    "group": "ai.factoredui",
    "module": "kotlin-compose",
    "version": "0.15.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14"
    }
  },
  "variants": [
    {
      "name": "desktopApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "ai.factoredui",
          "module": "kotlin-compose-schema",
          "version": {
            "requires": "0.15.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.21"
          }
        }
      ],
      "files": [
        {
          "name": "kotlin-compose-desktop-0.15.0.jar",
          "url": "kotlin-compose-desktop-0.15.0.jar",
          "size": 804175,
          "sha512": "a70578006af5572a57f7c382d72757876daedf54839c41fc50a4887e21561364cdf07fbd615f7373e0048b25fb3f60737c041cfc000c92687e57cdb0f2da2109",
          "sha256": "3dcdd3461c5276aa5459d0c3ba299154d68b6bfd542e31aea1557a5e66a6140b",
          "sha1": "8f9854d44efdbff712d0798b8eb657fe977c22f5",
          "md5": "7b32d64200af9f3eb2bfad411cb79816"
        }
      ]
    },
    {
      "name": "desktopRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "ai.factoredui",
          "module": "kotlin-compose-schema",
          "version": {
            "requires": "0.15.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.21"
          }
        },
        {
          "group": "org.jetbrains.compose.desktop",
          "module": "desktop-jvm-linux-x64",
          "version": {
            "requires": "1.10.3"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-okhttp",
          "version": {
            "requires": "3.2.0"
          }
        },
        {
          "group": "org.jetbrains.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "1.10.3"
          }
        },
        {
          "group": "org.jetbrains.compose.foundation",
          "module": "foundation",
          "version": {
            "requires": "1.10.3"
          }
        },
        {
          "group": "org.jetbrains.compose.material3",
          "module": "material3",
          "version": {
            "requires": "1.9.0-beta03"
          }
        },
        {
          "group": "org.jetbrains.compose.ui",
          "module": "ui",
          "version": {
            "requires": "1.10.3"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.11.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.10.2"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-datetime",
          "version": {
            "requires": "0.7.1"
          }
        },
        {
          "group": "io.coil-kt.coil3",
          "module": "coil-compose",
          "version": {
            "requires": "3.2.0"
          }
        },
        {
          "group": "io.coil-kt.coil3",
          "module": "coil-network-ktor3",
          "version": {
            "requires": "3.2.0"
          }
        },
        {
          "group": "io.coil-kt.coil3",
          "module": "coil-svg",
          "version": {
            "requires": "3.2.0"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-core",
          "version": {
            "requires": "3.2.0"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-content-negotiation",
          "version": {
            "requires": "3.2.0"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-serialization-kotlinx-json",
          "version": {
            "requires": "3.2.0"
          }
        }
      ],
      "files": [
        {
          "name": "kotlin-compose-desktop-0.15.0.jar",
          "url": "kotlin-compose-desktop-0.15.0.jar",
          "size": 804175,
          "sha512": "a70578006af5572a57f7c382d72757876daedf54839c41fc50a4887e21561364cdf07fbd615f7373e0048b25fb3f60737c041cfc000c92687e57cdb0f2da2109",
          "sha256": "3dcdd3461c5276aa5459d0c3ba299154d68b6bfd542e31aea1557a5e66a6140b",
          "sha1": "8f9854d44efdbff712d0798b8eb657fe977c22f5",
          "md5": "7b32d64200af9f3eb2bfad411cb79816"
        }
      ]
    },
    {
      "name": "desktopSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "kotlin-compose-desktop-0.15.0-sources.jar",
          "url": "kotlin-compose-desktop-0.15.0-sources.jar",
          "size": 95544,
          "sha512": "9da8e5e151b8ef0ce8a33e8aabadd4a8f195402148a75dc9115bed2e954215c10a499181a349c806b09c1a02a42e2e5049a47f942f48e43df628e1092836b5e9",
          "sha256": "206f8e38ef923b5dd689dbdd1a1066327ac2ff269c04076c6f73578e49e75c6f",
          "sha1": "c74999836bfa5c8403213b700af15869155e1073",
          "md5": "75b3d82e508bff7f78fede7ea7b1a078"
        }
      ]
    }
  ]
}
