{
  "formatVersion": "1.1",
  "component": {
    "url": "../../kotlin-compose-schema/0.19.0/kotlin-compose-schema-0.19.0.module",
    "group": "ai.factoredui",
    "module": "kotlin-compose-schema",
    "version": "0.19.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14"
    }
  },
  "variants": [
    {
      "name": "iosSimulatorArm64ApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.21"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.11.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-datetime",
          "version": {
            "requires": "0.7.1"
          }
        }
      ],
      "files": [
        {
          "name": "kotlin-compose-schema-iosSimulatorArm64Main-0.19.0.klib",
          "url": "kotlin-compose-schema-iossimulatorarm64-0.19.0.klib",
          "size": 112944,
          "sha512": "919217386614aff2684a62d729b50790e04b8397a697a55db9999e81d5e960ccf60c65439d587aad3a91b55d06edcb90099354e664c4f962b6e95d41e511f76c",
          "sha256": "c33d6da0222814acad0e101dc36b9e70d368601e81e593c0fa82dc33bbbcd92c",
          "sha1": "4f12661a6ace529a4fd122465a8ee93d07b30c46",
          "md5": "1f1c5b718baf33435a19322a7fc63d65"
        }
      ]
    },
    {
      "name": "iosSimulatorArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "files": [
        {
          "name": "kotlin-compose-schema-iossimulatorarm64-0.19.0-sources.jar",
          "url": "kotlin-compose-schema-iossimulatorarm64-0.19.0-sources.jar",
          "size": 11244,
          "sha512": "4f4fab68f47ca454347578d19a8686b5dc6d91880e982fd2ad2b00f30766de0e444f09cb6f94ced0f2cbd5a2748258be422665dcbc86dba910198bae1d2e7e23",
          "sha256": "98d201c5535c8ec3512dab69330bbbe3c2c19592d3a076c1131fc37ff0739ac7",
          "sha1": "f90a56dd668840053b36c36fb9bfaafba11c0ab9",
          "md5": "93f15f553e8b647097b619e1e104df7c"
        }
      ]
    },
    {
      "name": "iosSimulatorArm64MetadataElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.21"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.11.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-datetime",
          "version": {
            "requires": "0.7.1"
          }
        }
      ],
      "files": [
        {
          "name": "kotlin-compose-schema-iossimulatorarm64-0.19.0-metadata.jar",
          "url": "kotlin-compose-schema-iossimulatorarm64-0.19.0-metadata.jar",
          "size": 261,
          "sha512": "382c1cd4d39d6c01cdd2ebb61287f9891c9321fbbc1eb38b568f7499b903680916223b8b6c18874db7e7d71c9a011f4f9cd199c1af05301e347f13e71e41eb46",
          "sha256": "6d4f53c4d050f0cb9010eee38eeb6efc032057e951a896ebe530b02d89207b8a",
          "sha1": "28eda809c2c66a046acf12de48e556a5ce1fcaec",
          "md5": "51be341088d00f238ee27a391a71a2d3"
        }
      ]
    }
  ]
}
