{
  "formatVersion": "1.1",
  "component": {
    "url": "../../kotlin-compose-schema/0.15.1/kotlin-compose-schema-0.15.1.module",
    "group": "ai.factoredui",
    "module": "kotlin-compose-schema",
    "version": "0.15.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14"
    }
  },
  "variants": [
    {
      "name": "iosArm64ApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.21"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.11.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-datetime",
          "version": {
            "requires": "0.7.1"
          }
        }
      ],
      "files": [
        {
          "name": "kotlin-compose-schema-iosArm64Main-0.15.1.klib",
          "url": "kotlin-compose-schema-iosarm64-0.15.1.klib",
          "size": 111025,
          "sha512": "1977baa961d77e9965147c2486c6b29b378b87b37604f55e19e4a8f1a68176fc0f2d41000547f08aad17aefedaa3d18bc9b6743b7f273ca86947a0ecb4bded41",
          "sha256": "d91eca00d08dd42b7211dc68cea3c056dc7e1f91171f54ece1bd16c4cec1a63c",
          "sha1": "43c0ce69ba074728fbf47a90666ce957c5b41138",
          "md5": "38183c714ad38447c4248e23f390b4e5"
        }
      ]
    },
    {
      "name": "iosArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "files": [
        {
          "name": "kotlin-compose-schema-iosarm64-0.15.1-sources.jar",
          "url": "kotlin-compose-schema-iosarm64-0.15.1-sources.jar",
          "size": 10701,
          "sha512": "e03eabd24f7ad18525a53b2efdcbcd0587aeb9e5b04013ab6bf4e2cfdfa0ddd43e12eb8438375e892759fc85f72eeb0cf7b860ee4879b8d7139d14920dad2276",
          "sha256": "a7fe9cc4be4ffcf073a969764e26d8bb7269094079301e8370e5a752d9e90dd9",
          "sha1": "a1431a695180b1ca4b85418facb62d09da7942eb",
          "md5": "7aa00ebdc36bf4eddfd3db43fe3759a1"
        }
      ]
    },
    {
      "name": "iosArm64MetadataElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.21"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.11.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-datetime",
          "version": {
            "requires": "0.7.1"
          }
        }
      ],
      "files": [
        {
          "name": "kotlin-compose-schema-iosarm64-0.15.1-metadata.jar",
          "url": "kotlin-compose-schema-iosarm64-0.15.1-metadata.jar",
          "size": 261,
          "sha512": "91a88ba990e9ce9275f43bcb42080a0ed5efa76a02662dd6a9d7a1673701840f675ce410a1192988da41f1d4fa17e2abcfc60a1165c83883f74dcea8b4d14068",
          "sha256": "af2586f52cdb756759bb4cd9d33a3229c2070dc3b1c8b83c4a0de36924d37f2b",
          "sha1": "8bbee9d5fc7d80cc1483bcbf78ebca9d5d20595c",
          "md5": "c7d02df115e9e8a8b9840fa3aa25f0c1"
        }
      ]
    }
  ]
}
