{
  "formatVersion": "1.1",
  "component": {
    "url": "../../kotlin-compose/0.8.0/kotlin-compose-0.8.0.module",
    "group": "ai.factoredui",
    "module": "kotlin-compose",
    "version": "0.8.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14"
    }
  },
  "variants": [
    {
      "name": "desktopApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.21"
          }
        }
      ],
      "files": [
        {
          "name": "kotlin-compose-desktop-0.8.0.jar",
          "url": "kotlin-compose-desktop-0.8.0.jar",
          "size": 428168,
          "sha512": "0c330c72d1cd17b80428644b99393f19f32962a5383290c3572371ca659a2eaf163041c174baf526847f38172d1edbabc414c1ac69dc96e3484d44429450879e",
          "sha256": "53f0f0062dc0405522713ad3b1cbee0b5e8c1b8b1d9d9e481d0d13546b1daeb3",
          "sha1": "5e5b09d5273e1fce0697aba0f210cc925736a234",
          "md5": "7a8fac1b26866c05d49946287764ad18"
        }
      ]
    },
    {
      "name": "desktopRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.21"
          }
        },
        {
          "group": "org.jetbrains.compose.desktop",
          "module": "desktop-jvm-linux-x64",
          "version": {
            "requires": "1.10.3"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-okhttp",
          "version": {
            "requires": "3.2.0"
          }
        },
        {
          "group": "org.jetbrains.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "1.10.3"
          }
        },
        {
          "group": "org.jetbrains.compose.foundation",
          "module": "foundation",
          "version": {
            "requires": "1.10.3"
          }
        },
        {
          "group": "org.jetbrains.compose.material3",
          "module": "material3",
          "version": {
            "requires": "1.9.0-beta03"
          }
        },
        {
          "group": "org.jetbrains.compose.ui",
          "module": "ui",
          "version": {
            "requires": "1.10.3"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.11.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.10.2"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-datetime",
          "version": {
            "requires": "0.7.1"
          }
        },
        {
          "group": "io.coil-kt.coil3",
          "module": "coil-compose",
          "version": {
            "requires": "3.2.0"
          }
        },
        {
          "group": "io.coil-kt.coil3",
          "module": "coil-network-ktor3",
          "version": {
            "requires": "3.2.0"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-core",
          "version": {
            "requires": "3.2.0"
          }
        }
      ],
      "files": [
        {
          "name": "kotlin-compose-desktop-0.8.0.jar",
          "url": "kotlin-compose-desktop-0.8.0.jar",
          "size": 428168,
          "sha512": "0c330c72d1cd17b80428644b99393f19f32962a5383290c3572371ca659a2eaf163041c174baf526847f38172d1edbabc414c1ac69dc96e3484d44429450879e",
          "sha256": "53f0f0062dc0405522713ad3b1cbee0b5e8c1b8b1d9d9e481d0d13546b1daeb3",
          "sha1": "5e5b09d5273e1fce0697aba0f210cc925736a234",
          "md5": "7a8fac1b26866c05d49946287764ad18"
        }
      ]
    },
    {
      "name": "desktopSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "kotlin-compose-desktop-0.8.0-sources.jar",
          "url": "kotlin-compose-desktop-0.8.0-sources.jar",
          "size": 52062,
          "sha512": "80f34ca7c60a8b017143cf03f3d99341dd8cec2edd1be150cb2bdf8fae48cee7badc4f34f6e0a3c1e6896177735e5bb906b5d150a32f1b021ab58792e1db4bac",
          "sha256": "71667336e039ed2bdfcd81c7f7edda3a3620c512dfa780c62a4e7ba525672e57",
          "sha1": "af69de77082ff43a1c876fc9204d7a7d24e81f38",
          "md5": "5456a14829f7c9a950ebddcb71c09fb9"
        }
      ]
    }
  ]
}
