{
  "formatVersion": "1.1",
  "component": {
    "url": "../../kotlin-compose-schema/0.15.1/kotlin-compose-schema-0.15.1.module",
    "group": "ai.factoredui",
    "module": "kotlin-compose-schema",
    "version": "0.15.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14"
    }
  },
  "variants": [
    {
      "name": "linuxX64ApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "linux_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.21"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.11.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-datetime",
          "version": {
            "requires": "0.7.1"
          }
        }
      ],
      "files": [
        {
          "name": "kotlin-compose-schema-linuxX64Main-0.15.1.klib",
          "url": "kotlin-compose-schema-linuxx64-0.15.1.klib",
          "size": 111027,
          "sha512": "757c1406a68359abb765704e0b85ffd57aeded56b9c62fb1665a0006ce96797696f0efd4ca7aa2b880810f09a6b57a568d8ef7e7b48f6c4c4f3a13868d36698d",
          "sha256": "a2cc4990cc91707bdaa1bb8baa818fc659b008384a73f746a4b55b9984b0a33f",
          "sha1": "5d1e3835242418230de7e5a6487cf0501d8d0e92",
          "md5": "170a61b8be4a4be6b5cd0bd8f5e2b25f"
        }
      ]
    },
    {
      "name": "linuxX64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "linux_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "files": [
        {
          "name": "kotlin-compose-schema-linuxx64-0.15.1-sources.jar",
          "url": "kotlin-compose-schema-linuxx64-0.15.1-sources.jar",
          "size": 10701,
          "sha512": "e03eabd24f7ad18525a53b2efdcbcd0587aeb9e5b04013ab6bf4e2cfdfa0ddd43e12eb8438375e892759fc85f72eeb0cf7b860ee4879b8d7139d14920dad2276",
          "sha256": "a7fe9cc4be4ffcf073a969764e26d8bb7269094079301e8370e5a752d9e90dd9",
          "sha1": "a1431a695180b1ca4b85418facb62d09da7942eb",
          "md5": "7aa00ebdc36bf4eddfd3db43fe3759a1"
        }
      ]
    }
  ]
}
