{
  "formatVersion": "1.1",
  "component": {
    "url": "../../kotlin-engine/0.20.3/kotlin-engine-0.20.3.module",
    "group": "ai.factoredui",
    "module": "kotlin-engine",
    "version": "0.20.3",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14"
    }
  },
  "variants": [
    {
      "name": "iosX64ApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "ai.factoredui",
          "module": "kotlin-compose-schema",
          "version": {
            "requires": "0.20.3"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.21"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.11.0"
          }
        }
      ],
      "files": [
        {
          "name": "kotlin-engine-iosX64Main-0.20.3.klib",
          "url": "kotlin-engine-iosx64-0.20.3.klib",
          "size": 73999,
          "sha512": "106cdb8ca129bd29044f6d5bf63c3ecae8b7fb7b50d572168e6f644c40faa87e8ad823a5632d531e120c8e6a63a523fc9d1b8c82996d4baaaa230ee0c764ac6b",
          "sha256": "fb43ac5a4edac27cf41cb25dea38f4f1ef3e96f7ba6ffd5ce235bc0ebe5c09e2",
          "sha1": "a62fed0ab4f7116c69b2c48c3465b1111fd55db1",
          "md5": "3e8377c179a507892b402d54a0da00d2"
        }
      ]
    },
    {
      "name": "iosX64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "files": [
        {
          "name": "kotlin-engine-iosx64-0.20.3-sources.jar",
          "url": "kotlin-engine-iosx64-0.20.3-sources.jar",
          "size": 12466,
          "sha512": "64fd9f6420b2aea8e49b9b1c8e9f74b7b1590d51441509053c81d6938126bbd5376f8e3906583c32e296dd31055ab1b9756ddcfed6a9f30f6e8f968bad154fa1",
          "sha256": "dc8377b57cf44787664168ef1d1e1106cfba6c2299e91d4c1eb488ea0d5db025",
          "sha1": "eb97f38572b70bdbf1fe7cb88c68eac18830fc5a",
          "md5": "326b83071cbbb8de717754774c4007c1"
        }
      ]
    },
    {
      "name": "iosX64MetadataElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "ai.factoredui",
          "module": "kotlin-compose-schema",
          "version": {
            "requires": "0.20.3"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.21"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.11.0"
          }
        }
      ],
      "files": [
        {
          "name": "kotlin-engine-iosx64-0.20.3-metadata.jar",
          "url": "kotlin-engine-iosx64-0.20.3-metadata.jar",
          "size": 261,
          "sha512": "b7ba48d375e2d69e3eefd3ea5772b93cb9cea6b2511dedd46059edc2f3344ab2403e74d3e7e8323db92db038aa03dc629bf4160babce451f4d1a938504fc3be2",
          "sha256": "0df7dd5049d5335b9f6c3fde866a0aa91c5cebd8d5e5fb2804147e45d2ae76f8",
          "sha1": "65d8d269d9498c479637e473efc41a6e9f1d8c7b",
          "md5": "f1234bfece7962eb7cf13f1c1c3f9ffd"
        }
      ]
    }
  ]
}
