{
  "formatVersion": "1.1",
  "component": {
    "url": "../../kotlin-compose-schema/0.20.0/kotlin-compose-schema-0.20.0.module",
    "group": "ai.factoredui",
    "module": "kotlin-compose-schema",
    "version": "0.20.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14"
    }
  },
  "variants": [
    {
      "name": "wasmJsApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "wasm",
        "org.jetbrains.kotlin.wasm.target": "js"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.21"
          }
        }
      ],
      "files": [
        {
          "name": "kotlin-compose-schema-wasm-js-0.20.0.klib",
          "url": "kotlin-compose-schema-wasm-js-0.20.0.klib",
          "size": 122460,
          "sha512": "c4fd5a878f10f17386a5a37227930bd94089e2a6b28d7cd2c7435a1e54f53ef4da90bcb36809ff0e7accb4988bac1cbbfcaaa025ffb7c487fc40b2ffb5d3b660",
          "sha256": "cf9ff7c3d160082bc2528d0462c01f83855c750c035701d48c1192ac9a9cfa19",
          "sha1": "ec70d01d8984982fea0983a825729833fba8f6aa",
          "md5": "e92dcbb3078bbe8a94ef80db8a58ac20"
        }
      ]
    },
    {
      "name": "wasmJsRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.platform.type": "wasm",
        "org.jetbrains.kotlin.wasm.target": "js"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.21"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.11.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-datetime",
          "version": {
            "requires": "0.7.1"
          }
        }
      ],
      "files": [
        {
          "name": "kotlin-compose-schema-wasm-js-0.20.0.klib",
          "url": "kotlin-compose-schema-wasm-js-0.20.0.klib",
          "size": 122460,
          "sha512": "c4fd5a878f10f17386a5a37227930bd94089e2a6b28d7cd2c7435a1e54f53ef4da90bcb36809ff0e7accb4988bac1cbbfcaaa025ffb7c487fc40b2ffb5d3b660",
          "sha256": "cf9ff7c3d160082bc2528d0462c01f83855c750c035701d48c1192ac9a9cfa19",
          "sha1": "ec70d01d8984982fea0983a825729833fba8f6aa",
          "md5": "e92dcbb3078bbe8a94ef80db8a58ac20"
        }
      ]
    },
    {
      "name": "wasmJsSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.platform.type": "wasm",
        "org.jetbrains.kotlin.wasm.target": "js"
      },
      "files": [
        {
          "name": "kotlin-compose-schema-wasm-js-0.20.0-sources.jar",
          "url": "kotlin-compose-schema-wasm-js-0.20.0-sources.jar",
          "size": 11925,
          "sha512": "d1645926de0ed497e29af6c88a436b8b476605cbcf4c24d77f201dde5dc5c9cc1ebab9abcc50f0ac083e71007b9d0274013de0c58ad30852cae2bab4e9d00cb1",
          "sha256": "73d01c96b3c64ca8363f6f66713809c860ec92db0979d282b8a093525ea084e0",
          "sha1": "91339d0e477881713eba748395a8388c2c5e97d9",
          "md5": "dd76c50fd5f31467021fb2455b52bc31"
        }
      ]
    }
  ]
}
