{
  "formatVersion": "1.1",
  "component": {
    "url": "../../kotlin-compose/0.12.0/kotlin-compose-0.12.0.module",
    "group": "ai.factoredui",
    "module": "kotlin-compose",
    "version": "0.12.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14"
    }
  },
  "variants": [
    {
      "name": "desktopApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "ai.factoredui",
          "module": "kotlin-compose-schema",
          "version": {
            "requires": "0.12.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.21"
          }
        }
      ],
      "files": [
        {
          "name": "kotlin-compose-desktop-0.12.0.jar",
          "url": "kotlin-compose-desktop-0.12.0.jar",
          "size": 799285,
          "sha512": "a030b38e91ed0249261e0032f1a524f521a23b2c06a5a0a5f099953e1f6fd83e9d6123d837f8e9d70eb46cdb678f488d49d94eeb4ce762b55fbd32505fbc3fb4",
          "sha256": "cd6a3a434606c28a7640795d3d7278d6a6b879014265f0823b3525bd3426b008",
          "sha1": "9e0f01a3b59272d3bd87b2fa4d1c21fe3a9d1f13",
          "md5": "9b3cc085a17fe3e369af56b3b33cecb9"
        }
      ]
    },
    {
      "name": "desktopRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "ai.factoredui",
          "module": "kotlin-compose-schema",
          "version": {
            "requires": "0.12.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.21"
          }
        },
        {
          "group": "org.jetbrains.compose.desktop",
          "module": "desktop-jvm-linux-x64",
          "version": {
            "requires": "1.10.3"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-okhttp",
          "version": {
            "requires": "3.2.0"
          }
        },
        {
          "group": "org.jetbrains.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "1.10.3"
          }
        },
        {
          "group": "org.jetbrains.compose.foundation",
          "module": "foundation",
          "version": {
            "requires": "1.10.3"
          }
        },
        {
          "group": "org.jetbrains.compose.material3",
          "module": "material3",
          "version": {
            "requires": "1.9.0-beta03"
          }
        },
        {
          "group": "org.jetbrains.compose.ui",
          "module": "ui",
          "version": {
            "requires": "1.10.3"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.11.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.10.2"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-datetime",
          "version": {
            "requires": "0.7.1"
          }
        },
        {
          "group": "io.coil-kt.coil3",
          "module": "coil-compose",
          "version": {
            "requires": "3.2.0"
          }
        },
        {
          "group": "io.coil-kt.coil3",
          "module": "coil-network-ktor3",
          "version": {
            "requires": "3.2.0"
          }
        },
        {
          "group": "io.coil-kt.coil3",
          "module": "coil-svg",
          "version": {
            "requires": "3.2.0"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-core",
          "version": {
            "requires": "3.2.0"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-content-negotiation",
          "version": {
            "requires": "3.2.0"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-serialization-kotlinx-json",
          "version": {
            "requires": "3.2.0"
          }
        }
      ],
      "files": [
        {
          "name": "kotlin-compose-desktop-0.12.0.jar",
          "url": "kotlin-compose-desktop-0.12.0.jar",
          "size": 799285,
          "sha512": "a030b38e91ed0249261e0032f1a524f521a23b2c06a5a0a5f099953e1f6fd83e9d6123d837f8e9d70eb46cdb678f488d49d94eeb4ce762b55fbd32505fbc3fb4",
          "sha256": "cd6a3a434606c28a7640795d3d7278d6a6b879014265f0823b3525bd3426b008",
          "sha1": "9e0f01a3b59272d3bd87b2fa4d1c21fe3a9d1f13",
          "md5": "9b3cc085a17fe3e369af56b3b33cecb9"
        }
      ]
    },
    {
      "name": "desktopSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "kotlin-compose-desktop-0.12.0-sources.jar",
          "url": "kotlin-compose-desktop-0.12.0-sources.jar",
          "size": 93961,
          "sha512": "68024ef8d802eb3830a1acc04e8cd7e133b607f2ed41a5545ced6a26dfa9bb61d1d4edc0785861febeca7206871e736820c14f795362f92f0dd99c1022964662",
          "sha256": "f8bf2c5035b8a713b45477664e45c66162f81a8435463bb5885c09f1d9bc80f3",
          "sha1": "aab85d45f1287e6b6fff8364989dca586bfd6e72",
          "md5": "6e8dbbd1df243c6b7bf88ff3d8216083"
        }
      ]
    }
  ]
}
