{
  "formatVersion": "1.1",
  "component": {
    "url": "../../kotlin-compose/0.19.0/kotlin-compose-0.19.0.module",
    "group": "ai.factoredui",
    "module": "kotlin-compose",
    "version": "0.19.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14"
    }
  },
  "variants": [
    {
      "name": "iosArm64ApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "ai.factoredui",
          "module": "kotlin-compose-schema",
          "version": {
            "requires": "0.19.0"
          }
        },
        {
          "group": "ai.factoredui",
          "module": "kotlin-compose-capture",
          "version": {
            "requires": "0.19.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.21"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-darwin",
          "version": {
            "requires": "3.2.4"
          }
        },
        {
          "group": "org.jetbrains.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "1.10.3"
          }
        },
        {
          "group": "org.jetbrains.compose.foundation",
          "module": "foundation",
          "version": {
            "requires": "1.10.3"
          }
        },
        {
          "group": "org.jetbrains.compose.material3",
          "module": "material3",
          "version": {
            "requires": "1.9.0-beta03"
          }
        },
        {
          "group": "org.jetbrains.compose.ui",
          "module": "ui",
          "version": {
            "requires": "1.10.3"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.11.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.10.2"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-datetime",
          "version": {
            "requires": "0.7.1"
          }
        },
        {
          "group": "io.coil-kt.coil3",
          "module": "coil-compose",
          "version": {
            "requires": "3.2.0"
          }
        },
        {
          "group": "io.coil-kt.coil3",
          "module": "coil-network-ktor3",
          "version": {
            "requires": "3.2.0"
          }
        },
        {
          "group": "io.coil-kt.coil3",
          "module": "coil-svg",
          "version": {
            "requires": "3.2.0"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-core",
          "version": {
            "requires": "3.2.4"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-content-negotiation",
          "version": {
            "requires": "3.2.4"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-serialization-kotlinx-json",
          "version": {
            "requires": "3.2.4"
          }
        }
      ],
      "files": [
        {
          "name": "kotlin-compose-iosArm64Main-0.19.0.klib",
          "url": "kotlin-compose-iosarm64-0.19.0.klib",
          "size": 533226,
          "sha512": "bad54acf0dab458e60b9d2528f54f2b106cce5e5ac65fe03e5b28055fd94425cc6bfb0947c308b1c8ee2c1296b910d3d32e0cb8a76761e213ba726f0b660769a",
          "sha256": "493775e6c8bde8d6c072d2a93a9a2069698e1d7e53dd60512398b957d7029de6",
          "sha1": "6056f9de1c4801cb88fa13a50a33a097d62964c9",
          "md5": "6ac00874995b998f9a9b7ac325f7998b"
        }
      ]
    },
    {
      "name": "iosArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "files": [
        {
          "name": "kotlin-compose-iosarm64-0.19.0-sources.jar",
          "url": "kotlin-compose-iosarm64-0.19.0-sources.jar",
          "size": 74810,
          "sha512": "7a2dd9c9735cd8da22133d8476870215ff179513bf6c87d30b57817da0e6229fa56d5182b24f96bfdaf8973ab61472e8231a69f0270db26f65a611d020240276",
          "sha256": "5b4f081010436cccfc5d0c0001dfba606db064e907de8474bbddde3434e3a3ad",
          "sha1": "163c7bdb0fb76fae289f1e6c0503ea538e16d385",
          "md5": "293711537df63324d957610d85989018"
        }
      ]
    },
    {
      "name": "iosArm64ResourcesElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.libraryelements": "kotlin-multiplatformresources",
        "org.gradle.usage": "kotlin-multiplatformresources",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "ai.factoredui",
          "module": "kotlin-compose-schema",
          "version": {
            "requires": "0.19.0"
          }
        },
        {
          "group": "ai.factoredui",
          "module": "kotlin-compose-capture",
          "version": {
            "requires": "0.19.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.21"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-darwin",
          "version": {
            "requires": "3.2.4"
          }
        },
        {
          "group": "org.jetbrains.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "1.10.3"
          }
        },
        {
          "group": "org.jetbrains.compose.foundation",
          "module": "foundation",
          "version": {
            "requires": "1.10.3"
          }
        },
        {
          "group": "org.jetbrains.compose.material3",
          "module": "material3",
          "version": {
            "requires": "1.9.0-beta03"
          }
        },
        {
          "group": "org.jetbrains.compose.ui",
          "module": "ui",
          "version": {
            "requires": "1.10.3"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.11.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.10.2"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-datetime",
          "version": {
            "requires": "0.7.1"
          }
        },
        {
          "group": "io.coil-kt.coil3",
          "module": "coil-compose",
          "version": {
            "requires": "3.2.0"
          }
        },
        {
          "group": "io.coil-kt.coil3",
          "module": "coil-network-ktor3",
          "version": {
            "requires": "3.2.0"
          }
        },
        {
          "group": "io.coil-kt.coil3",
          "module": "coil-svg",
          "version": {
            "requires": "3.2.0"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-core",
          "version": {
            "requires": "3.2.4"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-content-negotiation",
          "version": {
            "requires": "3.2.4"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-serialization-kotlinx-json",
          "version": {
            "requires": "3.2.4"
          }
        }
      ],
      "files": [
        {
          "name": "kotlin-compose-0.19.0.kotlin_resources.zip",
          "url": "kotlin-compose-iosarm64-0.19.0-kotlin_resources.kotlin_resources.zip",
          "size": 344,
          "sha512": "bd0b4f2157b80a08f06955d281d94f8f37518a03a4439c5949f44ccc7582f758c2766eee8537f8575b2959b75a43f07162524b023c58063d227ffbbb8e2d056f",
          "sha256": "a2086df92cbfad376858b99b08cbac1a96cc451212a79e034b63fc2d399d4b70",
          "sha1": "55fe38b1271420d06af109f190bc9af54d8e133e",
          "md5": "1eeb7e00b4f3774bc5c61e4d1630acc4"
        }
      ]
    },
    {
      "name": "iosArm64MetadataElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "ai.factoredui",
          "module": "kotlin-compose-schema",
          "version": {
            "requires": "0.19.0"
          }
        },
        {
          "group": "ai.factoredui",
          "module": "kotlin-compose-capture",
          "version": {
            "requires": "0.19.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.21"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-darwin",
          "version": {
            "requires": "3.2.4"
          }
        },
        {
          "group": "org.jetbrains.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "1.10.3"
          }
        },
        {
          "group": "org.jetbrains.compose.foundation",
          "module": "foundation",
          "version": {
            "requires": "1.10.3"
          }
        },
        {
          "group": "org.jetbrains.compose.material3",
          "module": "material3",
          "version": {
            "requires": "1.9.0-beta03"
          }
        },
        {
          "group": "org.jetbrains.compose.ui",
          "module": "ui",
          "version": {
            "requires": "1.10.3"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.11.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.10.2"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-datetime",
          "version": {
            "requires": "0.7.1"
          }
        },
        {
          "group": "io.coil-kt.coil3",
          "module": "coil-compose",
          "version": {
            "requires": "3.2.0"
          }
        },
        {
          "group": "io.coil-kt.coil3",
          "module": "coil-network-ktor3",
          "version": {
            "requires": "3.2.0"
          }
        },
        {
          "group": "io.coil-kt.coil3",
          "module": "coil-svg",
          "version": {
            "requires": "3.2.0"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-core",
          "version": {
            "requires": "3.2.4"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-content-negotiation",
          "version": {
            "requires": "3.2.4"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-serialization-kotlinx-json",
          "version": {
            "requires": "3.2.4"
          }
        }
      ],
      "files": [
        {
          "name": "kotlin-compose-iosarm64-0.19.0-metadata.jar",
          "url": "kotlin-compose-iosarm64-0.19.0-metadata.jar",
          "size": 2500,
          "sha512": "814f7048a968b2e3e46291bd25cbcf95ceac0235ee6fb180cdea03755b91d1ea5c2bf324b9086950d6297a1717e949878906bea894d44b0ccdbab6832adeef45",
          "sha256": "6d25b01db6a5999c14ebac2fffa363b2e20493a5a057148ebb4de0a9c733fa94",
          "sha1": "f9e66c751ef294059d1f9b328a4ec5e31a4f2326",
          "md5": "065123e8ebf6a79ebf9d5bcbbc7c9c67"
        }
      ]
    }
  ]
}
