{
  "formatVersion": "1.1",
  "component": {
    "url": "../../kotlin-compose/0.15.2/kotlin-compose-0.15.2.module",
    "group": "ai.factoredui",
    "module": "kotlin-compose",
    "version": "0.15.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14"
    }
  },
  "variants": [
    {
      "name": "desktopApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "ai.factoredui",
          "module": "kotlin-compose-schema",
          "version": {
            "requires": "0.15.2"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.21"
          }
        }
      ],
      "files": [
        {
          "name": "kotlin-compose-desktop-0.15.2.jar",
          "url": "kotlin-compose-desktop-0.15.2.jar",
          "size": 811129,
          "sha512": "05744aba04728e32957191409046223d339f76d78e110a6d9804397b9e841964fec8999a8ac96005982901b6587f86908ef754c0bcb63a0d935620938a1f7282",
          "sha256": "166df4a7caffc3ecd39944cd571ee05f0725470ef993afb8cbf7a17011b4b634",
          "sha1": "00708655bafff17df772bfac619e5fdf30f8577f",
          "md5": "67fb7e57f2f277168854a03306ec6bf4"
        }
      ]
    },
    {
      "name": "desktopRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "ai.factoredui",
          "module": "kotlin-compose-schema",
          "version": {
            "requires": "0.15.2"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.21"
          }
        },
        {
          "group": "org.jetbrains.compose.desktop",
          "module": "desktop-jvm-linux-x64",
          "version": {
            "requires": "1.10.3"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-okhttp",
          "version": {
            "requires": "3.2.0"
          }
        },
        {
          "group": "org.jetbrains.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "1.10.3"
          }
        },
        {
          "group": "org.jetbrains.compose.foundation",
          "module": "foundation",
          "version": {
            "requires": "1.10.3"
          }
        },
        {
          "group": "org.jetbrains.compose.material3",
          "module": "material3",
          "version": {
            "requires": "1.9.0-beta03"
          }
        },
        {
          "group": "org.jetbrains.compose.ui",
          "module": "ui",
          "version": {
            "requires": "1.10.3"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.11.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.10.2"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-datetime",
          "version": {
            "requires": "0.7.1"
          }
        },
        {
          "group": "io.coil-kt.coil3",
          "module": "coil-compose",
          "version": {
            "requires": "3.2.0"
          }
        },
        {
          "group": "io.coil-kt.coil3",
          "module": "coil-network-ktor3",
          "version": {
            "requires": "3.2.0"
          }
        },
        {
          "group": "io.coil-kt.coil3",
          "module": "coil-svg",
          "version": {
            "requires": "3.2.0"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-core",
          "version": {
            "requires": "3.2.0"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-content-negotiation",
          "version": {
            "requires": "3.2.0"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-serialization-kotlinx-json",
          "version": {
            "requires": "3.2.0"
          }
        }
      ],
      "files": [
        {
          "name": "kotlin-compose-desktop-0.15.2.jar",
          "url": "kotlin-compose-desktop-0.15.2.jar",
          "size": 811129,
          "sha512": "05744aba04728e32957191409046223d339f76d78e110a6d9804397b9e841964fec8999a8ac96005982901b6587f86908ef754c0bcb63a0d935620938a1f7282",
          "sha256": "166df4a7caffc3ecd39944cd571ee05f0725470ef993afb8cbf7a17011b4b634",
          "sha1": "00708655bafff17df772bfac619e5fdf30f8577f",
          "md5": "67fb7e57f2f277168854a03306ec6bf4"
        }
      ]
    },
    {
      "name": "desktopSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "kotlin-compose-desktop-0.15.2-sources.jar",
          "url": "kotlin-compose-desktop-0.15.2-sources.jar",
          "size": 95918,
          "sha512": "ec7f5b48c85ee5bdea527fc81dd5f8f90acbeaddd0231b1fb8e10e3d902a10376e35c8aeba5d8bc444dcdaec2f9280d725dea1733015cdb264937f5129434474",
          "sha256": "9535a9fb571674cf111707f68e18d966295feb589870478ac3e0faf1470bb6b8",
          "sha1": "2c717059c1cdd03421d153588ce0ff8c365f64a8",
          "md5": "e5c716b68186c22784dcec495915b3f0"
        }
      ]
    }
  ]
}
