{
  "formatVersion": "1.1",
  "component": {
    "url": "../../kotlin-compose/0.8.0/kotlin-compose-0.8.0.module",
    "group": "ai.factoredui",
    "module": "kotlin-compose",
    "version": "0.8.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14"
    }
  },
  "variants": [
    {
      "name": "releaseApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.21"
          }
        }
      ],
      "files": [
        {
          "name": "kotlin-compose-release.aar",
          "url": "kotlin-compose-android-0.8.0.aar",
          "size": 400750,
          "sha512": "94f7588e2605d119097a0c1083b4502fac1d9d85cfe7f42581ab1d30a1c26b844927e5e937eea93465cc08325e2bf07666e07450bc955f38c1dbfbab074d0eea",
          "sha256": "00ceac194b6c9ba74e83db2ab325538bbfdf7c5907545f469a3547325ee7c31f",
          "sha1": "d55a77b1f1dc5450763644dc8c14bd6b0453b926",
          "md5": "35b0ea2f2cdff6f851e412bfc5a11396"
        }
      ]
    },
    {
      "name": "releaseRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "androidx.activity",
          "module": "activity-compose",
          "version": {
            "requires": "1.9.3"
          },
          "excludes": [
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-annotations-common"
            }
          ]
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-okhttp",
          "version": {
            "requires": "3.2.0"
          },
          "excludes": [
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-annotations-common"
            }
          ]
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.21"
          },
          "excludes": [
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-annotations-common"
            }
          ]
        },
        {
          "group": "org.jetbrains.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "1.10.3"
          },
          "excludes": [
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-annotations-common"
            }
          ]
        },
        {
          "group": "org.jetbrains.compose.foundation",
          "module": "foundation",
          "version": {
            "requires": "1.10.3"
          },
          "excludes": [
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-annotations-common"
            }
          ]
        },
        {
          "group": "org.jetbrains.compose.material3",
          "module": "material3",
          "version": {
            "requires": "1.9.0-beta03"
          },
          "excludes": [
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-annotations-common"
            }
          ]
        },
        {
          "group": "org.jetbrains.compose.ui",
          "module": "ui",
          "version": {
            "requires": "1.10.3"
          },
          "excludes": [
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-annotations-common"
            }
          ]
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.11.0"
          },
          "excludes": [
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-annotations-common"
            }
          ]
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.10.2"
          },
          "excludes": [
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-annotations-common"
            }
          ]
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-datetime",
          "version": {
            "requires": "0.7.1"
          },
          "excludes": [
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-annotations-common"
            }
          ]
        },
        {
          "group": "io.coil-kt.coil3",
          "module": "coil-compose",
          "version": {
            "requires": "3.2.0"
          },
          "excludes": [
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-annotations-common"
            }
          ]
        },
        {
          "group": "io.coil-kt.coil3",
          "module": "coil-network-ktor3",
          "version": {
            "requires": "3.2.0"
          },
          "excludes": [
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-annotations-common"
            }
          ]
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-core",
          "version": {
            "requires": "3.2.0"
          },
          "excludes": [
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-annotations-common"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "kotlin-compose-release.aar",
          "url": "kotlin-compose-android-0.8.0.aar",
          "size": 400750,
          "sha512": "94f7588e2605d119097a0c1083b4502fac1d9d85cfe7f42581ab1d30a1c26b844927e5e937eea93465cc08325e2bf07666e07450bc955f38c1dbfbab074d0eea",
          "sha256": "00ceac194b6c9ba74e83db2ab325538bbfdf7c5907545f469a3547325ee7c31f",
          "sha1": "d55a77b1f1dc5450763644dc8c14bd6b0453b926",
          "md5": "35b0ea2f2cdff6f851e412bfc5a11396"
        }
      ]
    },
    {
      "name": "releaseSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "android",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "files": [
        {
          "name": "kotlin-compose-android-0.8.0-sources.jar",
          "url": "kotlin-compose-android-0.8.0-sources.jar",
          "size": 52062,
          "sha512": "80f34ca7c60a8b017143cf03f3d99341dd8cec2edd1be150cb2bdf8fae48cee7badc4f34f6e0a3c1e6896177735e5bb906b5d150a32f1b021ab58792e1db4bac",
          "sha256": "71667336e039ed2bdfcd81c7f7edda3a3620c512dfa780c62a4e7ba525672e57",
          "sha1": "af69de77082ff43a1c876fc9204d7a7d24e81f38",
          "md5": "5456a14829f7c9a950ebddcb71c09fb9"
        }
      ]
    }
  ]
}
