{
  "formatVersion": "1.1",
  "component": {
    "url": "../../kotlin-compose/0.9.0/kotlin-compose-0.9.0.module",
    "group": "ai.factoredui",
    "module": "kotlin-compose",
    "version": "0.9.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14"
    }
  },
  "variants": [
    {
      "name": "releaseApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "ai.factoredui",
          "module": "kotlin-compose-schema",
          "version": {
            "requires": "0.9.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.21"
          }
        }
      ],
      "files": [
        {
          "name": "kotlin-compose-release.aar",
          "url": "kotlin-compose-android-0.9.0.aar",
          "size": 367220,
          "sha512": "60067eafc6e1a2e36059889fb881c3efc9175c37d05eaa6bdfa90c60e4aabc91e68f0616c21353410eb0f91fad06c357b4a08507f4870236e5ec85828b269da6",
          "sha256": "fc4d3dd11f1160d6b3c77d10732a104b91ee206ab4e770f635395bc9ddc22836",
          "sha1": "dbeb18fb3978c34cdf2bc48307564594cf0d9105",
          "md5": "e740cc68013fc8ccb8621c3fa04b0ee9"
        }
      ]
    },
    {
      "name": "releaseRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "androidx.activity",
          "module": "activity-compose",
          "version": {
            "requires": "1.9.3"
          },
          "excludes": [
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-annotations-common"
            }
          ]
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-okhttp",
          "version": {
            "requires": "3.2.0"
          },
          "excludes": [
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-annotations-common"
            }
          ]
        },
        {
          "group": "ai.factoredui",
          "module": "kotlin-compose-schema",
          "version": {
            "requires": "0.9.0"
          },
          "excludes": [
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-annotations-common"
            }
          ]
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.21"
          },
          "excludes": [
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-annotations-common"
            }
          ]
        },
        {
          "group": "org.jetbrains.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "1.10.3"
          },
          "excludes": [
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-annotations-common"
            }
          ]
        },
        {
          "group": "org.jetbrains.compose.foundation",
          "module": "foundation",
          "version": {
            "requires": "1.10.3"
          },
          "excludes": [
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-annotations-common"
            }
          ]
        },
        {
          "group": "org.jetbrains.compose.material3",
          "module": "material3",
          "version": {
            "requires": "1.9.0-beta03"
          },
          "excludes": [
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-annotations-common"
            }
          ]
        },
        {
          "group": "org.jetbrains.compose.ui",
          "module": "ui",
          "version": {
            "requires": "1.10.3"
          },
          "excludes": [
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-annotations-common"
            }
          ]
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.11.0"
          },
          "excludes": [
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-annotations-common"
            }
          ]
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.10.2"
          },
          "excludes": [
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-annotations-common"
            }
          ]
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-datetime",
          "version": {
            "requires": "0.7.1"
          },
          "excludes": [
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-annotations-common"
            }
          ]
        },
        {
          "group": "io.coil-kt.coil3",
          "module": "coil-compose",
          "version": {
            "requires": "3.2.0"
          },
          "excludes": [
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-annotations-common"
            }
          ]
        },
        {
          "group": "io.coil-kt.coil3",
          "module": "coil-network-ktor3",
          "version": {
            "requires": "3.2.0"
          },
          "excludes": [
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-annotations-common"
            }
          ]
        },
        {
          "group": "io.coil-kt.coil3",
          "module": "coil-svg",
          "version": {
            "requires": "3.2.0"
          },
          "excludes": [
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-annotations-common"
            }
          ]
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-core",
          "version": {
            "requires": "3.2.0"
          },
          "excludes": [
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-annotations-common"
            }
          ]
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-content-negotiation",
          "version": {
            "requires": "3.2.0"
          },
          "excludes": [
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-annotations-common"
            }
          ]
        },
        {
          "group": "io.ktor",
          "module": "ktor-serialization-kotlinx-json",
          "version": {
            "requires": "3.2.0"
          },
          "excludes": [
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-annotations-common"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "kotlin-compose-release.aar",
          "url": "kotlin-compose-android-0.9.0.aar",
          "size": 367220,
          "sha512": "60067eafc6e1a2e36059889fb881c3efc9175c37d05eaa6bdfa90c60e4aabc91e68f0616c21353410eb0f91fad06c357b4a08507f4870236e5ec85828b269da6",
          "sha256": "fc4d3dd11f1160d6b3c77d10732a104b91ee206ab4e770f635395bc9ddc22836",
          "sha1": "dbeb18fb3978c34cdf2bc48307564594cf0d9105",
          "md5": "e740cc68013fc8ccb8621c3fa04b0ee9"
        }
      ]
    },
    {
      "name": "releaseSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "android",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "files": [
        {
          "name": "kotlin-compose-android-0.9.0-sources.jar",
          "url": "kotlin-compose-android-0.9.0-sources.jar",
          "size": 56235,
          "sha512": "a2fac415e6814a96dd04e038d2f1d50fe750c6d3132d31f51cdfcae2dddd1727cf9dda0cbf73ed8449ab043cdb2ab7eeac5ce0c136b45a4e5a4f41368874c5f2",
          "sha256": "e56eeae4b3a67b34d41f45e284ee86f8c35e47b7a168e09a461b0d5d8811313c",
          "sha1": "6aede6f30433299f71a66434cdde9800b6ee96a3",
          "md5": "eec51c4ef0435812eff57c652b024b0c"
        }
      ]
    }
  ]
}
