{
  "formatVersion": "1.1",
  "component": {
    "url": "../../kotlin-compose-capture/0.17.2/kotlin-compose-capture-0.17.2.module",
    "group": "ai.factoredui",
    "module": "kotlin-compose-capture",
    "version": "0.17.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14"
    }
  },
  "variants": [
    {
      "name": "wasmJsApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "wasm",
        "org.jetbrains.kotlin.wasm.target": "js"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.21"
          }
        }
      ],
      "files": [
        {
          "name": "kotlin-compose-capture-wasm-js-0.17.2.klib",
          "url": "kotlin-compose-capture-wasm-js-0.17.2.klib",
          "size": 21480,
          "sha512": "f98565b4cf49df8f1b8f52283768947ed26dfb6fe834595328cfb9f55058c8b7a5e85b2ee40c6cb4a3e409752a783001974e43e1d640bb55806c804d0727019d",
          "sha256": "ec453bb2b1ca24b61c981c454a50fbd7747487ca7f487c86a31c367a0515ec3e",
          "sha1": "2ecb6ea61ae62917ec2f38db7ef070be34f93ac3",
          "md5": "621dea2c8b55f1d0e2c4848b492a57df"
        }
      ]
    },
    {
      "name": "wasmJsRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.platform.type": "wasm",
        "org.jetbrains.kotlin.wasm.target": "js"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.21"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.11.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-datetime",
          "version": {
            "requires": "0.7.1"
          }
        }
      ],
      "files": [
        {
          "name": "kotlin-compose-capture-wasm-js-0.17.2.klib",
          "url": "kotlin-compose-capture-wasm-js-0.17.2.klib",
          "size": 21480,
          "sha512": "f98565b4cf49df8f1b8f52283768947ed26dfb6fe834595328cfb9f55058c8b7a5e85b2ee40c6cb4a3e409752a783001974e43e1d640bb55806c804d0727019d",
          "sha256": "ec453bb2b1ca24b61c981c454a50fbd7747487ca7f487c86a31c367a0515ec3e",
          "sha1": "2ecb6ea61ae62917ec2f38db7ef070be34f93ac3",
          "md5": "621dea2c8b55f1d0e2c4848b492a57df"
        }
      ]
    },
    {
      "name": "wasmJsSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.platform.type": "wasm",
        "org.jetbrains.kotlin.wasm.target": "js"
      },
      "files": [
        {
          "name": "kotlin-compose-capture-wasm-js-0.17.2-sources.jar",
          "url": "kotlin-compose-capture-wasm-js-0.17.2-sources.jar",
          "size": 2675,
          "sha512": "2f30e91c5b3bb7af31334533cd53498c1f205f723d4956b8bd8d8d2c9480058b2ae47a8fdca96e615561199fa50a6a22b561bc5220848629ef7fe47dd537c6ef",
          "sha256": "c82f37fc21d50fc8ecc030b86b4137334808ac44ee33a7e7732c739eb29d0700",
          "sha1": "84a2b3c08bc728e17e68a868cfa57eada683f007",
          "md5": "1ce993c162e5d1582ebec69fad7b8a80"
        }
      ]
    }
  ]
}
