{
  "formatVersion": "1.1",
  "component": {
    "group": "ai.factoredui",
    "module": "kotlin-server",
    "version": "0.10.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.21"
          }
        }
      ],
      "files": [
        {
          "name": "kotlin-server-0.10.0.jar",
          "url": "kotlin-server-0.10.0.jar",
          "size": 12937,
          "sha512": "993a864f4889d7445077bf39f555a9183bc5bbdddcedb8ff78eb9824ca00b0c6c192077f38b50790f932a0c74b8e67ea1dc2be3c3530394a948988d2a83cb3f6",
          "sha256": "b1f6cc3c3d33e760e20a9fb52346daa2dda470596216214fa945014413a2a115",
          "sha1": "9e73b9064ac96859d4cde9c1d26fc4239a2811e1",
          "md5": "6d8bac3561e6ff3d606c56345ee68664"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "ai.factoredui",
          "module": "kotlin-compose-schema",
          "version": {
            "requires": "0.15.1"
          }
        },
        {
          "group": "ai.factoredui",
          "module": "kotlin-engine",
          "version": {
            "requires": "0.11.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.11.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.10.2"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-datetime",
          "version": {
            "requires": "0.7.1"
          }
        },
        {
          "group": "org.postgresql",
          "module": "postgresql",
          "version": {
            "requires": "42.7.4"
          }
        },
        {
          "group": "com.zaxxer",
          "module": "HikariCP",
          "version": {
            "requires": "5.1.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.21"
          }
        }
      ],
      "files": [
        {
          "name": "kotlin-server-0.10.0.jar",
          "url": "kotlin-server-0.10.0.jar",
          "size": 12937,
          "sha512": "993a864f4889d7445077bf39f555a9183bc5bbdddcedb8ff78eb9824ca00b0c6c192077f38b50790f932a0c74b8e67ea1dc2be3c3530394a948988d2a83cb3f6",
          "sha256": "b1f6cc3c3d33e760e20a9fb52346daa2dda470596216214fa945014413a2a115",
          "sha1": "9e73b9064ac96859d4cde9c1d26fc4239a2811e1",
          "md5": "6d8bac3561e6ff3d606c56345ee68664"
        }
      ]
    }
  ]
}
