{
  "formatVersion": "1.1",
  "component": {
    "group": "ai.factoredui",
    "module": "kotlin-server",
    "version": "0.10.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.21"
          }
        }
      ],
      "files": [
        {
          "name": "kotlin-server-0.10.0.jar",
          "url": "kotlin-server-0.10.0.jar",
          "size": 12937,
          "sha512": "364ecb7c578362e92a1fc937ef6a8f438b022ed4546326b7ff61f687036c5074c59544b2f05d577385e300db11ea9acbca678b312be3b169e43ee11745bd9fab",
          "sha256": "7af623ae4f701a4c29e0bbc1668701b7b54320ab9e2d7c762663e0def7ae2934",
          "sha1": "c09e835a95da76a246785c31504a93f2d1c3e3fe",
          "md5": "8b55191a2bce2dc2cc285fffb3f96fea"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "ai.factoredui",
          "module": "kotlin-compose-schema",
          "version": {
            "requires": "0.15.0"
          }
        },
        {
          "group": "ai.factoredui",
          "module": "kotlin-engine",
          "version": {
            "requires": "0.11.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.11.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.10.2"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-datetime",
          "version": {
            "requires": "0.7.1"
          }
        },
        {
          "group": "org.postgresql",
          "module": "postgresql",
          "version": {
            "requires": "42.7.4"
          }
        },
        {
          "group": "com.zaxxer",
          "module": "HikariCP",
          "version": {
            "requires": "5.1.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.21"
          }
        }
      ],
      "files": [
        {
          "name": "kotlin-server-0.10.0.jar",
          "url": "kotlin-server-0.10.0.jar",
          "size": 12937,
          "sha512": "364ecb7c578362e92a1fc937ef6a8f438b022ed4546326b7ff61f687036c5074c59544b2f05d577385e300db11ea9acbca678b312be3b169e43ee11745bd9fab",
          "sha256": "7af623ae4f701a4c29e0bbc1668701b7b54320ab9e2d7c762663e0def7ae2934",
          "sha1": "c09e835a95da76a246785c31504a93f2d1c3e3fe",
          "md5": "8b55191a2bce2dc2cc285fffb3f96fea"
        }
      ]
    }
  ]
}
